"""Explicit public exports; implementations load on first access."""

EXPORTS: dict[str, tuple[str, str]] = {
    "ContextViewProjectionSource": ("cayu.sessions.context_views", "ContextViewProjectionSource"),
    "ContextViewExtensionProjection": (
        "cayu.sessions.context_views",
        "ContextViewExtensionProjection",
    ),
    "CONTEXT_VIEW_CONTRACT_VERSION": (
        "cayu.sessions.context_views",
        "CONTEXT_VIEW_CONTRACT_VERSION",
    ),
    "CONTEXT_VIEW_STORE_VERSION": (
        "cayu.sessions.context_views",
        "CONTEXT_VIEW_STORE_VERSION",
    ),
    "ContextViewExtensionRecord": ("cayu.sessions.context_views", "ContextViewExtensionRecord"),
    "ContextViewExtensionRegistration": (
        "cayu.sessions.context_views",
        "ContextViewExtensionRegistration",
    ),
    "ContextViewLimits": ("cayu.sessions.context_views", "ContextViewLimits"),
    "ContextViewLifecycleEvent": (
        "cayu.sessions.context_views",
        "ContextViewLifecycleEvent",
    ),
    "ContextViewManifest": ("cayu.sessions.context_views", "ContextViewManifest"),
    "ContextViewOwnershipRequest": (
        "cayu.sessions.context_views",
        "ContextViewOwnershipRequest",
    ),
    "ContextViewPublicationRequest": (
        "cayu.sessions.context_views",
        "ContextViewPublicationRequest",
    ),
    "ContextViewReadback": ("cayu.sessions.context_views", "ContextViewReadback"),
    "ContextViewSelectionReceipt": (
        "cayu.sessions.context_views",
        "ContextViewSelectionReceipt",
    ),
    "ContextViewSelectionRequest": (
        "cayu.sessions.context_views",
        "ContextViewSelectionRequest",
    ),
    "ParticipantSessionBinding": (
        "cayu.sessions.context_views",
        "ParticipantSessionBinding",
    ),
    "ParticipantSessionCreationReceipt": (
        "cayu.sessions.context_views",
        "ParticipantSessionCreationReceipt",
    ),
    "ParticipantSessionCreationRequest": (
        "cayu.sessions.context_views",
        "ParticipantSessionCreationRequest",
    ),
    "ParticipantSessionExecutionRequest": (
        "cayu.sessions.context_views",
        "ParticipantSessionExecutionRequest",
    ),
    "RecipientSessionCreationRequest": (
        "cayu.sessions.context_views",
        "RecipientSessionCreationRequest",
    ),
    "RecipientSessionCreationReceipt": (
        "cayu.sessions.context_views",
        "RecipientSessionCreationReceipt",
    ),
    "ActiveModelCompletionStage": ("cayu.sessions.base", "ActiveModelCompletionStage"),
    "CHECKPOINT_SCHEMA_VERSION_KEY": ("cayu.sessions.checkpoints", "CHECKPOINT_SCHEMA_VERSION_KEY"),
    "CHILD_SESSION_CONTEXT_PROJECTION_VERSION": (
        "cayu.sessions.child_context",
        "CHILD_SESSION_CONTEXT_PROJECTION_VERSION",
    ),
    "CHILD_SESSION_PUBLIC_ALIAS_MAX_CHARS": (
        "cayu.sessions.child_context",
        "CHILD_SESSION_PUBLIC_ALIAS_MAX_CHARS",
    ),
    "CHILD_SESSION_PUBLIC_OCCURRENCE_ID_MAX_CHARS": (
        "cayu.sessions.child_context",
        "CHILD_SESSION_PUBLIC_OCCURRENCE_ID_MAX_CHARS",
    ),
    "CHILD_SESSION_RESULT_PROJECTION_VERSION": (
        "cayu.sessions.child_results",
        "CHILD_SESSION_RESULT_PROJECTION_VERSION",
    ),
    "CHILD_SESSION_RESULT_REFERENCE_VERSION": (
        "cayu.sessions.child_context",
        "CHILD_SESSION_RESULT_REFERENCE_VERSION",
    ),
    "CURRENT_CHECKPOINT_SCHEMA_VERSION": (
        "cayu.sessions.checkpoints",
        "CURRENT_CHECKPOINT_SCHEMA_VERSION",
    ),
    "CheckpointCompatibilityError": ("cayu.sessions.checkpoints", "CheckpointCompatibilityError"),
    "CheckpointRootFieldGuard": ("cayu.sessions.base", "CheckpointRootFieldGuard"),
    "CheckpointRootFieldProjection": ("cayu.sessions.base", "CheckpointRootFieldProjection"),
    "CheckpointTransform": ("cayu.sessions.base", "CheckpointTransform"),
    "ChildSessionContextContribution": (
        "cayu.sessions.child_context",
        "ChildSessionContextContribution",
    ),
    "ChildSessionContextContributor": (
        "cayu.sessions.child_context",
        "ChildSessionContextContributor",
    ),
    "ChildSessionContextCoverage": ("cayu.sessions.child_context", "ChildSessionContextCoverage"),
    "ChildSessionContextCoverageState": (
        "cayu.sessions.child_context",
        "ChildSessionContextCoverageState",
    ),
    "ChildSessionContextEntry": ("cayu.sessions.child_context", "ChildSessionContextEntry"),
    "ChildSessionContextOccurrence": (
        "cayu.sessions.child_context",
        "ChildSessionContextOccurrence",
    ),
    "ChildSessionContextProjection": (
        "cayu.sessions.child_context",
        "ChildSessionContextProjection",
    ),
    "ChildSessionContextTruncationReason": (
        "cayu.sessions.child_context",
        "ChildSessionContextTruncationReason",
    ),
    "ChildSessionResultProjection": ("cayu.sessions.child_results", "ChildSessionResultProjection"),
    "ChildSessionResultReference": ("cayu.sessions.child_context", "ChildSessionResultReference"),
    "ChildSessionResultUnavailable": (
        "cayu.sessions.child_results",
        "ChildSessionResultUnavailable",
    ),
    "CompactSessionRequest": ("cayu.sessions.base", "CompactSessionRequest"),
    "DEFAULT_CHILD_SESSION_RESULT_MAX_CHARS": (
        "cayu.sessions.child_results",
        "DEFAULT_CHILD_SESSION_RESULT_MAX_CHARS",
    ),
    "DEFAULT_PENDING_ACTION_RESULT_MAX_BYTES": (
        "cayu.sessions.pending_action_contracts",
        "DEFAULT_PENDING_ACTION_RESULT_MAX_BYTES",
    ),
    "DEFAULT_RECOVERY_CLEANUP_MAX_SUPERVISED_TASKS": (
        "cayu.sessions.cleanup",
        "DEFAULT_RECOVERY_CLEANUP_MAX_SUPERVISED_TASKS",
    ),
    "DEFAULT_RECOVERY_CLEANUP_OVERALL_TIMEOUT_SECONDS": (
        "cayu.sessions.cleanup",
        "DEFAULT_RECOVERY_CLEANUP_OVERALL_TIMEOUT_SECONDS",
    ),
    "DEFAULT_RECOVERY_CLEANUP_STEP_TIMEOUT_SECONDS": (
        "cayu.sessions.cleanup",
        "DEFAULT_RECOVERY_CLEANUP_STEP_TIMEOUT_SECONDS",
    ),
    "DeferredInteractionInput": ("cayu.sessions.transcript_input", "DeferredInteractionInput"),
    "DelegatedActionReference": (
        "cayu.sessions.pending_action_contracts",
        "DelegatedActionReference",
    ),
    "EnqueueSessionMessageRequest": ("cayu.sessions.messaging", "EnqueueSessionMessageRequest"),
    "EnqueueSessionMessageResult": ("cayu.sessions.messaging", "EnqueueSessionMessageResult"),
    "EventOrder": ("cayu.sessions.event_queries", "EventOrder"),
    "EventQuery": ("cayu.sessions.event_queries", "EventQuery"),
    "EventQueryResultTooLarge": ("cayu.sessions.event_queries", "EventQueryResultTooLarge"),
    "EventRecord": ("cayu.sessions.records", "EventRecord"),
    "EventSummary": ("cayu.sessions.summaries", "EventSummary"),
    "ForkExecutionProfileDecisionRecord": (
        "cayu.sessions.base",
        "ForkExecutionProfileDecisionRecord",
    ),
    "ForkExecutionProfileSelection": ("cayu.sessions.base", "ForkExecutionProfileSelection"),
    "ForkExecutionProfileSource": ("cayu.sessions.base", "ForkExecutionProfileSource"),
    "ForkSessionRequest": ("cayu.sessions.base", "ForkSessionRequest"),
    "ForkSourceSnapshot": ("cayu.sessions.base", "ForkSourceSnapshot"),
    "ForkSystemPromptPolicy": ("cayu.sessions.base", "ForkSystemPromptPolicy"),
    "ForkSystemPromptReplacement": ("cayu.sessions.base", "ForkSystemPromptReplacement"),
    "INITIAL_TRANSCRIPT_PENDING_CHECKPOINT_KEY": (
        "cayu.sessions.base",
        "INITIAL_TRANSCRIPT_PENDING_CHECKPOINT_KEY",
    ),
    "InMemorySessionStore": ("cayu.sessions.base", "InMemorySessionStore"),
    "IncompleteSessionRecoveryAction": (
        "cayu.sessions.recovery",
        "IncompleteSessionRecoveryAction",
    ),
    "IncompleteSessionRecoveryRequest": (
        "cayu.sessions.recovery",
        "IncompleteSessionRecoveryRequest",
    ),
    "IncompleteSessionRecoveryResult": (
        "cayu.sessions.recovery",
        "IncompleteSessionRecoveryResult",
    ),
    "IncompleteSessionsRecoveryPage": ("cayu.sessions.recovery", "IncompleteSessionsRecoveryPage"),
    "IncompleteSessionsRecoveryRequest": (
        "cayu.sessions.recovery",
        "IncompleteSessionsRecoveryRequest",
    ),
    "InteractionStatus": ("cayu.sessions.interactions", "InteractionStatus"),
    "InteractionSummaryEvidence": ("cayu.sessions.interactions", "InteractionSummaryEvidence"),
    "InteractionTransitionReceiptResult": (
        "cayu.sessions.base",
        "InteractionTransitionReceiptResult",
    ),
    "InteractionTransitionResult": ("cayu.sessions.base", "InteractionTransitionResult"),
    "InteractionTransitionSpec": ("cayu.sessions.base", "InteractionTransitionSpec"),
    "InterruptSessionRequest": ("cayu.sessions.base", "InterruptSessionRequest"),
    "InvocationOrigin": ("cayu.sessions.invocation", "InvocationOrigin"),
    "InvocationOriginClaim": ("cayu.sessions.invocation", "InvocationOriginClaim"),
    "InvocationOriginTrust": ("cayu.sessions.invocation", "InvocationOriginTrust"),
    "LabelSelectorOperator": ("cayu.sessions.queries", "LabelSelectorOperator"),
    "LabelSelectorRequirement": ("cayu.sessions.queries", "LabelSelectorRequirement"),
    "MAX_CHILD_SESSION_RESULT_MAX_CHARS": (
        "cayu.sessions.child_results",
        "MAX_CHILD_SESSION_RESULT_MAX_CHARS",
    ),
    "MAX_INCOMPLETE_SESSIONS_RECOVERY_CURSOR_BYTES": (
        "cayu.sessions.recovery",
        "MAX_INCOMPLETE_SESSIONS_RECOVERY_CURSOR_BYTES",
    ),
    "MAX_PENDING_ACTION_RESULT_BYTES": (
        "cayu.sessions.pending_action_contracts",
        "MAX_PENDING_ACTION_RESULT_BYTES",
    ),
    "MAX_SESSION_ID_BYTES": ("cayu.sessions.records", "MAX_SESSION_ID_BYTES"),
    "MAX_SESSION_LIST_CURSOR_BYTES": ("cayu.sessions.queries", "MAX_SESSION_LIST_CURSOR_BYTES"),
    "MIN_SUPPORTED_CHECKPOINT_SCHEMA_VERSION": (
        "cayu.sessions.checkpoints",
        "MIN_SUPPORTED_CHECKPOINT_SCHEMA_VERSION",
    ),
    "McpManifestBaseline": ("cayu.sessions.base", "McpManifestBaseline"),
    "McpManifestBaselineLoadResult": ("cayu.sessions.base", "McpManifestBaselineLoadResult"),
    "McpManifestHistoryConflict": ("cayu.sessions.base", "McpManifestHistoryConflict"),
    "McpManifestPublicationResult": ("cayu.sessions.base", "McpManifestPublicationResult"),
    "ModelCompletionManualRecoveryRequest": (
        "cayu.sessions.base",
        "ModelCompletionManualRecoveryRequest",
    ),
    "ModelCompletionManualRecoveryResult": (
        "cayu.sessions.base",
        "ModelCompletionManualRecoveryResult",
    ),
    "ModelCompletionStage": ("cayu.sessions.base", "ModelCompletionStage"),
    "ModelCompletionStageAbandonment": ("cayu.sessions.base", "ModelCompletionStageAbandonment"),
    "ModelCompletionStageAbandonmentResult": (
        "cayu.sessions.base",
        "ModelCompletionStageAbandonmentResult",
    ),
    "ModelCompletionStageDispatch": ("cayu.sessions.base", "ModelCompletionStageDispatch"),
    "ModelCompletionStageDisposition": ("cayu.sessions.base", "ModelCompletionStageDisposition"),
    "ModelCompletionStageRequest": ("cayu.sessions.base", "ModelCompletionStageRequest"),
    "ModelCompletionStageResult": ("cayu.sessions.base", "ModelCompletionStageResult"),
    "ModelCompletionStageSettlement": ("cayu.sessions.base", "ModelCompletionStageSettlement"),
    "ModelCompletionStageSettlementRequest": (
        "cayu.sessions.base",
        "ModelCompletionStageSettlementRequest",
    ),
    "ModelFailoverPolicy": ("cayu.sessions.base", "ModelFailoverPolicy"),
    "ModelTarget": ("cayu.sessions.base", "ModelTarget"),
    "PendingActionIssue": ("cayu.sessions.pending_action_contracts", "PendingActionIssue"),
    "PendingActionIssueCode": ("cayu.sessions.pending_action_contracts", "PendingActionIssueCode"),
    "PendingActionKind": ("cayu.sessions.records", "PendingActionKind"),
    "PendingActionListResult": (
        "cayu.sessions.pending_action_contracts",
        "PendingActionListResult",
    ),
    "PendingActionQuery": ("cayu.sessions.pending_action_contracts", "PendingActionQuery"),
    "PendingActionRecord": ("cayu.sessions.pending_action_contracts", "PendingActionRecord"),
    "PendingActionResultTooLarge": (
        "cayu.sessions.pending_action_contracts",
        "PendingActionResultTooLarge",
    ),
    "PendingActionSession": ("cayu.sessions.records", "PendingActionSession"),
    "PersistedEventSideEffectClaim": (
        "cayu.sessions.event_delivery",
        "PersistedEventSideEffectClaim",
    ),
    "PersistedEventSideEffectClaimLost": (
        "cayu.sessions.event_delivery",
        "PersistedEventSideEffectClaimLost",
    ),
    "PersistedEventSideEffectDelivery": (
        "cayu.sessions.event_delivery",
        "PersistedEventSideEffectDelivery",
    ),
    "PersistedEventSideEffectStatus": (
        "cayu.sessions.event_delivery",
        "PersistedEventSideEffectStatus",
    ),
    "ProfiledSessionForkResult": ("cayu.sessions.base", "ProfiledSessionForkResult"),
    "PromptAnatomyTransitionReceipt": ("cayu.sessions.base", "PromptAnatomyTransitionReceipt"),
    "RECOVERY_CLEANUP_MAX_TIMEOUT_SECONDS": (
        "cayu.sessions.cleanup",
        "RECOVERY_CLEANUP_MAX_TIMEOUT_SECONDS",
    ),
    "RECOVERY_PLAN_MAX_CONCURRENCY": ("cayu.sessions.recovery", "RECOVERY_PLAN_MAX_CONCURRENCY"),
    "RECOVERY_PLAN_MAX_INSPECTIONS": ("cayu.sessions.recovery", "RECOVERY_PLAN_MAX_INSPECTIONS"),
    "RECOVERY_PLAN_MAX_ITEMS": ("cayu.sessions.recovery", "RECOVERY_PLAN_MAX_ITEMS"),
    "RECOVERY_PLAN_SCHEMA_VERSION": ("cayu.sessions.recovery", "RECOVERY_PLAN_SCHEMA_VERSION"),
    "RUNTIME_BUILD_PROVENANCE_METADATA_KEY": (
        "cayu.sessions.records",
        "RUNTIME_BUILD_PROVENANCE_METADATA_KEY",
    ),
    "RecoveryBlockerCode": ("cayu.sessions.recovery", "RecoveryBlockerCode"),
    "RecoveryClaimEvidence": ("cayu.sessions.recovery", "RecoveryClaimEvidence"),
    "RecoveryCleanupCapacityExceeded": ("cayu.sessions.cleanup", "RecoveryCleanupCapacityExceeded"),
    "RecoveryCleanupDeadlineEvidence": ("cayu.sessions.cleanup", "RecoveryCleanupDeadlineEvidence"),
    "RecoveryCleanupDeadlineExceeded": ("cayu.sessions.cleanup", "RecoveryCleanupDeadlineExceeded"),
    "RecoveryCleanupDeadlineScope": ("cayu.sessions.cleanup", "RecoveryCleanupDeadlineScope"),
    "RecoveryCleanupPolicy": ("cayu.sessions.cleanup", "RecoveryCleanupPolicy"),
    "RecoveryCleanupRetainedTaskSnapshot": (
        "cayu.sessions.cleanup",
        "RecoveryCleanupRetainedTaskSnapshot",
    ),
    "RecoveryCleanupOwner": ("cayu.sessions.cleanup", "RecoveryCleanupOwner"),
    "RecoveryCleanupTaskSnapshot": ("cayu.sessions.cleanup", "RecoveryCleanupTaskSnapshot"),
    "RecoveryCleanupSessionSnapshot": ("cayu.sessions.cleanup", "RecoveryCleanupSessionSnapshot"),
    "RecoveryCleanupSupervisorSnapshot": (
        "cayu.sessions.cleanup",
        "RecoveryCleanupSupervisorSnapshot",
    ),
    "RecoveryDecision": ("cayu.sessions.recovery", "RecoveryDecision"),
    "RecoveryEnvironmentEvidence": ("cayu.sessions.recovery", "RecoveryEnvironmentEvidence"),
    "RecoveryExecutionRequest": ("cayu.sessions.recovery", "RecoveryExecutionRequest"),
    "RecoveryInterruptionCascadeEvidence": (
        "cayu.sessions.recovery",
        "RecoveryInterruptionCascadeEvidence",
    ),
    "RecoveryItemExecutionStatus": ("cayu.sessions.recovery", "RecoveryItemExecutionStatus"),
    "RecoveryItemReceipt": ("cayu.sessions.recovery", "RecoveryItemReceipt"),
    "RecoveryModelStageEvidence": ("cayu.sessions.recovery", "RecoveryModelStageEvidence"),
    "RecoveryPendingActionEvidence": ("cayu.sessions.recovery", "RecoveryPendingActionEvidence"),
    "RecoveryPlan": ("cayu.sessions.recovery", "RecoveryPlan"),
    "RecoveryPlanAction": ("cayu.sessions.recovery", "RecoveryPlanAction"),
    "RecoveryPlanBlocker": ("cayu.sessions.recovery", "RecoveryPlanBlocker"),
    "RecoveryPlanBounds": ("cayu.sessions.recovery", "RecoveryPlanBounds"),
    "RecoveryPlanExecutionEvidence": ("cayu.sessions.recovery", "RecoveryPlanExecutionEvidence"),
    "RecoveryPlanExecutionFenced": ("cayu.sessions.recovery", "RecoveryPlanExecutionFenced"),
    "RecoveryPlanItem": ("cayu.sessions.recovery", "RecoveryPlanItem"),
    "ProducerRecoveryExpectation": ("cayu.sessions.recovery", "ProducerRecoveryExpectation"),
    "ContinuationRecoveryExpectation": (
        "cayu.sessions.recovery",
        "ContinuationRecoveryExpectation",
    ),
    "RecoveryPlanRequest": ("cayu.sessions.recovery", "RecoveryPlanRequest"),
    "RecoveryPlanSelection": ("cayu.sessions.recovery", "RecoveryPlanSelection"),
    "RecoveryReceipt": ("cayu.sessions.recovery", "RecoveryReceipt"),
    "RecoveryRegistrationEvidence": ("cayu.sessions.recovery", "RecoveryRegistrationEvidence"),
    "RecoveryRegistrationStatus": ("cayu.sessions.recovery", "RecoveryRegistrationStatus"),
    "RecoveryTaskClaimEvidence": ("cayu.sessions.recovery", "RecoveryTaskClaimEvidence"),
    "ResumeRequest": ("cayu.sessions.base", "ResumeRequest"),
    "RunOutcome": ("cayu.sessions.outcomes", "RunOutcome"),
    "RunRequest": ("cayu.sessions.base", "RunRequest"),
    "RunnerObservedEventIdentity": ("cayu.sessions.records", "RunnerObservedEventIdentity"),
    "RuntimePublicationCheckpointOperation": (
        "cayu.sessions.base",
        "RuntimePublicationCheckpointOperation",
    ),
    "RuntimePublicationEventReference": ("cayu.sessions.base", "RuntimePublicationEventReference"),
    "RuntimePublicationMutation": ("cayu.sessions.base", "RuntimePublicationMutation"),
    "RuntimePublicationOperationRecordMutation": (
        "cayu.sessions.base",
        "RuntimePublicationOperationRecordMutation",
    ),
    "RuntimePublicationReceipt": ("cayu.sessions.base", "RuntimePublicationReceipt"),
    "RuntimePublicationRequest": ("cayu.sessions.base", "RuntimePublicationRequest"),
    "RuntimePublicationResult": ("cayu.sessions.base", "RuntimePublicationResult"),
    "SESSION_RUNTIME_METADATA_KEYS": ("cayu.sessions.base", "SESSION_RUNTIME_METADATA_KEYS"),
    "SESSION_RUNTIME_METADATA_PREFIX": ("cayu.sessions.base", "SESSION_RUNTIME_METADATA_PREFIX"),
    "SerializedRecordSummary": ("cayu.sessions.inspection", "SerializedRecordSummary"),
    "Session": ("cayu.sessions.records", "Session"),
    "SessionAggregateFilter": ("cayu.sessions.queries", "SessionAggregateFilter"),
    "SessionBudgetInspection": ("cayu.sessions.base", "SessionBudgetInspection"),
    "SessionDebugState": ("cayu.sessions.queries", "SessionDebugState"),
    "SessionExecutionSource": ("cayu.sessions.invocation", "SessionExecutionSource"),
    "SessionExportBoundary": ("cayu.sessions.exports", "SessionExportBoundary"),
    "SessionExportLimits": ("cayu.sessions.exports", "SessionExportLimits"),
    "SessionExportSnapshot": ("cayu.sessions.exports", "SessionExportSnapshot"),
    "SessionExportTooLarge": ("cayu.sessions.exports", "SessionExportTooLarge"),
    "SessionForkProfileRelationship": ("cayu.sessions.base", "SessionForkProfileRelationship"),
    "SessionIdentity": ("cayu.sessions.base", "SessionIdentity"),
    "SessionInspectionIdentity": ("cayu.sessions.inspection", "SessionInspectionIdentity"),
    "SessionInspectionSummary": ("cayu.sessions.inspection", "SessionInspectionSummary"),
    "SessionInspectionUsageSummary": ("cayu.sessions.inspection", "SessionInspectionUsageSummary"),
    "SessionInvocation": ("cayu.sessions.invocation", "SessionInvocation"),
    "SessionInvocationAdmission": ("cayu.sessions.base", "SessionInvocationAdmission"),
    "SessionInvocationBinding": ("cayu.sessions.invocation", "SessionInvocationBinding"),
    "SessionInvocationSnapshot": ("cayu.sessions.base", "SessionInvocationSnapshot"),
    "SessionLineageNode": ("cayu.sessions.lineage", "SessionLineageNode"),
    "SessionLineageOrigin": ("cayu.sessions.lineage", "SessionLineageOrigin"),
    "SessionLineageQuery": ("cayu.sessions.lineage", "SessionLineageQuery"),
    "SessionLineageResult": ("cayu.sessions.lineage", "SessionLineageResult"),
    "SessionListResult": ("cayu.sessions.queries", "SessionListResult"),
    "SessionMessageDeliveryBatch": ("cayu.sessions.messaging", "SessionMessageDeliveryBatch"),
    "SessionMessageDeliveryMode": ("cayu.sessions.messaging", "SessionMessageDeliveryMode"),
    "SessionMessageQueueStatus": ("cayu.sessions.base", "SessionMessageQueueStatus"),
    "SessionModelCompletionStageConflict": (
        "cayu.sessions.base",
        "SessionModelCompletionStageConflict",
    ),
    "SessionModelCompletionStageIncomplete": (
        "cayu.sessions.base",
        "SessionModelCompletionStageIncomplete",
    ),
    "SessionModelTransition": ("cayu.sessions.base", "SessionModelTransition"),
    "SessionOperationInitializer": ("cayu.sessions.base", "SessionOperationInitializer"),
    "SessionOperationPublication": ("cayu.sessions.base", "SessionOperationPublication"),
    "SessionOperationTransform": ("cayu.sessions.base", "SessionOperationTransform"),
    "SessionOperationalSnapshot": ("cayu.sessions.summaries", "SessionOperationalSnapshot"),
    "SessionOrder": ("cayu.sessions.queries", "SessionOrder"),
    "SessionOutcome": ("cayu.sessions.summaries", "SessionOutcome"),
    "SessionQuery": ("cayu.sessions.queries", "SessionQuery"),
    "SessionQueuedMessage": ("cayu.sessions.messaging", "SessionQueuedMessage"),
    "SessionQueuedMessagesPending": ("cayu.sessions.messaging", "SessionQueuedMessagesPending"),
    "SessionRunFenced": ("cayu.sessions.base", "SessionRunFenced"),
    "SessionRuntimePublicationConflict": (
        "cayu.sessions.base",
        "SessionRuntimePublicationConflict",
    ),
    "SessionExecutionConfig": ("cayu.sessions.execution", "SessionExecutionConfig"),
    "SessionExecutionState": ("cayu.sessions.execution", "SessionExecutionState"),
    "SessionStateSnapshot": ("cayu.sessions.base", "SessionStateSnapshot"),
    "SessionStatus": ("cayu.sessions.records", "SessionStatus"),
    "SessionExecutionInProgress": ("cayu.sessions.base", "SessionExecutionInProgress"),
    "SessionStatusConflict": ("cayu.sessions.base", "SessionStatusConflict"),
    "SessionStatusCounts": ("cayu.sessions.queries", "SessionStatusCounts"),
    "SessionStore": ("cayu.sessions.base", "SessionStore"),
    "SessionTopologyBranch": ("cayu.sessions.topology", "SessionTopologyBranch"),
    "SessionTopologyCycle": ("cayu.sessions.topology", "SessionTopologyCycle"),
    "SessionTopologyDepthExceeded": ("cayu.sessions.topology", "SessionTopologyDepthExceeded"),
    "SessionTopologyNode": ("cayu.sessions.topology", "SessionTopologyNode"),
    "SessionTopologyQuery": ("cayu.sessions.topology", "SessionTopologyQuery"),
    "SessionTopologyStoreResult": ("cayu.sessions.topology", "SessionTopologyStoreResult"),
    "StartupRecoveryBlockedSession": ("cayu.sessions.recovery", "StartupRecoveryBlockedSession"),
    "StartupRecoveryResult": ("cayu.sessions.recovery", "StartupRecoveryResult"),
    "StaleRecoveryPlanError": ("cayu.sessions.recovery", "StaleRecoveryPlanError"),
    "StoreTimeCheckpointTransform": ("cayu.sessions.base", "StoreTimeCheckpointTransform"),
    "StoreTimeSessionOperationTransform": (
        "cayu.sessions.base",
        "StoreTimeSessionOperationTransform",
    ),
    "StructuredOutputResult": ("cayu.sessions.outcomes", "StructuredOutputResult"),
    "TERMINAL_SESSION_EVIDENCE_DEFAULT_MAX_EVENTS": (
        "cayu.sessions.terminal_evidence",
        "TERMINAL_SESSION_EVIDENCE_DEFAULT_MAX_EVENTS",
    ),
    "TERMINAL_SESSION_EVIDENCE_DEFAULT_MAX_RECORD_BYTES": (
        "cayu.sessions.terminal_evidence",
        "TERMINAL_SESSION_EVIDENCE_DEFAULT_MAX_RECORD_BYTES",
    ),
    "TERMINAL_SESSION_EVIDENCE_DEFAULT_MAX_TOTAL_BYTES": (
        "cayu.sessions.terminal_evidence",
        "TERMINAL_SESSION_EVIDENCE_DEFAULT_MAX_TOTAL_BYTES",
    ),
    "TERMINAL_SESSION_EVIDENCE_DEFAULT_MAX_TRANSCRIPT_RECORDS": (
        "cayu.sessions.terminal_evidence",
        "TERMINAL_SESSION_EVIDENCE_DEFAULT_MAX_TRANSCRIPT_RECORDS",
    ),
    "TERMINAL_SESSION_EVIDENCE_HARD_MAX_EVENTS": (
        "cayu.sessions.terminal_evidence",
        "TERMINAL_SESSION_EVIDENCE_HARD_MAX_EVENTS",
    ),
    "TERMINAL_SESSION_EVIDENCE_HARD_MAX_RECORD_BYTES": (
        "cayu.sessions.terminal_evidence",
        "TERMINAL_SESSION_EVIDENCE_HARD_MAX_RECORD_BYTES",
    ),
    "TERMINAL_SESSION_EVIDENCE_HARD_MAX_TOTAL_BYTES": (
        "cayu.sessions.terminal_evidence",
        "TERMINAL_SESSION_EVIDENCE_HARD_MAX_TOTAL_BYTES",
    ),
    "TERMINAL_SESSION_EVIDENCE_HARD_MAX_TRANSCRIPT_RECORDS": (
        "cayu.sessions.terminal_evidence",
        "TERMINAL_SESSION_EVIDENCE_HARD_MAX_TRANSCRIPT_RECORDS",
    ),
    "TaskExecutionSource": ("cayu.sessions.invocation", "TaskExecutionSource"),
    "TaskInvocation": ("cayu.sessions.invocation", "TaskInvocation"),
    "TerminalPublicationMarker": ("cayu.sessions.terminal_evidence", "TerminalPublicationMarker"),
    "TerminalSessionEvidence": ("cayu.sessions.terminal_evidence", "TerminalSessionEvidence"),
    "TerminalSessionEvidenceBoundary": (
        "cayu.sessions.terminal_evidence",
        "TerminalSessionEvidenceBoundary",
    ),
    "TerminalSessionEvidenceError": (
        "cayu.sessions.terminal_evidence",
        "TerminalSessionEvidenceError",
    ),
    "TerminalSessionEvidenceErrorCode": (
        "cayu.sessions.terminal_evidence",
        "TerminalSessionEvidenceErrorCode",
    ),
    "TerminalSessionEvidenceLimits": (
        "cayu.sessions.terminal_evidence",
        "TerminalSessionEvidenceLimits",
    ),
    "TranscriptPage": ("cayu.sessions.transcript_queries", "TranscriptPage"),
    "TranscriptQuery": ("cayu.sessions.transcript_queries", "TranscriptQuery"),
    "TranscriptRecord": ("cayu.sessions.records", "TranscriptRecord"),
    "TranscriptSearchHit": ("cayu.sessions.transcript_queries", "TranscriptSearchHit"),
    "TranscriptSearchQuery": ("cayu.sessions.transcript_queries", "TranscriptSearchQuery"),
    "TranscriptSearchResult": ("cayu.sessions.transcript_queries", "TranscriptSearchResult"),
    "TranscriptSnapshot": ("cayu.sessions.transcript_queries", "TranscriptSnapshot"),
    "UsageRollupQuery": ("cayu.sessions.usage", "UsageRollupQuery"),
    "checkpoint_root_field_projection_from_storage": (
        "cayu.sessions.base",
        "checkpoint_root_field_projection_from_storage",
    ),
    "copy_recovery_cleanup_policy": ("cayu.sessions.cleanup", "copy_recovery_cleanup_policy"),
    "copy_session_user_metadata": ("cayu.sessions.base", "copy_session_user_metadata"),
    "is_runtime_owned_session_metadata_key": (
        "cayu.sessions.base",
        "is_runtime_owned_session_metadata_key",
    ),
    "project_terminal_child_session_result": (
        "cayu.sessions.child_results",
        "project_terminal_child_session_result",
    ),
    "replace_session_user_metadata": ("cayu.sessions.base", "replace_session_user_metadata"),
    "run_to_completion": ("cayu.sessions.outcomes", "run_to_completion"),
    "runtime_publication_checkpoint_mutation": (
        "cayu.sessions.base",
        "runtime_publication_checkpoint_mutation",
    ),
    "runtime_publication_checkpoint_value_digest": (
        "cayu.sessions.base",
        "runtime_publication_checkpoint_value_digest",
    ),
    "runtime_publication_event_reference": (
        "cayu.sessions.base",
        "runtime_publication_event_reference",
    ),
    "runtime_publication_operation_record_value_digest": (
        "cayu.sessions.base",
        "runtime_publication_operation_record_value_digest",
    ),
    "session_fork_profile_relationship": (
        "cayu.sessions.base",
        "session_fork_profile_relationship",
    ),
    "session_invocation_for_run_request": (
        "cayu.sessions.base",
        "session_invocation_for_run_request",
    ),
    "session_invocation_from_task": ("cayu.sessions.invocation", "session_invocation_from_task"),
    "session_prompt_anatomy_transition": (
        "cayu.sessions.base",
        "session_prompt_anatomy_transition",
    ),
    "system_prompt_messages_sha256": ("cayu.sessions.base", "system_prompt_messages_sha256"),
}

PUBLIC_NAMES = [
    "ActiveModelCompletionStage",
    "CONTEXT_VIEW_CONTRACT_VERSION",
    "CONTEXT_VIEW_STORE_VERSION",
    "CHECKPOINT_SCHEMA_VERSION_KEY",
    "CHILD_SESSION_CONTEXT_PROJECTION_VERSION",
    "CHILD_SESSION_PUBLIC_ALIAS_MAX_CHARS",
    "CHILD_SESSION_PUBLIC_OCCURRENCE_ID_MAX_CHARS",
    "CHILD_SESSION_RESULT_PROJECTION_VERSION",
    "CHILD_SESSION_RESULT_REFERENCE_VERSION",
    "CURRENT_CHECKPOINT_SCHEMA_VERSION",
    "CheckpointCompatibilityError",
    "CheckpointRootFieldGuard",
    "CheckpointRootFieldProjection",
    "CheckpointTransform",
    "ChildSessionContextContribution",
    "ChildSessionContextContributor",
    "ChildSessionContextCoverage",
    "ChildSessionContextCoverageState",
    "ChildSessionContextEntry",
    "ChildSessionContextOccurrence",
    "ChildSessionContextProjection",
    "ChildSessionContextTruncationReason",
    "ChildSessionResultProjection",
    "ChildSessionResultReference",
    "ChildSessionResultUnavailable",
    "CompactSessionRequest",
    "ContextViewExtensionRecord",
    "ContextViewExtensionRegistration",
    "ContextViewProjectionSource",
    "ContextViewExtensionProjection",
    "ContextViewLimits",
    "ContextViewLifecycleEvent",
    "ContextViewManifest",
    "ContextViewOwnershipRequest",
    "ContextViewPublicationRequest",
    "ContextViewReadback",
    "ContextViewSelectionReceipt",
    "ContextViewSelectionRequest",
    "DEFAULT_CHILD_SESSION_RESULT_MAX_CHARS",
    "DEFAULT_PENDING_ACTION_RESULT_MAX_BYTES",
    "DEFAULT_RECOVERY_CLEANUP_MAX_SUPERVISED_TASKS",
    "DEFAULT_RECOVERY_CLEANUP_OVERALL_TIMEOUT_SECONDS",
    "DEFAULT_RECOVERY_CLEANUP_STEP_TIMEOUT_SECONDS",
    "DeferredInteractionInput",
    "DelegatedActionReference",
    "EnqueueSessionMessageRequest",
    "EnqueueSessionMessageResult",
    "EventOrder",
    "EventQuery",
    "EventQueryResultTooLarge",
    "EventRecord",
    "EventSummary",
    "ForkExecutionProfileDecisionRecord",
    "ForkExecutionProfileSelection",
    "ForkExecutionProfileSource",
    "ForkSessionRequest",
    "ForkSourceSnapshot",
    "ForkSystemPromptPolicy",
    "ForkSystemPromptReplacement",
    "INITIAL_TRANSCRIPT_PENDING_CHECKPOINT_KEY",
    "InMemorySessionStore",
    "IncompleteSessionRecoveryAction",
    "IncompleteSessionRecoveryRequest",
    "IncompleteSessionRecoveryResult",
    "IncompleteSessionsRecoveryPage",
    "IncompleteSessionsRecoveryRequest",
    "InteractionStatus",
    "InteractionSummaryEvidence",
    "InteractionTransitionReceiptResult",
    "InteractionTransitionResult",
    "InteractionTransitionSpec",
    "InterruptSessionRequest",
    "InvocationOrigin",
    "InvocationOriginClaim",
    "InvocationOriginTrust",
    "LabelSelectorOperator",
    "LabelSelectorRequirement",
    "MAX_CHILD_SESSION_RESULT_MAX_CHARS",
    "MAX_INCOMPLETE_SESSIONS_RECOVERY_CURSOR_BYTES",
    "MAX_PENDING_ACTION_RESULT_BYTES",
    "MAX_SESSION_ID_BYTES",
    "MAX_SESSION_LIST_CURSOR_BYTES",
    "MIN_SUPPORTED_CHECKPOINT_SCHEMA_VERSION",
    "McpManifestBaseline",
    "McpManifestBaselineLoadResult",
    "McpManifestHistoryConflict",
    "McpManifestPublicationResult",
    "ModelCompletionManualRecoveryRequest",
    "ModelCompletionManualRecoveryResult",
    "ModelCompletionStage",
    "ModelCompletionStageAbandonment",
    "ModelCompletionStageAbandonmentResult",
    "ModelCompletionStageDispatch",
    "ModelCompletionStageDisposition",
    "ModelCompletionStageRequest",
    "ModelCompletionStageResult",
    "ModelCompletionStageSettlement",
    "ModelCompletionStageSettlementRequest",
    "ModelFailoverPolicy",
    "ModelTarget",
    "PendingActionIssue",
    "PendingActionIssueCode",
    "PendingActionKind",
    "PendingActionListResult",
    "PendingActionQuery",
    "PendingActionRecord",
    "PendingActionResultTooLarge",
    "ParticipantSessionBinding",
    "ParticipantSessionCreationReceipt",
    "ParticipantSessionCreationRequest",
    "RecipientSessionCreationRequest",
    "RecipientSessionCreationReceipt",
    "PendingActionSession",
    "PersistedEventSideEffectClaim",
    "PersistedEventSideEffectClaimLost",
    "PersistedEventSideEffectDelivery",
    "PersistedEventSideEffectStatus",
    "ProfiledSessionForkResult",
    "PromptAnatomyTransitionReceipt",
    "RECOVERY_CLEANUP_MAX_TIMEOUT_SECONDS",
    "RECOVERY_PLAN_MAX_CONCURRENCY",
    "RECOVERY_PLAN_MAX_INSPECTIONS",
    "RECOVERY_PLAN_MAX_ITEMS",
    "RECOVERY_PLAN_SCHEMA_VERSION",
    "RUNTIME_BUILD_PROVENANCE_METADATA_KEY",
    "RecoveryBlockerCode",
    "RecoveryClaimEvidence",
    "RecoveryCleanupCapacityExceeded",
    "RecoveryCleanupDeadlineEvidence",
    "RecoveryCleanupDeadlineExceeded",
    "RecoveryCleanupDeadlineScope",
    "RecoveryCleanupPolicy",
    "RecoveryCleanupRetainedTaskSnapshot",
    "RecoveryCleanupOwner",
    "RecoveryCleanupTaskSnapshot",
    "RecoveryCleanupSessionSnapshot",
    "RecoveryCleanupSupervisorSnapshot",
    "RecoveryDecision",
    "RecoveryEnvironmentEvidence",
    "RecoveryExecutionRequest",
    "RecoveryInterruptionCascadeEvidence",
    "RecoveryItemExecutionStatus",
    "RecoveryItemReceipt",
    "RecoveryModelStageEvidence",
    "RecoveryPendingActionEvidence",
    "RecoveryPlan",
    "RecoveryPlanAction",
    "RecoveryPlanBlocker",
    "RecoveryPlanBounds",
    "RecoveryPlanExecutionEvidence",
    "RecoveryPlanExecutionFenced",
    "RecoveryPlanItem",
    "ProducerRecoveryExpectation",
    "ContinuationRecoveryExpectation",
    "RecoveryPlanRequest",
    "RecoveryPlanSelection",
    "RecoveryReceipt",
    "RecoveryRegistrationEvidence",
    "RecoveryRegistrationStatus",
    "RecoveryTaskClaimEvidence",
    "ResumeRequest",
    "RunOutcome",
    "RunRequest",
    "RunnerObservedEventIdentity",
    "RuntimePublicationCheckpointOperation",
    "RuntimePublicationEventReference",
    "RuntimePublicationMutation",
    "RuntimePublicationOperationRecordMutation",
    "RuntimePublicationReceipt",
    "RuntimePublicationRequest",
    "RuntimePublicationResult",
    "SESSION_RUNTIME_METADATA_KEYS",
    "SESSION_RUNTIME_METADATA_PREFIX",
    "SerializedRecordSummary",
    "Session",
    "SessionAggregateFilter",
    "SessionBudgetInspection",
    "SessionDebugState",
    "SessionExecutionSource",
    "SessionExportBoundary",
    "SessionExportLimits",
    "SessionExportSnapshot",
    "SessionExportTooLarge",
    "SessionForkProfileRelationship",
    "SessionIdentity",
    "SessionInspectionIdentity",
    "SessionInspectionSummary",
    "SessionInspectionUsageSummary",
    "SessionInvocation",
    "SessionInvocationAdmission",
    "SessionInvocationBinding",
    "SessionInvocationSnapshot",
    "SessionLineageNode",
    "SessionLineageOrigin",
    "SessionLineageQuery",
    "SessionLineageResult",
    "SessionListResult",
    "SessionMessageDeliveryBatch",
    "SessionMessageDeliveryMode",
    "SessionMessageQueueStatus",
    "SessionModelCompletionStageConflict",
    "SessionModelCompletionStageIncomplete",
    "SessionModelTransition",
    "SessionOperationInitializer",
    "SessionOperationPublication",
    "SessionOperationTransform",
    "SessionOperationalSnapshot",
    "SessionOrder",
    "SessionOutcome",
    "SessionQuery",
    "SessionQueuedMessage",
    "SessionQueuedMessagesPending",
    "SessionRunFenced",
    "SessionRuntimePublicationConflict",
    "SessionExecutionConfig",
    "SessionExecutionState",
    "SessionStateSnapshot",
    "SessionStatus",
    "SessionExecutionInProgress",
    "SessionStatusConflict",
    "SessionStatusCounts",
    "SessionStore",
    "SessionTopologyBranch",
    "SessionTopologyCycle",
    "SessionTopologyDepthExceeded",
    "SessionTopologyNode",
    "SessionTopologyQuery",
    "SessionTopologyStoreResult",
    "StartupRecoveryBlockedSession",
    "StartupRecoveryResult",
    "StaleRecoveryPlanError",
    "StoreTimeCheckpointTransform",
    "StoreTimeSessionOperationTransform",
    "StructuredOutputResult",
    "TERMINAL_SESSION_EVIDENCE_DEFAULT_MAX_EVENTS",
    "TERMINAL_SESSION_EVIDENCE_DEFAULT_MAX_RECORD_BYTES",
    "TERMINAL_SESSION_EVIDENCE_DEFAULT_MAX_TOTAL_BYTES",
    "TERMINAL_SESSION_EVIDENCE_DEFAULT_MAX_TRANSCRIPT_RECORDS",
    "TERMINAL_SESSION_EVIDENCE_HARD_MAX_EVENTS",
    "TERMINAL_SESSION_EVIDENCE_HARD_MAX_RECORD_BYTES",
    "TERMINAL_SESSION_EVIDENCE_HARD_MAX_TOTAL_BYTES",
    "TERMINAL_SESSION_EVIDENCE_HARD_MAX_TRANSCRIPT_RECORDS",
    "TaskExecutionSource",
    "TaskInvocation",
    "TerminalPublicationMarker",
    "TerminalSessionEvidence",
    "TerminalSessionEvidenceBoundary",
    "TerminalSessionEvidenceError",
    "TerminalSessionEvidenceErrorCode",
    "TerminalSessionEvidenceLimits",
    "TranscriptPage",
    "TranscriptQuery",
    "TranscriptRecord",
    "TranscriptSearchHit",
    "TranscriptSearchQuery",
    "TranscriptSearchResult",
    "TranscriptSnapshot",
    "UsageRollupQuery",
    "checkpoint_root_field_projection_from_storage",
    "copy_recovery_cleanup_policy",
    "copy_session_user_metadata",
    "is_runtime_owned_session_metadata_key",
    "project_terminal_child_session_result",
    "replace_session_user_metadata",
    "run_to_completion",
    "runtime_publication_checkpoint_mutation",
    "runtime_publication_checkpoint_value_digest",
    "runtime_publication_event_reference",
    "runtime_publication_operation_record_value_digest",
    "session_fork_profile_relationship",
    "session_invocation_for_run_request",
    "session_invocation_from_task",
    "session_prompt_anatomy_transition",
    "system_prompt_messages_sha256",
]
