"""Explicit public exports; implementations load on first access."""

EXPORTS: dict[str, tuple[str, str]] = {
    "DEFAULT_HTTP_MCP_CONNECT_TIMEOUT_S": ("cayu.mcp.http", "DEFAULT_HTTP_MCP_CONNECT_TIMEOUT_S"),
    "DEFAULT_HTTP_MCP_TIMEOUT_S": ("cayu.mcp.http", "DEFAULT_HTTP_MCP_TIMEOUT_S"),
    "DEFAULT_MCP_CANCELLATION_NOTIFICATION_TIMEOUT_S": (
        "cayu.mcp.stdio",
        "DEFAULT_MCP_CANCELLATION_NOTIFICATION_TIMEOUT_S",
    ),
    "DEFAULT_MCP_CLIENT_NAME": ("cayu.mcp._jsonrpc", "DEFAULT_MCP_CLIENT_NAME"),
    "DEFAULT_MCP_CLIENT_VERSION": ("cayu.mcp._jsonrpc", "DEFAULT_MCP_CLIENT_VERSION"),
    "DEFAULT_MCP_CONTAINMENT_KILL_TIMEOUT_S": (
        "cayu.mcp._stdio_process",
        "DEFAULT_MCP_CONTAINMENT_KILL_TIMEOUT_S",
    ),
    "DEFAULT_MCP_CONTAINMENT_STARTUP_TIMEOUT_S": (
        "cayu.mcp._stdio_process",
        "DEFAULT_MCP_CONTAINMENT_STARTUP_TIMEOUT_S",
    ),
    "DEFAULT_MCP_CONTAINMENT_TERM_TIMEOUT_S": (
        "cayu.mcp._stdio_process",
        "DEFAULT_MCP_CONTAINMENT_TERM_TIMEOUT_S",
    ),
    "DEFAULT_MCP_GRACEFUL_SHUTDOWN_TIMEOUT_S": (
        "cayu.mcp.stdio",
        "DEFAULT_MCP_GRACEFUL_SHUTDOWN_TIMEOUT_S",
    ),
    "DEFAULT_MCP_MAX_LIST_ITEMS": ("cayu.mcp._jsonrpc", "DEFAULT_MCP_MAX_LIST_ITEMS"),
    "DEFAULT_MCP_MAX_LIST_PAGES": ("cayu.mcp._jsonrpc", "DEFAULT_MCP_MAX_LIST_PAGES"),
    "DEFAULT_MCP_MAX_MESSAGE_BYTES": ("cayu.mcp._transport", "DEFAULT_MCP_MAX_MESSAGE_BYTES"),
    "DEFAULT_MCP_MAX_RESPONSE_BYTES": ("cayu.mcp._transport", "DEFAULT_MCP_MAX_RESPONSE_BYTES"),
    "DEFAULT_MCP_REQUEST_TIMEOUT_S": ("cayu.mcp._jsonrpc", "DEFAULT_MCP_REQUEST_TIMEOUT_S"),
    "DEFAULT_MCP_WRITE_TIMEOUT_S": ("cayu.mcp.stdio", "DEFAULT_MCP_WRITE_TIMEOUT_S"),
    "HttpMcpClient": ("cayu.mcp.http", "HttpMcpClient"),
    "HttpMcpSession": ("cayu.mcp.http", "HttpMcpSession"),
    "MCP_MODERN_PROTOCOL_VERSION": ("cayu.mcp._jsonrpc", "MCP_MODERN_PROTOCOL_VERSION"),
    "MCP_PROTOCOL_VERSION": ("cayu.mcp._jsonrpc", "MCP_PROTOCOL_VERSION"),
    "McpCallDeadlineExceededError": ("cayu.mcp._transport", "McpCallDeadlineExceededError"),
    "McpClient": ("cayu.mcp.base", "McpClient"),
    "McpIdleTimeoutError": ("cayu.mcp._transport", "McpIdleTimeoutError"),
    "McpInitializeResult": ("cayu.mcp.base", "McpInitializeResult"),
    "McpMessageTooLargeError": ("cayu.mcp._transport", "McpMessageTooLargeError"),
    "McpPeerClosedError": ("cayu.mcp._transport", "McpPeerClosedError"),
    "McpProtocolEra": ("cayu.mcp._protocol", "McpProtocolEra"),
    "McpProtocolError": ("cayu.mcp._jsonrpc", "McpProtocolError"),
    "McpResourceDefinition": ("cayu.mcp.base", "McpResourceDefinition"),
    "McpResourceResult": ("cayu.mcp.base", "McpResourceResult"),
    "McpResponseTooLargeError": ("cayu.mcp._transport", "McpResponseTooLargeError"),
    "McpServerSpec": ("cayu.mcp.base", "McpServerSpec"),
    "McpSession": ("cayu.mcp.base", "McpSession"),
    "McpToolAdapter": ("cayu.mcp.tools", "McpToolAdapter"),
    "McpToolDefinition": ("cayu.mcp.base", "McpToolDefinition"),
    "McpToolResult": ("cayu.mcp.base", "McpToolResult"),
    "McpToolset": ("cayu.mcp.tools", "McpToolset"),
    "McpToolsetManifestDiff": ("cayu.mcp.tools", "McpToolsetManifestDiff"),
    "McpToolsetRefreshBlocked": ("cayu.mcp.tools", "McpToolsetRefreshBlocked"),
    "McpToolsetRefreshResult": ("cayu.mcp.tools", "McpToolsetRefreshResult"),
    "McpToolsetRefreshState": ("cayu.mcp.tools", "McpToolsetRefreshState"),
    "McpToolsetUnavailable": ("cayu.mcp.tools", "McpToolsetUnavailable"),
    "McpTransportLimits": ("cayu.mcp._transport", "McpTransportLimits"),
    "SUPPORTED_MCP_PROTOCOL_VERSIONS": ("cayu.mcp._jsonrpc", "SUPPORTED_MCP_PROTOCOL_VERSIONS"),
    "StdioMcpClient": ("cayu.mcp.stdio", "StdioMcpClient"),
    "StdioMcpProcessLifetime": ("cayu.mcp._stdio_process", "StdioMcpProcessLifetime"),
    "StdioMcpSession": ("cayu.mcp.stdio", "StdioMcpSession"),
    "connect_mcp_toolset": ("cayu.mcp.tools", "connect_mcp_toolset"),
    "mcp_cayu_tool_name": ("cayu.mcp.tools", "mcp_cayu_tool_name"),
    "mcp_tool_manifest_hash": ("cayu.mcp.tools", "mcp_tool_manifest_hash"),
    "mcp_tool_manifest_identity": ("cayu.mcp.tools", "mcp_tool_manifest_identity"),
    "mcp_tool_manifest_server_hash": ("cayu.mcp.tools", "mcp_tool_manifest_server_hash"),
    "mcp_tool_manifest_tools": ("cayu.mcp.tools", "mcp_tool_manifest_tools"),
    "mcp_toolset_manifest_diff": ("cayu.mcp.tools", "mcp_toolset_manifest_diff"),
}

PUBLIC_NAMES = [
    "DEFAULT_HTTP_MCP_CONNECT_TIMEOUT_S",
    "DEFAULT_HTTP_MCP_TIMEOUT_S",
    "DEFAULT_MCP_CANCELLATION_NOTIFICATION_TIMEOUT_S",
    "DEFAULT_MCP_CLIENT_NAME",
    "DEFAULT_MCP_CLIENT_VERSION",
    "DEFAULT_MCP_CONTAINMENT_KILL_TIMEOUT_S",
    "DEFAULT_MCP_CONTAINMENT_STARTUP_TIMEOUT_S",
    "DEFAULT_MCP_CONTAINMENT_TERM_TIMEOUT_S",
    "DEFAULT_MCP_GRACEFUL_SHUTDOWN_TIMEOUT_S",
    "DEFAULT_MCP_MAX_LIST_ITEMS",
    "DEFAULT_MCP_MAX_LIST_PAGES",
    "DEFAULT_MCP_MAX_MESSAGE_BYTES",
    "DEFAULT_MCP_MAX_RESPONSE_BYTES",
    "DEFAULT_MCP_REQUEST_TIMEOUT_S",
    "DEFAULT_MCP_WRITE_TIMEOUT_S",
    "HttpMcpClient",
    "HttpMcpSession",
    "MCP_MODERN_PROTOCOL_VERSION",
    "MCP_PROTOCOL_VERSION",
    "McpCallDeadlineExceededError",
    "McpClient",
    "McpIdleTimeoutError",
    "McpInitializeResult",
    "McpMessageTooLargeError",
    "McpPeerClosedError",
    "McpProtocolEra",
    "McpProtocolError",
    "McpResourceDefinition",
    "McpResourceResult",
    "McpResponseTooLargeError",
    "McpServerSpec",
    "McpSession",
    "McpToolAdapter",
    "McpToolDefinition",
    "McpToolResult",
    "McpToolset",
    "McpToolsetManifestDiff",
    "McpToolsetRefreshBlocked",
    "McpToolsetRefreshResult",
    "McpToolsetRefreshState",
    "McpToolsetUnavailable",
    "McpTransportLimits",
    "SUPPORTED_MCP_PROTOCOL_VERSIONS",
    "StdioMcpClient",
    "StdioMcpProcessLifetime",
    "StdioMcpSession",
    "connect_mcp_toolset",
    "mcp_cayu_tool_name",
    "mcp_tool_manifest_hash",
    "mcp_tool_manifest_identity",
    "mcp_tool_manifest_server_hash",
    "mcp_tool_manifest_tools",
    "mcp_toolset_manifest_diff",
]
