from __future__ import annotations

import json
import re
from collections.abc import Iterable, Mapping, Sequence
from datetime import UTC, date, datetime, timedelta
from decimal import Decimal
from itertools import islice
from math import isfinite
from types import MappingProxyType
from typing import Any, Never, cast

from pydantic import BaseModel, ValidationError

_MAX_LABEL_KEY_LENGTH = 128
_MAX_LABEL_VALUE_LENGTH = 512
_RESERVED_LABEL_PREFIX = "cayu:"

EXECUTION_UNIT_ID_MAX_CHARS = 70
_EXECUTION_UNIT_ID_PATTERNS = {
    "model_step_id": re.compile(r"mstep_[0-9a-f]{32}\Z"),
    "model_attempt_id": re.compile(r"matt_[0-9a-f]{32}\Z"),
    "tool_round_id": re.compile(r"tround_[0-9a-f]{32}\Z"),
    "budget_limit_id": re.compile(r"blim_[0-9a-f]{64}\Z"),
}

MIN_DURABLE_JSON_INTEGER = -(2**63)
MAX_DURABLE_JSON_INTEGER = 2**63 - 1
MAX_DURABLE_JSON_NESTING = 128


def revalidate_model_input(value: Any, *model_types: type[BaseModel]) -> Any:
    """Reconstruct an already-validated model while leaving raw input unchanged.

    Pydantic normally accepts a model instance for a nested field by reference.
    Public snapshot contracts use this helper in ``mode="before"`` validators
    so caller-owned instances are detached and revalidated just like raw
    mappings. Private model attributes are intentionally not preserved; values
    whose runtime provenance is part of their contract need a dedicated copier.
    """

    for model_type in model_types:
        if isinstance(value, model_type):
            return model_type.model_validate(_model_instance_python_input(value))
    return value


def revalidate_model_inputs(
    value: Any,
    *model_types: type[BaseModel],
    maximum: int | None = None,
    field_name: str = "value",
) -> Any:
    """Reconstruct validated models inside one optionally bounded iterable input."""

    if (
        value is None
        or isinstance(value, (str, bytes, bytearray, Mapping, BaseModel))
        or not isinstance(value, Iterable)
    ):
        return value
    if maximum is None:
        items = value
    else:
        if type(maximum) is not int or maximum < 0:
            raise ValueError("maximum must be a non-negative integer.")
        items = tuple(islice(value, maximum + 1))
        if len(items) > maximum:
            raise ValueError(f"{field_name} must contain at most {maximum} values.")
    return tuple(revalidate_model_input(item, *model_types) for item in items)


def _model_instance_python_input(value: BaseModel) -> dict[str, Any]:
    """Dump a model for validation without dropping excluded nested fields."""

    nested_fields: dict[str, Any] = {}
    for field_name, field_info in type(value).model_fields.items():
        field_value = getattr(value, field_name)
        if field_info.exclude or isinstance(field_value, (BaseModel, Mapping, list, tuple)):
            nested_fields[field_name] = field_value
    document = value.model_dump(
        mode="python",
        warnings=False,
        exclude=set(nested_fields),
    )
    for field_name, field_value in nested_fields.items():
        document[field_name] = (
            dict(field_value)
            if isinstance(field_value, Mapping)
            else _nested_model_python_input(field_value)
        )
    return document


def _nested_model_python_input(value: Any) -> Any:
    if isinstance(value, BaseModel):
        return _model_instance_python_input(value)
    if isinstance(value, list):
        return [_nested_model_python_input(item) for item in value]
    if isinstance(value, tuple):
        return tuple(_nested_model_python_input(item) for item in value)
    return value


_MAX_DURABLE_ERROR_FIELD_CHARS = 128
_MAX_DURABLE_ERROR_PATH_CHARS = 512
_DURABLE_ERROR_MESSAGES = {
    "invalid_text_type": "must be a string.",
    "invalid_json_type": "must contain JSON-compatible values.",
    "invalid_json_object": "must be a JSON object.",
    "invalid_json_key": "JSON object keys must be strings.",
    "duplicate_json_key": "must not contain duplicate JSON object keys.",
    "nul_character": "must not contain NUL characters.",
    "unicode_surrogate": "must not contain Unicode surrogate code points.",
    "non_finite_number": "must contain finite JSON numbers.",
    "integer_out_of_range": "must contain signed 64-bit JSON integers.",
    "integral_float_out_of_range": (
        "must not contain integral floating-point values outside the signed 64-bit range."
    ),
    "circular_reference": "must not contain circular references.",
    "nesting_too_deep": (f"must not exceed {MAX_DURABLE_JSON_NESTING} levels of JSON nesting."),
}
_DURABLE_ERROR_PATH_RE = re.compile(
    r"\$(?:/(?:[0-9]+|#[0-9]+)(?:/key)?)*",
    flags=re.ASCII,
)


class DurableValueError(ValueError):
    """A stable, backend-independent portable-value validation failure.

    ``field_name`` is a caller-supplied boundary label and ``path`` is an
    input-value-independent location generated by the validator. Both are
    bounded and reduced to printable ASCII before entering the exception
    message, so malformed data cannot poison logs or durable error records.
    """

    code: str
    field_name: str
    path: str

    def __init__(self, code: str, field_name: str, *, path: str = "$") -> None:
        try:
            detail = _DURABLE_ERROR_MESSAGES[code]
        except KeyError as exc:
            raise ValueError("Unknown durable value error code.") from exc
        self.code = code
        self.field_name = _bounded_ascii_label(
            field_name,
            limit=_MAX_DURABLE_ERROR_FIELD_CHARS,
            fallback="value",
        )
        self.path = _bounded_ascii_label(
            path,
            limit=_MAX_DURABLE_ERROR_PATH_CHARS,
            fallback="$",
        )
        super().__init__(f"`{self.field_name}` {detail} [code={self.code}; path={self.path}]")

    def __reduce__(self):
        return _restore_durable_value_error, (self.code, self.field_name, self.path)


def _restore_durable_value_error(
    code: str,
    field_name: str,
    path: str,
) -> DurableValueError:
    return DurableValueError(code, field_name, path=path)


def extract_durable_value_error(exc: BaseException) -> DurableValueError | None:
    """Return a trusted direct or Pydantic-wrapped durable-value failure.

    The helper reads Pydantic's structured error context without rendering the
    exception or requesting its rejected input. Public subclasses are
    provider-controlled and may override attribute access, so they collapse to
    a fresh runtime-owned fallback without reading any subclass state.
    """

    if type(exc) is DurableValueError:
        return exc
    if _is_durable_value_error_instance(exc):
        return DurableValueError("invalid_json_type", "value")
    if type(exc) is not ValidationError:
        return None
    try:
        errors = exc.errors(
            include_url=False,
            include_context=True,
            include_input=False,
        )
    except BaseException:
        return None
    if type(errors) is not list:
        return None
    for error in errors:
        if type(error) is not dict:
            continue
        context = error.get("ctx")
        if type(context) is not dict:
            continue
        wrapped = context.get("error")
        if type(wrapped) is DurableValueError:
            return wrapped
        if _is_durable_value_error_instance(wrapped):
            return DurableValueError("invalid_json_type", "value")
    return None


def _is_durable_value_error_instance(value: object) -> bool:
    """Check the actual type hierarchy without consulting ``value.__class__``."""

    try:
        hierarchy = type.__getattribute__(type(value), "__mro__")
    except BaseException:
        return False
    return any(base is DurableValueError for base in hierarchy)


def safe_durable_value_error_details(error: DurableValueError) -> tuple[str, str]:
    """Return bounded, trusted details suitable for durable diagnostics.

    ``DurableValueError`` is public and ordinary exception attributes are
    mutable. Runtime boundaries must therefore treat even an extracted error
    as caller-controlled rather than persisting its attributes verbatim.
    Subclasses and malformed base instances collapse to constant diagnostics;
    provider-overridable attribute access is never invoked.
    """

    fallback = ("invalid_json_type", "$")
    if type(error) is not DurableValueError:
        return fallback
    try:
        attributes = object.__getattribute__(error, "__dict__")
        if type(attributes) is not dict:
            return fallback
        code = dict.get(attributes, "code")
        path = dict.get(attributes, "path")
        if type(code) is not str or code not in _DURABLE_ERROR_MESSAGES:
            code = "invalid_json_type"
        if (
            type(path) is not str
            or len(path) > _MAX_DURABLE_ERROR_PATH_CHARS
            or _DURABLE_ERROR_PATH_RE.fullmatch(path) is None
        ):
            path = "$"
        return code, path
    except BaseException:
        return fallback


def parse_durable_json_integer_literal(value: str, field_name: str) -> int:
    """Parse one JSON integer literal within the shared signed-int64 contract.

    ``json.loads`` otherwise delegates arbitrarily large literals to Python's
    bigint parser. Besides accepting values that PostgreSQL JSONB cannot round
    trip through Cayu's durable contract, that can surface interpreter-specific
    digit-limit errors. Compare the short decimal representation before calling
    ``int`` so every ingress boundary rejects the same values deterministically.
    """

    if type(value) is not str:
        raise DurableValueError("invalid_text_type", field_name)
    negative = value.startswith("-")
    digits = value[1:] if negative else value
    limit = str(-MIN_DURABLE_JSON_INTEGER if negative else MAX_DURABLE_JSON_INTEGER)
    if len(digits) > len(limit) or (len(digits) == len(limit) and digits > limit):
        raise DurableValueError("integer_out_of_range", field_name)
    # The JSON decoder guarantees integer syntax. Keep this helper safe for
    # direct callers too, without ever delegating malformed text to ``int``.
    if not digits or not digits.isascii() or not digits.isdecimal():
        raise DurableValueError("invalid_json_type", field_name)
    return int(value)


def reject_nonportable_json_constant(value: str, field_name: str) -> Never:
    """Reject JSON's non-standard NaN/Infinity spellings without echoing one."""

    del value
    raise DurableValueError("non_finite_number", field_name)


def durable_json_object_from_pairs(
    pairs: list[tuple[str, Any]],
    field_name: str,
) -> dict[str, Any]:
    """Build a JSON object while rejecting duplicate or non-portable keys."""

    result: dict[str, Any] = {}
    for key, value in pairs:
        if type(key) is not str:
            raise DurableValueError("invalid_json_key", field_name)
        require_durable_text(key, field_name)
        if key in result:
            # Never echo the caller-controlled key: it can be a secret and JSON
            # duplicate handling otherwise varies between parsers/backends.
            raise DurableValueError("duplicate_json_key", field_name)
        result[key] = value
    return result


def _bounded_ascii_label(value: object, *, limit: int, fallback: str) -> str:
    if type(value) is not str or not value:
        return fallback
    safe = "".join(char if 0x20 <= ord(char) <= 0x7E else "?" for char in value)
    if len(safe) <= limit:
        return safe
    return safe[: limit - 3] + "..."


class FrozenJsonDict(Mapping[str, Any]):
    """An immutable JSON object with mapping-compatible reads."""

    _data: Mapping[str, Any]
    __slots__ = ("_data",)

    def __init__(self, values: Mapping[str, Any] | Iterable[tuple[str, Any]] = ()) -> None:
        object.__setattr__(self, "_data", MappingProxyType(dict(values)))

    def __setattr__(self, name: str, value: Any) -> Never:
        _raise_frozen_json_mutation()

    def __delattr__(self, name: str) -> Never:
        _raise_frozen_json_mutation()

    def __getitem__(self, key: str) -> Any:
        return self._data[key]

    def __iter__(self):
        return iter(self._data)

    def __len__(self) -> int:
        return len(self._data)

    def __repr__(self) -> str:
        return repr(dict(self._data))

    def __delitem__(self, key: str, /) -> None:
        _raise_frozen_json_mutation()

    def __ior__(self, value: Any, /) -> Never:
        _raise_frozen_json_mutation()

    def __setitem__(self, key: str, value: Any, /) -> None:
        _raise_frozen_json_mutation()

    def clear(self) -> None:
        _raise_frozen_json_mutation()

    def pop(self, key: str, default: Any = None, /) -> Any:
        _raise_frozen_json_mutation()

    def popitem(self) -> tuple[str, Any]:
        _raise_frozen_json_mutation()

    def setdefault(self, key: str, default: Any = None, /) -> Any:
        _raise_frozen_json_mutation()

    def update(self, *args: Any, **kwargs: Any) -> None:
        _raise_frozen_json_mutation()

    def __copy__(self) -> FrozenJsonDict:
        return self

    def __deepcopy__(self, memo: dict[int, Any]) -> FrozenJsonDict:
        return self

    def __reduce__(self):
        return type(self), (tuple(self._data.items()),)


class FrozenJsonList(Sequence[Any]):
    """An immutable JSON array with sequence-compatible reads."""

    _items: tuple[Any, ...]
    __slots__ = ("_items",)

    def __init__(self, values: Iterable[Any] = ()) -> None:
        object.__setattr__(self, "_items", tuple(values))

    def __setattr__(self, name: str, value: Any) -> Never:
        _raise_frozen_json_mutation()

    def __delattr__(self, name: str) -> Never:
        _raise_frozen_json_mutation()

    def __getitem__(self, index: int | slice) -> Any:
        value = self._items[index]
        if isinstance(index, slice):
            return type(self)(value)
        return value

    def __len__(self) -> int:
        return len(self._items)

    def __iter__(self):
        return iter(self._items)

    def __repr__(self) -> str:
        return repr(list(self._items))

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, Sequence) or isinstance(other, str | bytes | bytearray):
            return False
        return tuple(self._items) == tuple(other)

    def __delitem__(self, key: Any, /) -> None:
        _raise_frozen_json_mutation()

    def __iadd__(self, value: Any, /) -> Never:
        _raise_frozen_json_mutation()

    def __imul__(self, value: Any, /) -> Never:
        _raise_frozen_json_mutation()

    def __setitem__(self, key: Any, value: Any, /) -> None:
        _raise_frozen_json_mutation()

    def append(self, value: Any, /) -> None:
        _raise_frozen_json_mutation()

    def clear(self) -> None:
        _raise_frozen_json_mutation()

    def extend(self, values: Any, /) -> None:
        _raise_frozen_json_mutation()

    def insert(self, index: Any, value: Any, /) -> None:
        _raise_frozen_json_mutation()

    def pop(self, index: Any = -1, /) -> Any:
        _raise_frozen_json_mutation()

    def remove(self, value: Any, /) -> None:
        _raise_frozen_json_mutation()

    def reverse(self) -> None:
        _raise_frozen_json_mutation()

    def sort(self, *, key: Any = None, reverse: bool = False) -> None:
        _raise_frozen_json_mutation()

    def __copy__(self) -> FrozenJsonList:
        return self

    def __deepcopy__(self, memo: dict[int, Any]) -> FrozenJsonList:
        return self

    def __reduce__(self):
        return type(self), (self._items,)


def _raise_frozen_json_mutation() -> Never:
    raise TypeError("Frozen JSON values cannot be mutated.")


def require_nonblank(value: str, field_name: str) -> str:
    if type(value) is not str:
        raise ValueError(f"`{field_name}` must be a string.")
    if not value.strip():
        raise ValueError(f"`{field_name}` cannot be blank.")
    return value


def require_clean_nonblank(value: str, field_name: str) -> str:
    value = require_nonblank(value, field_name)
    if value != value.strip():
        raise ValueError(f"`{field_name}` must not start or end with whitespace.")
    return value


def require_unicode_scalar_text(value: str, field_name: str) -> str:
    """Reject lone UTF-16 surrogate code points from a validated string."""

    if type(value) is not str:
        raise ValueError(f"`{field_name}` must be a string.")
    if any(0xD800 <= ord(char) <= 0xDFFF for char in value):
        raise ValueError(f"`{field_name}` must not contain Unicode surrogate code points.")
    return value


def require_durable_text(value: str, field_name: str) -> str:
    """Return text that can cross every supported durable JSON boundary."""

    return _require_durable_text(value, field_name, path="$")


def require_durable_nonblank(value: str, field_name: str) -> str:
    """Return portable durable text that is not blank."""

    return require_nonblank(require_durable_text(value, field_name), field_name)


def require_durable_clean_nonblank(value: str, field_name: str) -> str:
    """Return portable durable text without surrounding whitespace."""

    return require_clean_nonblank(require_durable_text(value, field_name), field_name)


def require_execution_unit_id(value: str, field_name: str) -> str:
    """Return one canonical, portable Cayu execution-unit identifier."""

    pattern = _EXECUTION_UNIT_ID_PATTERNS.get(field_name)
    if pattern is None:
        raise ValueError("Unknown execution-unit identity field.")
    value = require_durable_clean_nonblank(value, field_name)
    if pattern.fullmatch(value) is None:
        raise ValueError(f"{field_name} is not a valid Cayu execution-unit identifier.")
    return value


def _require_durable_text(value: Any, field_name: str, *, path: str) -> str:
    if type(value) is not str:
        raise DurableValueError("invalid_text_type", field_name, path=path)
    if "\x00" in value:
        raise DurableValueError("nul_character", field_name, path=path)
    if any(0xD800 <= ord(char) <= 0xDFFF for char in value):
        raise DurableValueError("unicode_surrogate", field_name, path=path)
    return value


def require_unicode_scalar_json(value: Any, field_name: str) -> Any:
    """Reject lone UTF-16 surrogates recursively from a JSON-compatible value."""

    if type(value) is str:
        return require_unicode_scalar_text(value, field_name)
    if type(value) is list:
        for index, item in enumerate(value):
            require_unicode_scalar_json(item, f"{field_name}[{index}]")
        return value
    if type(value) is dict:
        for key, item in value.items():
            require_unicode_scalar_text(key, f"{field_name} key")
            require_unicode_scalar_json(item, f"{field_name}.{key}")
        return value
    return value


def require_durable_json_text(value: Any, field_name: str) -> Any:
    """Reject strings that cannot round-trip through every durable JSON store."""

    if type(value) is str:
        require_unicode_scalar_text(value, field_name)
        if "\x00" in value:
            raise ValueError(f"`{field_name}` must not contain NUL characters.")
        return value
    if type(value) is list:
        for index, item in enumerate(value):
            require_durable_json_text(item, f"{field_name}[{index}]")
        return value
    if type(value) is dict:
        for key, item in value.items():
            require_durable_json_text(key, f"{field_name} key")
            require_durable_json_text(item, f"{field_name}.{key}")
        return value
    return value


def freeze_json_value(value: Any) -> Any:
    """Recursively freeze an already validated JSON-compatible value."""

    if type(value) is FrozenJsonDict or type(value) is FrozenJsonList:
        return value
    if type(value) is dict:
        return FrozenJsonDict({key: freeze_json_value(item) for key, item in value.items()})
    if type(value) is list:
        return FrozenJsonList(freeze_json_value(item) for item in value)
    return value


def thaw_json_value(value: Any) -> Any:
    """Return ordinary JSON containers from recursively frozen JSON data."""

    if type(value) is FrozenJsonDict:
        return {key: thaw_json_value(item) for key, item in value.items()}
    if type(value) is FrozenJsonList:
        return [thaw_json_value(item) for item in value]
    if type(value) is dict:
        return {key: thaw_json_value(item) for key, item in value.items()}
    if type(value) is list:
        return [thaw_json_value(item) for item in value]
    return value


class JsonUtf8SizeCounter:
    """Count compact JSON UTF-8 bytes without building the serialized value."""

    def __init__(
        self,
        limit: int,
        *,
        ensure_ascii: bool = False,
        canonical_durable_numbers: bool = False,
    ) -> None:
        if type(limit) is not int or limit < 0:
            raise ValueError("limit must be a non-negative integer.")
        if type(ensure_ascii) is not bool:
            raise TypeError("ensure_ascii must be a boolean.")
        if type(canonical_durable_numbers) is not bool:
            raise TypeError("canonical_durable_numbers must be a boolean.")
        self.remaining = limit
        self.ensure_ascii = ensure_ascii
        self.canonical_durable_numbers = canonical_durable_numbers
        self.exceeded_limit = False
        self.encountered_unsupported_value = False

    def _consume(self, count: int) -> bool:
        self.remaining -= count
        if self.remaining < 0:
            self.exceeded_limit = True
            return False
        return True

    def _string(self, value: str) -> bool:
        if not self._consume(2):  # opening and closing quotes
            return False
        for character in value:
            codepoint = ord(character)
            if character in {'"', "\\"} or character in "\b\f\n\r\t":
                size = 2
            elif codepoint < 0x20 or (self.ensure_ascii and 0x7F <= codepoint < 0x10000):
                size = 6
            elif self.ensure_ascii and codepoint >= 0x10000:
                size = 12
            elif codepoint < 0x80:
                size = 1
            elif codepoint < 0x800:
                size = 2
            elif codepoint < 0x10000:
                size = 3
            else:
                size = 4
            if not self._consume(size):
                return False
        return True

    def value(self, value: Any) -> bool:
        if value is None:
            return self._consume(4)
        if value is True:
            return self._consume(4)
        if value is False:
            return self._consume(5)
        if isinstance(value, str):
            return self._string(value)
        if isinstance(value, datetime):
            # ``+00:00`` is five bytes longer than Pydantic's UTC ``Z`` form, so
            # this intentionally provides a conservative upper bound.
            return self._string(value.isoformat())
        if isinstance(value, date):
            return self._string(value.isoformat())
        if type(value) in {int, float}:
            try:
                rendered = (
                    _canonical_durable_json_text(value)
                    if self.canonical_durable_numbers
                    else str(value)
                )
            except (AssertionError, OverflowError, ValueError):
                # CPython bounds decimal conversion of very large integers. A
                # size preflight must fail closed instead of leaking that raw
                # interpreter error past a caller expecting a bounded result.
                self.encountered_unsupported_value = True
                return False
            return self._consume(len(rendered.encode("utf-8")))
        if isinstance(value, Decimal):
            try:
                rendered = str(value)
            except (OverflowError, ValueError):
                self.encountered_unsupported_value = True
                return False
            # Pydantic JSON serializes Decimals as strings.
            return self._string(rendered)
        if isinstance(value, BaseModel):
            fields = type(value).model_fields
            if not self._consume(2):
                return False
            for index, (name, field) in enumerate(fields.items()):
                if index and not self._consume(1):
                    return False
                key = field.serialization_alias or field.alias or name
                if not self._string(key) or not self._consume(1):
                    return False
                if not self.value(getattr(value, name)):
                    return False
            return True
        if isinstance(value, Mapping):
            if not self._consume(2):
                return False
            for index, (key, item) in enumerate(value.items()):
                if index and not self._consume(1):
                    return False
                if not self._string(str(key)) or not self._consume(1):
                    return False
                if not self.value(item):
                    return False
            return True
        if isinstance(value, (list, tuple)) or type(value) is FrozenJsonList:
            if not self._consume(2):
                return False
            for index, item in enumerate(value):
                if index and not self._consume(1):
                    return False
                if not self.value(item):
                    return False
            return True
        self.encountered_unsupported_value = True
        return False


def json_utf8_size_within_limit(
    value: Any,
    max_bytes: int,
    *,
    ensure_ascii: bool = False,
) -> bool:
    """Whether compact, unescaped JSON for ``value`` fits ``max_bytes``.

    The walk stops as soon as the limit is exceeded and never allocates a
    serialized copy. Pydantic models, dates, and datetimes are supported for
    internal response-size guards; ordinary JSON containers cover transport
    payloads.
    """
    return JsonUtf8SizeCounter(max_bytes, ensure_ascii=ensure_ascii).value(value)


def compact_json_utf8_size(value: Any) -> int:
    """Exact UTF-8 size of Cayu's canonical compact JSON representation."""
    return len(
        json.dumps(
            value,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
        ).encode("utf-8")
    )


def require_nonblank_keys(value: dict[str, Any], field_name: str) -> dict[str, Any]:
    if type(value) is not dict:
        raise ValueError(f"`{field_name}` must be a dictionary.")
    for key in value:
        if type(key) is not str:
            raise ValueError(f"`{field_name}` keys must be strings.")
        require_nonblank(key, f"{field_name} key")
    return value


def require_clean_nonblank_keys(value: dict[str, Any], field_name: str) -> dict[str, Any]:
    if type(value) is not dict:
        raise ValueError(f"`{field_name}` must be a dictionary.")
    for key in value:
        if type(key) is not str:
            raise ValueError(f"`{field_name}` keys must be strings.")
        require_clean_nonblank(key, f"{field_name} key")
    return value


def copy_label_map(
    value: Any,
    field_name: str,
    *,
    allow_reserved: bool = True,
) -> dict[str, str]:
    if value is None:
        return {}
    value = copy_durable_json_object(value, field_name)
    copied: dict[str, str] = {}
    for key, item in value.items():
        if type(key) is not str:
            raise ValueError(f"`{field_name}` keys must be strings.")
        clean_key = require_clean_nonblank(
            require_durable_text(key, f"{field_name} key"),
            f"{field_name} key",
        )
        if len(clean_key) > _MAX_LABEL_KEY_LENGTH:
            raise ValueError(
                f"`{field_name}` keys must be at most {_MAX_LABEL_KEY_LENGTH} characters."
            )
        if not allow_reserved and clean_key.startswith(_RESERVED_LABEL_PREFIX):
            raise ValueError(
                f"`{field_name}` keys starting with `{_RESERVED_LABEL_PREFIX}` "
                "are reserved for Cayu."
            )
        if type(item) is not str:
            raise ValueError(f"`{field_name}.{clean_key}` must be a string.")
        clean_value = require_clean_nonblank(
            require_durable_text(item, f"{field_name}.{clean_key}"),
            f"{field_name}.{clean_key}",
        )
        if len(clean_value) > _MAX_LABEL_VALUE_LENGTH:
            raise ValueError(
                f"`{field_name}` values must be at most {_MAX_LABEL_VALUE_LENGTH} characters."
            )
        copied[clean_key] = clean_value
    return copied


def require_finite(value: float, field_name: str) -> float:
    if not isfinite(value):
        raise ValueError(f"`{field_name}` must be finite.")
    return value


def require_positive_timedelta_seconds(
    value: Any,
    field_name: str,
    *,
    relative_to: datetime | None = None,
) -> float:
    """Return positive seconds whose duration and resulting expiry are representable."""

    if type(value) not in {int, float}:
        raise ValueError(f"`{field_name}` must be a finite positive number of seconds.")
    try:
        validated = float(value)
    except OverflowError as exc:
        raise ValueError(f"`{field_name}` must be representable as a timedelta.") from exc
    if not isfinite(validated) or validated <= 0:
        raise ValueError(f"`{field_name}` must be a finite positive number of seconds.")
    try:
        duration = timedelta(seconds=validated)
    except OverflowError as exc:
        raise ValueError(f"`{field_name}` must be representable as a timedelta.") from exc
    if duration <= timedelta(0):
        raise ValueError(f"`{field_name}` must produce a positive timedelta.")
    try:
        (relative_to or datetime.now(UTC)) + duration
    except OverflowError as exc:
        raise ValueError(f"`{field_name}` must produce a representable expiry datetime.") from exc
    return validated


def require_positive_finite_seconds(value: object, field_name: str) -> float:
    """Return one numeric seconds value after exact finite/positive validation."""

    if type(value) not in {int, float}:
        raise TypeError(f"{field_name} must be numeric.")
    normalized = float(cast("int | float", value))
    if not isfinite(normalized) or normalized <= 0:
        raise ValueError(f"{field_name} must be finite and greater than zero.")
    return normalized


def escape_json_pointer_segment(key: str) -> str:
    """Escape one JSON-pointer reference token per RFC 6901 (`~`→`~0`, `/`→`~1`).

    Used to build the `$`-rooted, `/`-separated error paths shared by the
    runtime's structured-output validation and provider schema preflights.
    """
    return key.replace("~", "~0").replace("/", "~1")


def unescape_json_pointer_segment(segment: str) -> str:
    """Decode one JSON-pointer reference token per RFC 6901 (`~1`→`/`, `~0`→`~`).

    The replace order is load-bearing: `~1` must be decoded before `~0` so
    that `~01` becomes `~1`, not `/` (RFC 6901 section 4).
    """
    return segment.replace("~1", "/").replace("~0", "~")


def copy_durable_json_value(value: Any, field_name: str) -> Any:
    """Validate and defensively copy one portable durable JSON value."""

    try:
        return _copy_durable_json_value(
            value,
            field_name,
            path="$",
            active_container_ids=set(),
            container_depth=0,
        )
    except RecursionError as exc:
        raise DurableValueError("nesting_too_deep", field_name) from exc


def copy_durable_json_object(value: Any, field_name: str) -> dict[str, Any]:
    copied = copy_durable_json_value(value, field_name)
    if type(copied) is not dict:
        raise DurableValueError("invalid_json_object", field_name)
    return copied


def canonical_durable_json_bytes(value: Any, field_name: str) -> bytes:
    """Return one backend-stable canonical encoding of a durable JSON value.

    PostgreSQL JSONB preserves a JSON number's value but may normalize its
    spelling and decoded Python type (for example, ``1e18`` can load as an
    ``int``). Hashes and idempotency keys must therefore canonicalize numeric
    value semantics instead of hashing Python's input spelling.
    """

    copied = copy_durable_json_value(value, field_name)
    return _canonical_durable_json_text(copied).encode("utf-8")


def copy_json_value(value: Any, field_name: str) -> Any:
    return _copy_json_value(value, field_name, set())


def copy_json_object(value: Any, field_name: str) -> dict[str, Any]:
    copied = copy_json_value(value, field_name)
    if type(copied) is not dict:
        raise ValueError(f"`{field_name}` must be a JSON object.")
    return copied


def validate_json_value(value: Any, field_name: str) -> None:
    _copy_json_value(value, field_name, set())


def collision_safe_json_object(
    items: Iterable[tuple[str, Any]],
    *,
    preserve_input_order: bool,
) -> dict[str, Any]:
    """Build a deterministic JSON object without dropping transformed key collisions."""

    indexed_items = [
        (
            index,
            key,
            json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False),
            value,
        )
        for index, (key, value) in enumerate(items)
    ]
    assigned: list[tuple[int, str, Any]] = []
    counts: dict[str, int] = {}
    used_keys: set[str] = set()
    for index, key, _, value in sorted(indexed_items, key=lambda item: (item[1], item[2])):
        count = counts.get(key, 0) + 1
        candidate = key if count == 1 else f"{key}_{count}"
        while candidate in used_keys:
            count += 1
            candidate = f"{key}_{count}"
        counts[key] = count
        used_keys.add(candidate)
        assigned.append((index, candidate, value))

    if preserve_input_order:
        assigned.sort(key=lambda item: item[0])
    return {key: value for _, key, value in assigned}


def _copy_durable_json_value(
    value: Any,
    field_name: str,
    *,
    path: str,
    active_container_ids: set[int],
    container_depth: int,
) -> Any:
    if value is None or type(value) is bool:
        return value
    if type(value) is str:
        return _require_durable_text(value, field_name, path=path)
    if type(value) is int:
        if MIN_DURABLE_JSON_INTEGER <= value <= MAX_DURABLE_JSON_INTEGER:
            return value
        raise DurableValueError("integer_out_of_range", field_name, path=path)
    if type(value) is float:
        if not isfinite(value):
            raise DurableValueError("non_finite_number", field_name, path=path)
        if value.is_integer() and not (
            MIN_DURABLE_JSON_INTEGER <= value <= MAX_DURABLE_JSON_INTEGER
        ):
            # JSONB can render an exponent-form integral float as an integer.
            # Reject values that would then fail the shared int64 contract on
            # reload instead of accepting a write that cannot be reconstructed.
            raise DurableValueError("integral_float_out_of_range", field_name, path=path)
        # JSON has one number domain rather than distinct integer/float types.
        # PostgreSQL JSONB may decode exponent-form integral floats (for
        # example, 1e18) as ``int`` while memory and SQLite otherwise retain a
        # Python ``float``. Canonicalize every in-range integral float at the
        # shared boundary so all stores, JSONL, hashing, and replay return the
        # exact same Python representation. This also collapses signed zero.
        return int(value) if value.is_integer() else value
    if type(value) in {list, FrozenJsonList}:
        next_depth = container_depth + 1
        if next_depth > MAX_DURABLE_JSON_NESTING:
            raise DurableValueError("nesting_too_deep", field_name, path=path)
        value_id = id(value)
        if value_id in active_container_ids:
            raise DurableValueError("circular_reference", field_name, path=path)
        active_container_ids.add(value_id)
        try:
            return [
                _copy_durable_json_value(
                    item,
                    field_name,
                    path=_durable_child_path(path, index, object_value=False),
                    active_container_ids=active_container_ids,
                    container_depth=next_depth,
                )
                for index, item in enumerate(value)
            ]
        finally:
            active_container_ids.remove(value_id)
    if type(value) in {dict, FrozenJsonDict}:
        next_depth = container_depth + 1
        if next_depth > MAX_DURABLE_JSON_NESTING:
            raise DurableValueError("nesting_too_deep", field_name, path=path)
        value_id = id(value)
        if value_id in active_container_ids:
            raise DurableValueError("circular_reference", field_name, path=path)
        active_container_ids.add(value_id)
        try:
            copied: dict[str, Any] = {}
            for index, (key, item) in enumerate(value.items()):
                child_path = _durable_child_path(path, index, object_value=True)
                if type(key) is not str:
                    raise DurableValueError(
                        "invalid_json_key",
                        field_name,
                        path=f"{child_path}/key",
                    )
                _require_durable_text(key, field_name, path=f"{child_path}/key")
                copied[key] = _copy_durable_json_value(
                    item,
                    field_name,
                    path=child_path,
                    active_container_ids=active_container_ids,
                    container_depth=next_depth,
                )
            return copied
        finally:
            active_container_ids.remove(value_id)
    raise DurableValueError("invalid_json_type", field_name, path=path)


def _canonical_durable_json_text(value: Any) -> str:
    if value is None:
        return "null"
    if type(value) is bool:
        return "true" if value else "false"
    if type(value) is str:
        return json.dumps(value, ensure_ascii=False, separators=(",", ":"))
    if type(value) is int:
        return str(value)
    if type(value) is float:
        if value == 0.0:
            return "0"
        if value.is_integer():
            return str(int(value))
        sign, digits, decimal_exponent = Decimal(repr(value)).as_tuple()
        if type(decimal_exponent) is not int:  # pragma: no cover - finite float invariant
            raise AssertionError("Finite float produced a non-finite Decimal exponent.")
        exponent = decimal_exponent
        while len(digits) > 1 and digits[-1] == 0:
            digits = digits[:-1]
            exponent += 1
        coefficient = "".join(str(digit) for digit in digits)
        prefix = "-" if sign else ""
        return f"{prefix}{coefficient}e{exponent}"
    if type(value) is list:
        return "[" + ",".join(_canonical_durable_json_text(item) for item in value) + "]"
    if type(value) is dict:
        entries = (
            json.dumps(key, ensure_ascii=False, separators=(",", ":"))
            + ":"
            + _canonical_durable_json_text(value[key])
            for key in sorted(value)
        )
        return "{" + ",".join(entries) + "}"
    raise TypeError("Canonical durable JSON received an unvalidated value.")


def _copy_json_value(value: Any, field_name: str, seen: set[int]) -> Any:
    if value is None or type(value) in {str, bool, int}:
        return value
    if type(value) is float:
        if isfinite(value):
            return value
        raise ValueError(f"`{field_name}` must contain finite JSON numbers.")
    if type(value) in {list, FrozenJsonList}:
        value_id = id(value)
        if value_id in seen:
            raise ValueError(f"`{field_name}` must not contain circular references.")
        seen.add(value_id)
        try:
            return [
                _copy_json_value(item, f"{field_name}[{index}]", seen)
                for index, item in enumerate(value)
            ]
        finally:
            seen.remove(value_id)
    if type(value) in {dict, FrozenJsonDict}:
        value_id = id(value)
        if value_id in seen:
            raise ValueError(f"`{field_name}` must not contain circular references.")
        seen.add(value_id)
        try:
            copied: dict[str, Any] = {}
            for key, item in value.items():
                if type(key) is not str:
                    raise ValueError(f"`{field_name}` JSON object keys must be strings.")
                copied[key] = _copy_json_value(item, f"{field_name}.{key}", seen)
            return copied
        finally:
            seen.remove(value_id)
    raise ValueError(f"`{field_name}` must contain JSON-compatible values.")


def _durable_child_path(path: str, index: int, *, object_value: bool) -> str:
    marker = f"#{index}" if object_value else str(index)
    return _bounded_ascii_label(
        f"{path}/{marker}",
        limit=_MAX_DURABLE_ERROR_PATH_CHARS,
        fallback="$",
    )
