"""Explicit public exports; implementations load on first access."""

EXPORTS: dict[str, tuple[str, str]] = {
    "ApprovedEgressDestination": ("cayu.egress.destinations", "ApprovedEgressDestination"),
    "BrowserEgressPolicy": ("cayu.egress.policy", "BrowserEgressPolicy"),
    "CapturedRequest": ("cayu.egress.broker", "CapturedRequest"),
    "CapturedResponse": ("cayu.egress.broker", "CapturedResponse"),
    "CredentialKind": ("cayu.egress.credential_kinds", "CredentialKind"),
    "CredentialMode": ("cayu.credentials", "CredentialMode"),
    "DockerEgressReconnectError": ("cayu.egress.errors", "DockerEgressReconnectError"),
    "EGRESS_AUTHORITY_SCHEMA_VERSION": ("cayu.egress.authority", "EGRESS_AUTHORITY_SCHEMA_VERSION"),
    "EGRESS_AUTHORITY_TRANSITION_CHECKPOINT_KEY": (
        "cayu.egress.transitions",
        "EGRESS_AUTHORITY_TRANSITION_CHECKPOINT_KEY",
    ),
    "EGRESS_AUTHORITY_TRANSITION_SCHEMA_VERSION": (
        "cayu.egress.transitions",
        "EGRESS_AUTHORITY_TRANSITION_SCHEMA_VERSION",
    ),
    "EGRESS_CAPABILITY_EVIDENCE_SCHEMA": (
        "cayu.egress.capabilities",
        "EGRESS_CAPABILITY_EVIDENCE_SCHEMA",
    ),
    "EgressAdapterRegistry": ("cayu.egress.adapter", "EgressAdapterRegistry"),
    "EgressAuthorityAdoptionHandler": ("cayu.egress.transitions", "EgressAuthorityAdoptionHandler"),
    "EgressAuthorityAdoptionResult": ("cayu.egress.transitions", "EgressAuthorityAdoptionResult"),
    "EgressAuthorityBindingIdentity": ("cayu.egress.authority", "EgressAuthorityBindingIdentity"),
    "EgressAuthorityChangeKind": ("cayu.egress.authority", "EgressAuthorityChangeKind"),
    "EgressAuthorityCutoverError": ("cayu.egress.errors", "EgressAuthorityCutoverError"),
    "EgressAuthorityCutoverNeedsAttention": (
        "cayu.egress.errors",
        "EgressAuthorityCutoverNeedsAttention",
    ),
    "EgressAuthorityCutoverReceipt": ("cayu.egress.authority", "EgressAuthorityCutoverReceipt"),
    "EgressAuthorityCutoverRequest": ("cayu.egress.adapter", "EgressAuthorityCutoverRequest"),
    "EgressAuthorityCutoverResult": ("cayu.egress.adapter", "EgressAuthorityCutoverResult"),
    "EgressAuthorityCutoverStrategy": ("cayu.egress.authority", "EgressAuthorityCutoverStrategy"),
    "EgressAuthorityIdentity": ("cayu.egress.authority", "EgressAuthorityIdentity"),
    "EgressAuthorityOperation": ("cayu.egress.authority", "EgressAuthorityOperation"),
    "EgressAuthorityPolicyIdentity": ("cayu.egress.authority", "EgressAuthorityPolicyIdentity"),
    "EgressAuthorityRenewalRequest": ("cayu.egress.adapter", "EgressAuthorityRenewalRequest"),
    "EgressAuthorityTransitionConflict": (
        "cayu.egress.transitions",
        "EgressAuthorityTransitionConflict",
    ),
    "EgressAuthorityTransitionCoordinator": (
        "cayu.egress.transitions",
        "EgressAuthorityTransitionCoordinator",
    ),
    "EgressAuthorityTransitionRecord": (
        "cayu.egress.transitions",
        "EgressAuthorityTransitionRecord",
    ),
    "EgressAuthorityTransitionState": ("cayu.egress.authority", "EgressAuthorityTransitionState"),
    "EgressBinding": ("cayu.egress.adapter", "EgressBinding"),
    "EgressCapabilityClaim": ("cayu.egress.capabilities", "EgressCapabilityClaim"),
    "EgressCapabilityDetail": ("cayu.egress.capabilities", "EgressCapabilityDetail"),
    "EgressCapabilityEvidence": ("cayu.egress.capabilities", "EgressCapabilityEvidence"),
    "EgressCapabilityState": ("cayu.egress.capabilities", "EgressCapabilityState"),
    "EgressDecision": ("cayu.egress.broker", "EgressDecision"),
    "EgressError": ("cayu.egress.errors", "EgressError"),
    "EgressPolicy": ("cayu.egress.policy", "EgressPolicy"),
    "EgressProtocol": ("cayu.egress.destinations", "EgressProtocol"),
    "EgressReconnectConflictError": ("cayu.egress.errors", "EgressReconnectConflictError"),
    "EgressReconnectError": ("cayu.egress.errors", "EgressReconnectError"),
    "EgressReconnectNotFoundError": ("cayu.egress.errors", "EgressReconnectNotFoundError"),
    "EgressRequest": ("cayu.egress.policy", "EgressRequest"),
    "EgressUpstream": ("cayu.egress.broker", "EgressUpstream"),
    "EgressUpstreamLimits": ("cayu.egress.broker", "EgressUpstreamLimits"),
    "EgressUpstreamOperation": ("cayu.egress.broker", "EgressUpstreamOperation"),
    "HttpEgressPolicy": ("cayu.egress.policy", "HttpEgressPolicy"),
    "HttpxUpstream": ("cayu.egress.broker", "HttpxUpstream"),
    "InvalidEgressReconnectMetadataError": (
        "cayu.egress.errors",
        "InvalidEgressReconnectMetadataError",
    ),
    "RunnerFinalizationResult": ("cayu.egress.adapter", "RunnerFinalizationResult"),
    "SandboxEgressAdapter": ("cayu.egress.adapter", "SandboxEgressAdapter"),
    "SessionCheckpointEgressAuthorityTransitionStore": (
        "cayu.egress.transitions",
        "SessionCheckpointEgressAuthorityTransitionStore",
    ),
    "TransparentEgressBroker": ("cayu.egress.broker", "TransparentEgressBroker"),
    "UnsupportedEgressAdapter": ("cayu.egress.adapter", "UnsupportedEgressAdapter"),
    "UnsupportedEgressAuthorityCutoverError": (
        "cayu.egress.errors",
        "UnsupportedEgressAuthorityCutoverError",
    ),
    "UnsupportedEgressCapabilityError": ("cayu.egress.errors", "UnsupportedEgressCapabilityError"),
    "UnsupportedEgressError": ("cayu.egress.errors", "UnsupportedEgressError"),
    "UnsupportedEgressReconnectError": ("cayu.egress.errors", "UnsupportedEgressReconnectError"),
    "VIRTUAL_EGRESS_EVENT_TYPES": ("cayu.egress.runtime", "VIRTUAL_EGRESS_EVENT_TYPES"),
    "VIRTUAL_EGRESS_RECONNECT_VERSION": ("cayu.egress.runtime", "VIRTUAL_EGRESS_RECONNECT_VERSION"),
    "VirtualCredentialError": ("cayu.egress.errors", "VirtualCredentialError"),
    "VirtualCredentialGrant": ("cayu.egress.grants", "VirtualCredentialGrant"),
    "VirtualCredentialLease": ("cayu.egress.grants", "VirtualCredentialLease"),
    "VirtualCredentialRegistry": ("cayu.egress.grants", "VirtualCredentialRegistry"),
    "VirtualCredentialSpec": ("cayu.egress.runtime", "VirtualCredentialSpec"),
    "VirtualEgressEnvironmentFactory": ("cayu.egress.runtime", "VirtualEgressEnvironmentFactory"),
    "VirtualEgressRunnerRequest": ("cayu.egress.adapter", "VirtualEgressRunnerRequest"),
    "VirtualEgressWorkspaceFactory": ("cayu.egress.runtime", "VirtualEgressWorkspaceFactory"),
    "VpcTaskProxyExposure": ("cayu.egress.proxy_exposure", "VpcTaskProxyExposure"),
    "advance_egress_authority_transition": (
        "cayu.egress.transitions",
        "advance_egress_authority_transition",
    ),
    "authorized_egress_authority_transition": (
        "cayu.egress.transitions",
        "authorized_egress_authority_transition",
    ),
    "build_egress_authority_cutover_receipt": (
        "cayu.egress.authority",
        "build_egress_authority_cutover_receipt",
    ),
    "build_egress_authority_identity": ("cayu.egress.authority", "build_egress_authority_identity"),
    "compare_egress_authority": ("cayu.egress.authority", "compare_egress_authority"),
    "egress_authority_owner_fingerprint": (
        "cayu.egress.transitions",
        "egress_authority_owner_fingerprint",
    ),
    "egress_authority_transition_events": (
        "cayu.egress.transitions",
        "egress_authority_transition_events",
    ),
}

PUBLIC_NAMES = [
    "ApprovedEgressDestination",
    "BrowserEgressPolicy",
    "CapturedRequest",
    "CapturedResponse",
    "CredentialKind",
    "CredentialMode",
    "DockerEgressReconnectError",
    "EGRESS_AUTHORITY_SCHEMA_VERSION",
    "EGRESS_AUTHORITY_TRANSITION_CHECKPOINT_KEY",
    "EGRESS_AUTHORITY_TRANSITION_SCHEMA_VERSION",
    "EGRESS_CAPABILITY_EVIDENCE_SCHEMA",
    "EgressAdapterRegistry",
    "EgressAuthorityAdoptionHandler",
    "EgressAuthorityAdoptionResult",
    "EgressAuthorityBindingIdentity",
    "EgressAuthorityChangeKind",
    "EgressAuthorityCutoverError",
    "EgressAuthorityCutoverNeedsAttention",
    "EgressAuthorityCutoverReceipt",
    "EgressAuthorityCutoverRequest",
    "EgressAuthorityCutoverResult",
    "EgressAuthorityCutoverStrategy",
    "EgressAuthorityIdentity",
    "EgressAuthorityOperation",
    "EgressAuthorityPolicyIdentity",
    "EgressAuthorityRenewalRequest",
    "EgressAuthorityTransitionConflict",
    "EgressAuthorityTransitionCoordinator",
    "EgressAuthorityTransitionRecord",
    "EgressAuthorityTransitionState",
    "EgressBinding",
    "EgressCapabilityClaim",
    "EgressCapabilityDetail",
    "EgressCapabilityEvidence",
    "EgressCapabilityState",
    "EgressDecision",
    "EgressError",
    "EgressPolicy",
    "EgressProtocol",
    "EgressReconnectConflictError",
    "EgressReconnectError",
    "EgressReconnectNotFoundError",
    "EgressRequest",
    "EgressUpstream",
    "EgressUpstreamLimits",
    "EgressUpstreamOperation",
    "HttpEgressPolicy",
    "HttpxUpstream",
    "InvalidEgressReconnectMetadataError",
    "RunnerFinalizationResult",
    "SandboxEgressAdapter",
    "SessionCheckpointEgressAuthorityTransitionStore",
    "TransparentEgressBroker",
    "UnsupportedEgressAdapter",
    "UnsupportedEgressAuthorityCutoverError",
    "UnsupportedEgressCapabilityError",
    "UnsupportedEgressError",
    "UnsupportedEgressReconnectError",
    "VIRTUAL_EGRESS_EVENT_TYPES",
    "VIRTUAL_EGRESS_RECONNECT_VERSION",
    "VirtualCredentialError",
    "VirtualCredentialGrant",
    "VirtualCredentialLease",
    "VirtualCredentialRegistry",
    "VirtualCredentialSpec",
    "VirtualEgressEnvironmentFactory",
    "VirtualEgressRunnerRequest",
    "VirtualEgressWorkspaceFactory",
    "VpcTaskProxyExposure",
    "advance_egress_authority_transition",
    "authorized_egress_authority_transition",
    "build_egress_authority_cutover_receipt",
    "build_egress_authority_identity",
    "compare_egress_authority",
    "egress_authority_owner_fingerprint",
    "egress_authority_transition_events",
]
