"""Explicit public exports; implementations load on first access."""

EXPORTS: dict[str, tuple[str, str]] = {
    "AGENT_BUNDLE_CONTAINER_EXTENSION": (
        "cayu.snapshots.containers",
        "AGENT_BUNDLE_CONTAINER_EXTENSION",
    ),
    "AGENT_BUNDLE_CONTAINER_MAX_BYTES": (
        "cayu.snapshots.containers",
        "AGENT_BUNDLE_CONTAINER_MAX_BYTES",
    ),
    "AGENT_BUNDLE_CONTAINER_MAX_ENTRIES": (
        "cayu.snapshots.containers",
        "AGENT_BUNDLE_CONTAINER_MAX_ENTRIES",
    ),
    "AGENT_BUNDLE_CONTAINER_MEDIA_TYPE": (
        "cayu.snapshots.containers",
        "AGENT_BUNDLE_CONTAINER_MEDIA_TYPE",
    ),
    "AGENT_BUNDLE_CONTAINER_MIMETYPE_ENTRY": (
        "cayu.snapshots.containers",
        "AGENT_BUNDLE_CONTAINER_MIMETYPE_ENTRY",
    ),
    "AGENT_BUNDLE_CONTAINER_SCHEMA_VERSION": (
        "cayu.snapshots.containers",
        "AGENT_BUNDLE_CONTAINER_SCHEMA_VERSION",
    ),
    "AGENT_BUNDLE_INDEX_FILENAME": ("cayu.snapshots.bundles", "AGENT_BUNDLE_INDEX_FILENAME"),
    "AGENT_BUNDLE_MAX_INDEX_BYTES": ("cayu.snapshots.bundles", "AGENT_BUNDLE_MAX_INDEX_BYTES"),
    "AGENT_BUNDLE_MAX_OBJECTS": ("cayu.snapshots.bundles", "AGENT_BUNDLE_MAX_OBJECTS"),
    "AGENT_BUNDLE_MAX_OBJECT_BYTES": ("cayu.snapshots.bundles", "AGENT_BUNDLE_MAX_OBJECT_BYTES"),
    "AGENT_BUNDLE_MAX_TOTAL_BYTES": ("cayu.snapshots.bundles", "AGENT_BUNDLE_MAX_TOTAL_BYTES"),
    "AGENT_BUNDLE_OBJECT_DIRECTORY": ("cayu.snapshots.bundles", "AGENT_BUNDLE_OBJECT_DIRECTORY"),
    "AGENT_BUNDLE_RECORD_TYPE": ("cayu.snapshots.bundles", "AGENT_BUNDLE_RECORD_TYPE"),
    "AGENT_BUNDLE_SCHEMA_VERSION": ("cayu.snapshots.bundles", "AGENT_BUNDLE_SCHEMA_VERSION"),
    "AGENT_SNAPSHOT_MAX_BYTES": ("cayu.snapshots.base", "AGENT_SNAPSHOT_MAX_BYTES"),
    "AGENT_SNAPSHOT_NODE_RECORD_TYPE": ("cayu.snapshots.base", "AGENT_SNAPSHOT_NODE_RECORD_TYPE"),
    "AGENT_SNAPSHOT_NODE_SCHEMA_VERSION": (
        "cayu.snapshots.base",
        "AGENT_SNAPSHOT_NODE_SCHEMA_VERSION",
    ),
    "AGENT_SNAPSHOT_RECORD_TYPE": ("cayu.snapshots.base", "AGENT_SNAPSHOT_RECORD_TYPE"),
    "AGENT_SNAPSHOT_SCHEMA_VERSION": ("cayu.snapshots.base", "AGENT_SNAPSHOT_SCHEMA_VERSION"),
    "AGENT_SNAPSHOT_TRIAL_METADATA_KEY": (
        "cayu.snapshots.base",
        "AGENT_SNAPSHOT_TRIAL_METADATA_KEY",
    ),
    "AgentBundle": ("cayu.snapshots.bundles", "AgentBundle"),
    "AgentBundleContainerInspection": (
        "cayu.snapshots.containers",
        "AgentBundleContainerInspection",
    ),
    "AgentBundleContainerReceipt": ("cayu.snapshots.containers", "AgentBundleContainerReceipt"),
    "AgentBundleCoordinator": ("cayu.snapshots.bundles", "AgentBundleCoordinator"),
    "AgentBundleError": ("cayu.snapshots.bundles", "AgentBundleError"),
    "AgentBundleExportReceipt": ("cayu.snapshots.bundles", "AgentBundleExportReceipt"),
    "AgentBundleImportReceipt": ("cayu.snapshots.bundles", "AgentBundleImportReceipt"),
    "AgentBundleInventory": ("cayu.snapshots.bundles", "AgentBundleInventory"),
    "AgentBundleMaterializationAuthority": (
        "cayu.snapshots.bundles",
        "AgentBundleMaterializationAuthority",
    ),
    "AgentBundleMaterializationAuthorization": (
        "cayu.snapshots.bundles",
        "AgentBundleMaterializationAuthorization",
    ),
    "AgentBundleMaterializationReceipt": (
        "cayu.snapshots.bundles",
        "AgentBundleMaterializationReceipt",
    ),
    "AgentBundleMaterializationRequest": (
        "cayu.snapshots.bundles",
        "AgentBundleMaterializationRequest",
    ),
    "AgentBundleMode": ("cayu.snapshots.bundles", "AgentBundleMode"),
    "AgentBundleObjectKind": ("cayu.snapshots.bundles", "AgentBundleObjectKind"),
    "AgentBundleObjectRef": ("cayu.snapshots.bundles", "AgentBundleObjectRef"),
    "AgentBundleSizeReport": ("cayu.snapshots.bundles", "AgentBundleSizeReport"),
    "AgentExternalBindingKind": ("cayu.snapshots.bundles", "AgentExternalBindingKind"),
    "AgentExternalBindingRequirement": (
        "cayu.snapshots.bundles",
        "AgentExternalBindingRequirement",
    ),
    "AgentExternalBindingResolution": ("cayu.snapshots.bundles", "AgentExternalBindingResolution"),
    "AgentMaterializationFreshIdentities": (
        "cayu.snapshots.bundles",
        "AgentMaterializationFreshIdentities",
    ),
    "AgentSnapshot": ("cayu.snapshots.base", "AgentSnapshot"),
    "AgentSnapshotAccess": ("cayu.snapshots.base", "AgentSnapshotAccess"),
    "AgentSnapshotAuthorityRef": ("cayu.snapshots.base", "AgentSnapshotAuthorityRef"),
    "AgentSnapshotAuthorizationError": ("cayu.snapshots.base", "AgentSnapshotAuthorizationError"),
    "AgentSnapshotCaptureError": ("cayu.snapshots.base", "AgentSnapshotCaptureError"),
    "AgentSnapshotCaptureRequest": ("cayu.snapshots.base", "AgentSnapshotCaptureRequest"),
    "AgentSnapshotClosureInspection": ("cayu.snapshots.base", "AgentSnapshotClosureInspection"),
    "AgentSnapshotCompleteness": ("cayu.snapshots.base", "AgentSnapshotCompleteness"),
    "AgentSnapshotComponentCapture": ("cayu.snapshots.base", "AgentSnapshotComponentCapture"),
    "AgentSnapshotComponentFile": ("cayu.snapshots.bundles", "AgentSnapshotComponentFile"),
    "AgentSnapshotComponentKind": ("cayu.snapshots.base", "AgentSnapshotComponentKind"),
    "AgentSnapshotComponentPackage": ("cayu.snapshots.bundles", "AgentSnapshotComponentPackage"),
    "AgentSnapshotComponentProvider": ("cayu.snapshots.base", "AgentSnapshotComponentProvider"),
    "AgentSnapshotComponentRef": ("cayu.snapshots.base", "AgentSnapshotComponentRef"),
    "AgentSnapshotComponentSelector": ("cayu.snapshots.base", "AgentSnapshotComponentSelector"),
    "AgentSnapshotConsistency": ("cayu.snapshots.base", "AgentSnapshotConsistency"),
    "AgentSnapshotCoordinator": ("cayu.snapshots.base", "AgentSnapshotCoordinator"),
    "AgentSnapshotExecutionProfileComponent": (
        "cayu.snapshots.base",
        "AgentSnapshotExecutionProfileComponent",
    ),
    "AgentSnapshotExecutionProfileRef": ("cayu.snapshots.base", "AgentSnapshotExecutionProfileRef"),
    "AgentSnapshotGCPlan": ("cayu.snapshots.base", "AgentSnapshotGCPlan"),
    "AgentSnapshotGCReceipt": ("cayu.snapshots.base", "AgentSnapshotGCReceipt"),
    "AgentSnapshotGCRequest": ("cayu.snapshots.base", "AgentSnapshotGCRequest"),
    "AgentSnapshotIdentityBinding": ("cayu.snapshots.base", "AgentSnapshotIdentityBinding"),
    "AgentSnapshotLearningDisposition": ("cayu.snapshots.base", "AgentSnapshotLearningDisposition"),
    "AgentSnapshotLogicalRef": ("cayu.snapshots.base", "AgentSnapshotLogicalRef"),
    "AgentSnapshotMaterialization": ("cayu.snapshots.base", "AgentSnapshotMaterialization"),
    "AgentSnapshotMaterializationCapability": (
        "cayu.snapshots.base",
        "AgentSnapshotMaterializationCapability",
    ),
    "AgentSnapshotMaterializationError": (
        "cayu.snapshots.base",
        "AgentSnapshotMaterializationError",
    ),
    "AgentSnapshotMaterializationMode": (
        "cayu.snapshots.bundles",
        "AgentSnapshotMaterializationMode",
    ),
    "AgentSnapshotMaterializationOperation": (
        "cayu.snapshots.base",
        "AgentSnapshotMaterializationOperation",
    ),
    "AgentSnapshotMaterializationProgress": (
        "cayu.snapshots.base",
        "AgentSnapshotMaterializationProgress",
    ),
    "AgentSnapshotMaterializationRequest": (
        "cayu.snapshots.base",
        "AgentSnapshotMaterializationRequest",
    ),
    "AgentSnapshotMaterializedComponent": (
        "cayu.snapshots.base",
        "AgentSnapshotMaterializedComponent",
    ),
    "AgentSnapshotNode": ("cayu.snapshots.base", "AgentSnapshotNode"),
    "AgentSnapshotNodeChild": ("cayu.snapshots.base", "AgentSnapshotNodeChild"),
    "AgentSnapshotNodeKind": ("cayu.snapshots.base", "AgentSnapshotNodeKind"),
    "AgentSnapshotObjectStore": ("cayu.snapshots.bundles", "AgentSnapshotObjectStore"),
    "AgentSnapshotOverlayKind": ("cayu.snapshots.base", "AgentSnapshotOverlayKind"),
    "AgentSnapshotOverlayRef": ("cayu.snapshots.base", "AgentSnapshotOverlayRef"),
    "AgentSnapshotPinReceipt": ("cayu.snapshots.base", "AgentSnapshotPinReceipt"),
    "AgentSnapshotPinRequest": ("cayu.snapshots.base", "AgentSnapshotPinRequest"),
    "AgentSnapshotProfile": ("cayu.snapshots.bundles", "AgentSnapshotProfile"),
    "AgentSnapshotProtection": ("cayu.snapshots.base", "AgentSnapshotProtection"),
    "AgentSnapshotProtectionKind": ("cayu.snapshots.base", "AgentSnapshotProtectionKind"),
    "AgentSnapshotPutReceipt": ("cayu.snapshots.base", "AgentSnapshotPutReceipt"),
    "AgentSnapshotRedaction": ("cayu.snapshots.base", "AgentSnapshotRedaction"),
    "AgentSnapshotRef": ("cayu.snapshots.base", "AgentSnapshotRef"),
    "AgentSnapshotReleaseReceipt": ("cayu.snapshots.base", "AgentSnapshotReleaseReceipt"),
    "AgentSnapshotReleaseRequest": ("cayu.snapshots.base", "AgentSnapshotReleaseRequest"),
    "AgentSnapshotResultBinding": ("cayu.snapshots.base", "AgentSnapshotResultBinding"),
    "AgentSnapshotRetentionClass": ("cayu.snapshots.base", "AgentSnapshotRetentionClass"),
    "AgentSnapshotSessionDisposition": (
        "cayu.snapshots.bundles",
        "AgentSnapshotSessionDisposition",
    ),
    "AgentSnapshotStore": ("cayu.snapshots.base", "AgentSnapshotStore"),
    "AgentSnapshotStoreConflict": ("cayu.snapshots.base", "AgentSnapshotStoreConflict"),
    "AgentSnapshotSubject": ("cayu.snapshots.base", "AgentSnapshotSubject"),
    "AgentSnapshotTerminalAuthority": ("cayu.snapshots.bundles", "AgentSnapshotTerminalAuthority"),
    "AgentSnapshotTerminalAuthorization": (
        "cayu.snapshots.bundles",
        "AgentSnapshotTerminalAuthorization",
    ),
    "AgentSnapshotTerminalCaptureReceipt": (
        "cayu.snapshots.bundles",
        "AgentSnapshotTerminalCaptureReceipt",
    ),
    "AgentSnapshotTerminalCaptureRequest": (
        "cayu.snapshots.bundles",
        "AgentSnapshotTerminalCaptureRequest",
    ),
    "AgentSnapshotTerminalDisposition": ("cayu.snapshots.base", "AgentSnapshotTerminalDisposition"),
    "AgentSnapshotTrialBinding": ("cayu.snapshots.base", "AgentSnapshotTrialBinding"),
    "AgentSnapshotTrialStateMode": ("cayu.snapshots.base", "AgentSnapshotTrialStateMode"),
    "AgentSnapshotVerificationError": ("cayu.snapshots.base", "AgentSnapshotVerificationError"),
    "FileSystemAgentSnapshotObjectStore": (
        "cayu.snapshots.bundles",
        "FileSystemAgentSnapshotObjectStore",
    ),
    "InMemoryAgentSnapshotStore": ("cayu.snapshots.base", "InMemoryAgentSnapshotStore"),
    "MemoryStateRef": ("cayu.snapshots.base", "MemoryStateRef"),
    "PortableAgentSnapshotComponentProvider": (
        "cayu.snapshots.bundles",
        "PortableAgentSnapshotComponentProvider",
    ),
    "SQLiteAgentSnapshotStore": ("cayu.snapshots.base", "SQLiteAgentSnapshotStore"),
    "agent_snapshot_component_package": (
        "cayu.snapshots.bundles",
        "agent_snapshot_component_package",
    ),
    "agent_snapshot_consistency": ("cayu.snapshots.base", "agent_snapshot_consistency"),
    "agent_snapshot_from_json": ("cayu.snapshots.base", "agent_snapshot_from_json"),
    "agent_snapshot_to_json": ("cayu.snapshots.base", "agent_snapshot_to_json"),
    "app_body_snapshot_ref": ("cayu.snapshots.base", "app_body_snapshot_ref"),
    "execution_profile_snapshot_ref": ("cayu.snapshots.base", "execution_profile_snapshot_ref"),
    "inspect_agent_bundle_container": (
        "cayu.snapshots.containers",
        "inspect_agent_bundle_container",
    ),
    "load_portable_agent_snapshot_component_providers": (
        "cayu.snapshots.bundles",
        "load_portable_agent_snapshot_component_providers",
    ),
    "pack_agent_bundle": ("cayu.snapshots.containers", "pack_agent_bundle"),
    "store_agent_snapshot_component_package": (
        "cayu.snapshots.bundles",
        "store_agent_snapshot_component_package",
    ),
    "trajectory_snapshot_ref": ("cayu.snapshots.base", "trajectory_snapshot_ref"),
    "unpack_agent_bundle_container": ("cayu.snapshots.containers", "unpack_agent_bundle_container"),
    "workspace_snapshot_ref": ("cayu.snapshots.base", "workspace_snapshot_ref"),
}

PUBLIC_NAMES = [
    "AGENT_BUNDLE_CONTAINER_EXTENSION",
    "AGENT_BUNDLE_CONTAINER_MAX_BYTES",
    "AGENT_BUNDLE_CONTAINER_MAX_ENTRIES",
    "AGENT_BUNDLE_CONTAINER_MEDIA_TYPE",
    "AGENT_BUNDLE_CONTAINER_MIMETYPE_ENTRY",
    "AGENT_BUNDLE_CONTAINER_SCHEMA_VERSION",
    "AGENT_BUNDLE_INDEX_FILENAME",
    "AGENT_BUNDLE_MAX_INDEX_BYTES",
    "AGENT_BUNDLE_MAX_OBJECTS",
    "AGENT_BUNDLE_MAX_OBJECT_BYTES",
    "AGENT_BUNDLE_MAX_TOTAL_BYTES",
    "AGENT_BUNDLE_OBJECT_DIRECTORY",
    "AGENT_BUNDLE_RECORD_TYPE",
    "AGENT_BUNDLE_SCHEMA_VERSION",
    "AGENT_SNAPSHOT_MAX_BYTES",
    "AGENT_SNAPSHOT_NODE_RECORD_TYPE",
    "AGENT_SNAPSHOT_NODE_SCHEMA_VERSION",
    "AGENT_SNAPSHOT_RECORD_TYPE",
    "AGENT_SNAPSHOT_SCHEMA_VERSION",
    "AGENT_SNAPSHOT_TRIAL_METADATA_KEY",
    "AgentBundle",
    "AgentBundleContainerInspection",
    "AgentBundleContainerReceipt",
    "AgentBundleCoordinator",
    "AgentBundleError",
    "AgentBundleExportReceipt",
    "AgentBundleImportReceipt",
    "AgentBundleInventory",
    "AgentBundleMaterializationAuthority",
    "AgentBundleMaterializationAuthorization",
    "AgentBundleMaterializationReceipt",
    "AgentBundleMaterializationRequest",
    "AgentBundleMode",
    "AgentBundleObjectKind",
    "AgentBundleObjectRef",
    "AgentBundleSizeReport",
    "AgentExternalBindingKind",
    "AgentExternalBindingRequirement",
    "AgentExternalBindingResolution",
    "AgentMaterializationFreshIdentities",
    "AgentSnapshot",
    "AgentSnapshotAccess",
    "AgentSnapshotAuthorityRef",
    "AgentSnapshotAuthorizationError",
    "AgentSnapshotCaptureError",
    "AgentSnapshotCaptureRequest",
    "AgentSnapshotClosureInspection",
    "AgentSnapshotCompleteness",
    "AgentSnapshotComponentCapture",
    "AgentSnapshotComponentFile",
    "AgentSnapshotComponentKind",
    "AgentSnapshotComponentPackage",
    "AgentSnapshotComponentProvider",
    "AgentSnapshotComponentRef",
    "AgentSnapshotComponentSelector",
    "AgentSnapshotConsistency",
    "AgentSnapshotCoordinator",
    "AgentSnapshotExecutionProfileComponent",
    "AgentSnapshotExecutionProfileRef",
    "AgentSnapshotGCPlan",
    "AgentSnapshotGCReceipt",
    "AgentSnapshotGCRequest",
    "AgentSnapshotIdentityBinding",
    "AgentSnapshotLearningDisposition",
    "AgentSnapshotLogicalRef",
    "AgentSnapshotMaterialization",
    "AgentSnapshotMaterializationCapability",
    "AgentSnapshotMaterializationError",
    "AgentSnapshotMaterializationMode",
    "AgentSnapshotMaterializationOperation",
    "AgentSnapshotMaterializationProgress",
    "AgentSnapshotMaterializationRequest",
    "AgentSnapshotMaterializedComponent",
    "AgentSnapshotNode",
    "AgentSnapshotNodeChild",
    "AgentSnapshotNodeKind",
    "AgentSnapshotObjectStore",
    "AgentSnapshotOverlayKind",
    "AgentSnapshotOverlayRef",
    "AgentSnapshotPinReceipt",
    "AgentSnapshotPinRequest",
    "AgentSnapshotProfile",
    "AgentSnapshotProtection",
    "AgentSnapshotProtectionKind",
    "AgentSnapshotPutReceipt",
    "AgentSnapshotRedaction",
    "AgentSnapshotRef",
    "AgentSnapshotReleaseReceipt",
    "AgentSnapshotReleaseRequest",
    "AgentSnapshotResultBinding",
    "AgentSnapshotRetentionClass",
    "AgentSnapshotSessionDisposition",
    "AgentSnapshotStore",
    "AgentSnapshotStoreConflict",
    "AgentSnapshotSubject",
    "AgentSnapshotTerminalAuthority",
    "AgentSnapshotTerminalAuthorization",
    "AgentSnapshotTerminalCaptureReceipt",
    "AgentSnapshotTerminalCaptureRequest",
    "AgentSnapshotTerminalDisposition",
    "AgentSnapshotTrialBinding",
    "AgentSnapshotTrialStateMode",
    "AgentSnapshotVerificationError",
    "FileSystemAgentSnapshotObjectStore",
    "InMemoryAgentSnapshotStore",
    "MemoryStateRef",
    "PortableAgentSnapshotComponentProvider",
    "SQLiteAgentSnapshotStore",
    "agent_snapshot_component_package",
    "agent_snapshot_consistency",
    "agent_snapshot_from_json",
    "agent_snapshot_to_json",
    "app_body_snapshot_ref",
    "execution_profile_snapshot_ref",
    "inspect_agent_bundle_container",
    "load_portable_agent_snapshot_component_providers",
    "pack_agent_bundle",
    "store_agent_snapshot_component_package",
    "trajectory_snapshot_ref",
    "unpack_agent_bundle_container",
    "workspace_snapshot_ref",
]
