"""Compatibility imports for contracts owned by ``cayu.tasks.completion_verifier_profiles``."""

from cayu.tasks.completion_verifier_profiles import (
    COMPLETION_VERIFIER_PROFILE_CHANGED_COMPONENT_MAX_ITEMS,
    COMPLETION_VERIFIER_PROFILE_COMPONENT_MAX_ITEMS,
    COMPLETION_VERIFIER_PROFILE_SCHEMA_VERSION,
    CompletionVerifierExecutionProfile,
    CompletionVerifierProfileAdoptionDecision,
    CompletionVerifierProfileComponentDeclaration,
    CompletionVerifierProfileComponentIdentity,
    CompletionVerifierProfilePolicy,
    CompletionVerifierProfilePolicyRequest,
    CompletionVerifierProfilePreparationRequest,
    CompletionVerifierProfileRecord,
    build_completion_verifier_execution_profile,
    changed_completion_verifier_profile_components,
    completion_verifier_profile_adoption_request_sha256,
    completion_verifier_profile_fingerprint,
    completion_verifier_profile_preparation_request_sha256,
    completion_verifier_profile_record_from_document,
    completion_verifier_profile_record_from_preparation,
    copy_completion_verifier_execution_profile,
    copy_completion_verifier_profile_policy_request,
    copy_completion_verifier_profile_preparation_request,
    copy_completion_verifier_profile_record,
    require_completion_verifier_profile_transition,
)
from cayu.tasks.completion_verifier_profiles import (
    COMPLETION_VERIFIER_PROFILE_TEXT_MAX_CHARS as COMPLETION_VERIFIER_PROFILE_TEXT_MAX_CHARS,
)

__all__ = [
    "COMPLETION_VERIFIER_PROFILE_CHANGED_COMPONENT_MAX_ITEMS",
    "COMPLETION_VERIFIER_PROFILE_COMPONENT_MAX_ITEMS",
    "COMPLETION_VERIFIER_PROFILE_SCHEMA_VERSION",
    "CompletionVerifierExecutionProfile",
    "CompletionVerifierProfileAdoptionDecision",
    "CompletionVerifierProfileComponentDeclaration",
    "CompletionVerifierProfileComponentIdentity",
    "CompletionVerifierProfilePolicy",
    "CompletionVerifierProfilePolicyRequest",
    "CompletionVerifierProfilePreparationRequest",
    "CompletionVerifierProfileRecord",
    "build_completion_verifier_execution_profile",
    "changed_completion_verifier_profile_components",
    "completion_verifier_profile_adoption_request_sha256",
    "completion_verifier_profile_fingerprint",
    "completion_verifier_profile_preparation_request_sha256",
    "completion_verifier_profile_record_from_document",
    "completion_verifier_profile_record_from_preparation",
    "copy_completion_verifier_execution_profile",
    "copy_completion_verifier_profile_policy_request",
    "copy_completion_verifier_profile_preparation_request",
    "copy_completion_verifier_profile_record",
    "require_completion_verifier_profile_transition",
]
