"""Explicit public exports; implementations load on first access."""

EXPORTS: dict[str, tuple[str, str]] = {
    "CheckpointCompactionContextPolicy": ("cayu.context.base", "CheckpointCompactionContextPolicy"),
    "CompactionPrompt": ("cayu.context.base", "CompactionPrompt"),
    "CompactionRequest": ("cayu.context.base", "CompactionRequest"),
    "CompactionResult": ("cayu.context.base", "CompactionResult"),
    "ContextCompactor": ("cayu.context.base", "ContextCompactor"),
    "ContextCountingConfig": ("cayu.context.counting", "ContextCountingConfig"),
    "ContextCountingMode": ("cayu.context.counting", "ContextCountingMode"),
    "ContextInputCoverage": ("cayu.context.base", "ContextInputCoverage"),
    "ContextPolicy": ("cayu.context.base", "ContextPolicy"),
    "ContextPressureEstimate": ("cayu.context.base", "ContextPressureEstimate"),
    "ContextPressureOverhead": ("cayu.context.base", "ContextPressureOverhead"),
    "ContextRecallTelemetry": ("cayu.context.base", "ContextRecallTelemetry"),
    "ContextRequest": ("cayu.context.base", "ContextRequest"),
    "ContextUsageState": ("cayu.context.base", "ContextUsageState"),
    "DefaultContextPolicy": ("cayu.context.base", "DefaultContextPolicy"),
    "MessageWindowContextPolicy": ("cayu.context.base", "MessageWindowContextPolicy"),
    "ModelCompactor": ("cayu.context.base", "ModelCompactor"),
    "NativeStructuredOutputUnsupported": (
        "cayu.context.structured_output",
        "NativeStructuredOutputUnsupported",
    ),
    "ObservedDeltaContextEstimator": ("cayu.context.base", "ObservedDeltaContextEstimator"),
    "PromptCacheCompactor": ("cayu.context.base", "PromptCacheCompactor"),
    "PromptContributionAvailability": ("cayu.context.footprints", "PromptContributionAvailability"),
    "PromptContributionFootprint": ("cayu.context.footprints", "PromptContributionFootprint"),
    "PromptContributionKind": ("cayu.context.footprints", "PromptContributionKind"),
    "PromptContributionManifest": ("cayu.context.footprints", "PromptContributionManifest"),
    "REQUEST_FOOTPRINT_CANONICALIZATION_VERSION": (
        "cayu.context.footprints",
        "REQUEST_FOOTPRINT_CANONICALIZATION_VERSION",
    ),
    "REQUEST_FOOTPRINT_SCHEMA_VERSION": (
        "cayu.context.footprints",
        "REQUEST_FOOTPRINT_SCHEMA_VERSION",
    ),
    "RecentTurnsContextPolicy": ("cayu.context.base", "RecentTurnsContextPolicy"),
    "RequestAttachmentGroupFootprint": (
        "cayu.context.footprints",
        "RequestAttachmentGroupFootprint",
    ),
    "RequestAttachmentsFootprint": ("cayu.context.footprints", "RequestAttachmentsFootprint"),
    "RequestCacheBreakpointFootprint": (
        "cayu.context.footprints",
        "RequestCacheBreakpointFootprint",
    ),
    "RequestComponentFootprint": ("cayu.context.footprints", "RequestComponentFootprint"),
    "RequestComponentTokenEstimates": ("cayu.context.footprints", "RequestComponentTokenEstimates"),
    "RequestContentGroupFootprint": ("cayu.context.footprints", "RequestContentGroupFootprint"),
    "RequestFingerprint": ("cayu.context.footprints", "RequestFingerprint"),
    "RequestFingerprintAvailability": ("cayu.context.footprints", "RequestFingerprintAvailability"),
    "RequestFingerprintSet": ("cayu.context.footprints", "RequestFingerprintSet"),
    "RequestFootprint": ("cayu.context.footprints", "RequestFootprint"),
    "RequestFootprintConfig": ("cayu.context.footprints", "RequestFootprintConfig"),
    "RequestMessagesFootprint": ("cayu.context.footprints", "RequestMessagesFootprint"),
    "RequestOptionsFootprint": ("cayu.context.footprints", "RequestOptionsFootprint"),
    "RequestPromptContributionAttribution": (
        "cayu.context.footprints",
        "RequestPromptContributionAttribution",
    ),
    "RequestSize": ("cayu.context.footprints", "RequestSize"),
    "RequestVariant": ("cayu.context.footprints", "RequestVariant"),
    "StructuredOutputError": ("cayu.context.structured_output", "StructuredOutputError"),
    "StructuredOutputSpec": ("cayu.context.structured_output", "StructuredOutputSpec"),
    "StructuredOutputStrategy": ("cayu.context.structured_output", "StructuredOutputStrategy"),
    "StructuredOutputValidation": ("cayu.context.structured_output", "StructuredOutputValidation"),
    "TargetedToolGrantFootprint": ("cayu.context.footprints", "TargetedToolGrantFootprint"),
    "ThinkingConfig": ("cayu.context.thinking", "ThinkingConfig"),
    "ToolDiscoveryProjectionFootprint": (
        "cayu.context.footprints",
        "ToolDiscoveryProjectionFootprint",
    ),
    "ToolDiscoveryViewFootprint": ("cayu.context.footprints", "ToolDiscoveryViewFootprint"),
    "ToolExposureFootprint": ("cayu.context.footprints", "ToolExposureFootprint"),
    "TranscriptDigestCompactor": ("cayu.context.base", "TranscriptDigestCompactor"),
    "UsageTriggeredContextPolicy": ("cayu.context.base", "UsageTriggeredContextPolicy"),
    "build_prompt_contribution_manifest": (
        "cayu.context.footprints",
        "build_prompt_contribution_manifest",
    ),
    "build_request_footprint": ("cayu.context.footprints", "build_request_footprint"),
    "context_input_coverage": ("cayu.context.base", "context_input_coverage"),
    "copy_context_counting_config": ("cayu.context.counting", "copy_context_counting_config"),
    "copy_request_footprint_config": ("cayu.context.footprints", "copy_request_footprint_config"),
    "default_compaction_prompt": ("cayu.context.base", "default_compaction_prompt"),
    "estimate_model_request_context_pressure": (
        "cayu.context.base",
        "estimate_model_request_context_pressure",
    ),
    "strip_old_file_attachments": ("cayu.context.base", "strip_old_file_attachments"),
    "targeted_tool_grant_footprint": ("cayu.context.footprints", "targeted_tool_grant_footprint"),
    "tool_discovery_view_footprint": ("cayu.context.footprints", "tool_discovery_view_footprint"),
    "trim_context_messages": ("cayu.context.base", "trim_context_messages"),
    "trim_context_turns": ("cayu.context.base", "trim_context_turns"),
}

PUBLIC_NAMES = [
    "CheckpointCompactionContextPolicy",
    "CompactionPrompt",
    "CompactionRequest",
    "CompactionResult",
    "ContextCompactor",
    "ContextCountingConfig",
    "ContextCountingMode",
    "ContextInputCoverage",
    "ContextPolicy",
    "ContextPressureEstimate",
    "ContextPressureOverhead",
    "ContextRecallTelemetry",
    "ContextRequest",
    "ContextUsageState",
    "DefaultContextPolicy",
    "MessageWindowContextPolicy",
    "ModelCompactor",
    "NativeStructuredOutputUnsupported",
    "ObservedDeltaContextEstimator",
    "PromptCacheCompactor",
    "PromptContributionAvailability",
    "PromptContributionFootprint",
    "PromptContributionKind",
    "PromptContributionManifest",
    "REQUEST_FOOTPRINT_CANONICALIZATION_VERSION",
    "REQUEST_FOOTPRINT_SCHEMA_VERSION",
    "RecentTurnsContextPolicy",
    "RequestAttachmentGroupFootprint",
    "RequestAttachmentsFootprint",
    "RequestCacheBreakpointFootprint",
    "RequestComponentFootprint",
    "RequestComponentTokenEstimates",
    "RequestContentGroupFootprint",
    "RequestFingerprint",
    "RequestFingerprintAvailability",
    "RequestFingerprintSet",
    "RequestFootprint",
    "RequestFootprintConfig",
    "RequestMessagesFootprint",
    "RequestOptionsFootprint",
    "RequestPromptContributionAttribution",
    "RequestSize",
    "RequestVariant",
    "StructuredOutputError",
    "StructuredOutputSpec",
    "StructuredOutputStrategy",
    "StructuredOutputValidation",
    "TargetedToolGrantFootprint",
    "ThinkingConfig",
    "ToolDiscoveryProjectionFootprint",
    "ToolDiscoveryViewFootprint",
    "ToolExposureFootprint",
    "TranscriptDigestCompactor",
    "UsageTriggeredContextPolicy",
    "build_prompt_contribution_manifest",
    "build_request_footprint",
    "context_input_coverage",
    "copy_context_counting_config",
    "copy_request_footprint_config",
    "default_compaction_prompt",
    "estimate_model_request_context_pressure",
    "strip_old_file_attachments",
    "targeted_tool_grant_footprint",
    "tool_discovery_view_footprint",
    "trim_context_messages",
    "trim_context_turns",
]
