"""Explicit public exports; implementations load on first access."""

EXPORTS: dict[str, tuple[str, str]] = {
    "EventStoreJournal": ("cayu.workflows.journal", "EventStoreJournal"),
    "FailureEvidence": ("cayu.failure_evidence", "FailureEvidence"),
    "GateOutcome": ("cayu.workflows.models", "GateOutcome"),
    "JournalFactory": ("cayu.workflows.workflow", "JournalFactory"),
    "ParallelResult": ("cayu.workflows.models", "ParallelResult"),
    "ParallelStepError": ("cayu.workflows.models", "ParallelStepError"),
    "StepError": ("cayu.workflows.models", "StepError"),
    "StepFailure": ("cayu.workflows.models", "StepFailure"),
    "StepResult": ("cayu.workflows.models", "StepResult"),
    "StepRunOptions": ("cayu.workflows.workflow", "StepRunOptions"),
    "WORKFLOW_ATTEMPT_EVENT_TYPE": ("cayu.workflows.base", "WORKFLOW_ATTEMPT_EVENT_TYPE"),
    "WORKFLOW_JOURNAL_MODEL": ("cayu.workflows.journal", "WORKFLOW_JOURNAL_MODEL"),
    "WORKFLOW_JOURNAL_PROVIDER": ("cayu.workflows.journal", "WORKFLOW_JOURNAL_PROVIDER"),
    "Workflow": ("cayu.workflows.base", "Workflow"),
    "WorkflowBase": ("cayu.workflows.workflow", "WorkflowBase"),
    "WorkflowContext": ("cayu.workflows.workflow", "WorkflowContext"),
    "WorkflowJournal": ("cayu.workflows.journal", "WorkflowJournal"),
    "WorkflowJournalContext": ("cayu.workflows.journal", "WorkflowJournalContext"),
    "WorkflowJournalReplayEvidence": ("cayu.workflows.journal", "WorkflowJournalReplayEvidence"),
    "WorkflowSpec": ("cayu.workflows.base", "WorkflowSpec"),
    "WorkflowStepCompletionSnapshot": ("cayu.workflows.journal", "WorkflowStepCompletionSnapshot"),
    "WorkflowSupersededError": ("cayu.workflows.workflow", "WorkflowSupersededError"),
    "canonical_workflow_step_completion_ids": (
        "cayu.workflows.journal",
        "canonical_workflow_step_completion_ids",
    ),
    "copy_workflow_step_completion_snapshot": (
        "cayu.workflows.journal",
        "copy_workflow_step_completion_snapshot",
    ),
    "gated_loop": ("cayu.workflows.workflow", "gated_loop"),
    "normalize_gate_outcome": ("cayu.workflows.models", "normalize_gate_outcome"),
    "parallel": ("cayu.workflows.workflow", "parallel"),
    "pipeline": ("cayu.workflows.workflow", "pipeline"),
    "step": ("cayu.workflows.workflow", "step"),
}

PUBLIC_NAMES = [
    "EventStoreJournal",
    "FailureEvidence",
    "GateOutcome",
    "JournalFactory",
    "ParallelResult",
    "ParallelStepError",
    "StepError",
    "StepFailure",
    "StepResult",
    "StepRunOptions",
    "WORKFLOW_ATTEMPT_EVENT_TYPE",
    "WORKFLOW_JOURNAL_MODEL",
    "WORKFLOW_JOURNAL_PROVIDER",
    "Workflow",
    "WorkflowBase",
    "WorkflowContext",
    "WorkflowJournal",
    "WorkflowJournalContext",
    "WorkflowJournalReplayEvidence",
    "WorkflowSpec",
    "WorkflowStepCompletionSnapshot",
    "WorkflowSupersededError",
    "canonical_workflow_step_completion_ids",
    "copy_workflow_step_completion_snapshot",
    "gated_loop",
    "normalize_gate_outcome",
    "parallel",
    "pipeline",
    "step",
]
