"""Fixed public classifications for opaque runner failures."""

from __future__ import annotations

_TRUSTED_RUNNER_ERROR_TYPE_NAMES = frozenset(
    {
        "ArithmeticError",
        "AssertionError",
        "AttributeError",
        "AuthenticationException",
        "BaseException",
        "BaseExceptionGroup",
        "BlockingIOError",
        "BrokenPipeError",
        "BuildException",
        "BufferError",
        "BytesWarning",
        "CancelledError",
        "ChildProcessError",
        "CloudHttpError",
        "CommandExitException",
        "ConnectionAbortedError",
        "ConnectionError",
        "ConnectionRefusedError",
        "ConnectionResetError",
        "DeprecationWarning",
        "E2BGuestHandoffError",
        "EOFError",
        "EncodingWarning",
        "Exception",
        "ExceptionGroup",
        "ExecFailedError",
        "ExecTimeoutError",
        "FileExistsError",
        "FileNotFoundException",
        "FileNotFoundError",
        "FileUploadException",
        "FilesystemError",
        "FloatingPointError",
        "FutureWarning",
        "GeneratorExit",
        "GitAuthException",
        "GitUpstreamException",
        "ImageInUseError",
        "ImageNotFoundError",
        "ImagePullFailedError",
        "ImportError",
        "ImportWarning",
        "IndentationError",
        "IndexError",
        "InvalidArgumentException",
        "InvalidConfigError",
        "InterruptedError",
        "IsADirectoryError",
        "IoError",
        "KeyError",
        "KeyboardInterrupt",
        "LambdaMicroVMEndpointUnauthorized",
        "LambdaMicroVMError",
        "LambdaMicroVMProtocolError",
        "LookupError",
        "MemoryError",
        "MetricsDisabledError",
        "MetricsUnavailableError",
        "MicrosandboxCleanupError",
        "MicrosandboxError",
        "MicrosandboxReconnectIdentityError",
        "MicrosandboxUnavailableError",
        "ModuleNotFoundError",
        "NameError",
        "NetworkPolicyError",
        "NotEnoughSpaceException",
        "NotADirectoryError",
        "NotFoundException",
        "NotImplementedError",
        "OSError",
        "OverflowError",
        "PathNotFoundError",
        "PendingDeprecationWarning",
        "PermissionError",
        "ProcessLookupError",
        "PythonFinalizationError",
        "RateLimitException",
        "RecursionError",
        "ReferenceError",
        "ResourceWarning",
        "RunnerExecutionError",
        "RunnerUnavailableError",
        "RuntimeError",
        "RuntimeWarning",
        "SandboxAlreadyExistsError",
        "SandboxException",
        "SandboxNotFoundError",
        "SandboxNotFoundException",
        "SandboxNotRunningError",
        "SandboxStillRunningError",
        "SecretViolationError",
        "StopAsyncIteration",
        "StopIteration",
        "SyntaxError",
        "SyntaxWarning",
        "SystemError",
        "SystemExit",
        "TabError",
        "TemplateException",
        "TimeoutException",
        "TimeoutError",
        "TlsError",
        "TypeError",
        "UnboundLocalError",
        "UnicodeDecodeError",
        "UnicodeEncodeError",
        "UnicodeError",
        "UnicodeTranslateError",
        "UnicodeWarning",
        "UnexpectedStatus",
        "UnsupportedError",
        "UnsupportedOperationError",
        "UserWarning",
        "ValueError",
        "VolumeException",
        "VolumeNotFoundError",
        "Warning",
        "ZeroDivisionError",
    }
)


def trusted_runner_exception_type_name(error: BaseException) -> str:
    """Return a fixed public classification for one opaque runner failure."""

    try:
        name = type.__getattribute__(type(error), "__name__")
    except BaseException:
        return "Exception"
    return trusted_runner_error_type_name(name) or "Exception"


def trusted_runner_error_type_name(value: object) -> str | None:
    """Accept only runtime-owned runner classifications, never extension text."""

    if type(value) is not str or value not in _TRUSTED_RUNNER_ERROR_TYPE_NAMES:
        return None
    return value
