"""Explicit public exports; implementations load on first access."""

EXPORTS: dict[str, tuple[str, str]] = {
    "BROWSER_FETCH_WORKLOAD_NAME": ("cayu.runners.workloads", "BROWSER_FETCH_WORKLOAD_NAME"),
    "BROWSER_SESSION_WORKLOAD_NAME": ("cayu.runners.workloads", "BROWSER_SESSION_WORKLOAD_NAME"),
    "DEFAULT_DOCKER_CWD": ("cayu.runners.docker", "DEFAULT_DOCKER_CWD"),
    "DEFAULT_DOCKER_IMAGE": ("cayu.runners.docker", "DEFAULT_DOCKER_IMAGE"),
    "DEFAULT_E2B_CWD": ("cayu.runners.e2b", "DEFAULT_E2B_CWD"),
    "DEFAULT_E2B_HANDOFF_CLEANUP_TIMEOUT_SECONDS": (
        "cayu.runners.e2b",
        "DEFAULT_E2B_HANDOFF_CLEANUP_TIMEOUT_SECONDS",
    ),
    "DEFAULT_E2B_HANDOFF_TIMEOUT_SECONDS": (
        "cayu.runners.e2b",
        "DEFAULT_E2B_HANDOFF_TIMEOUT_SECONDS",
    ),
    "DEFAULT_E2B_PROTECTED_FILE_MAX_BYTES": (
        "cayu.runners.e2b",
        "DEFAULT_E2B_PROTECTED_FILE_MAX_BYTES",
    ),
    "DEFAULT_EXEC_OUTPUT_LIMIT_BYTES": ("cayu.runners.base", "DEFAULT_EXEC_OUTPUT_LIMIT_BYTES"),
    "DEFAULT_LAMBDA_MICROVM_CWD": ("cayu.runners.aws_lambda_microvm", "DEFAULT_LAMBDA_MICROVM_CWD"),
    "DEFAULT_MICROSANDBOX_CWD": ("cayu.runners.microsandbox", "DEFAULT_MICROSANDBOX_CWD"),
    "DEFAULT_MICROSANDBOX_IMAGE": ("cayu.runners.microsandbox", "DEFAULT_MICROSANDBOX_IMAGE"),
    "DEFAULT_MICROSANDBOX_RECONNECT_TIMEOUT_SECONDS": (
        "cayu.runners.microsandbox",
        "DEFAULT_MICROSANDBOX_RECONNECT_TIMEOUT_SECONDS",
    ),
    "DEFAULT_MICROSANDBOX_REMOVE_TIMEOUT_SECONDS": (
        "cayu.runners.microsandbox",
        "DEFAULT_MICROSANDBOX_REMOVE_TIMEOUT_SECONDS",
    ),
    "DEFAULT_RUNNER_CANCELLATION_CLEANUP_POLICY": (
        "cayu.runners._cleanup",
        "DEFAULT_RUNNER_CANCELLATION_CLEANUP_POLICY",
    ),
    "DEFAULT_RUNNER_TIMEOUT_CLEANUP_POLICY": (
        "cayu.runners._cleanup",
        "DEFAULT_RUNNER_TIMEOUT_CLEANUP_POLICY",
    ),
    "DockerCloseAction": ("cayu.runners.docker", "DockerCloseAction"),
    "DockerContainerOwnershipError": ("cayu.runners.docker", "DockerContainerOwnershipError"),
    "DockerImageIdentity": ("cayu.runners.docker_workload", "DockerImageIdentity"),
    "DockerRunner": ("cayu.runners.docker", "DockerRunner"),
    "DockerRuntimeConfigurationError": ("cayu.runners.docker", "DockerRuntimeConfigurationError"),
    "DockerTmpfsMount": ("cayu.runners.docker_workload", "DockerTmpfsMount"),
    "DockerWorkloadRestrictions": ("cayu.runners.docker_workload", "DockerWorkloadRestrictions"),
    "E2BCloseAction": ("cayu.runners.e2b", "E2BCloseAction"),
    "E2BGuestHandoffError": ("cayu.runners.e2b", "E2BGuestHandoffError"),
    "E2BGuestHandoffPhase": ("cayu.runners.e2b", "E2BGuestHandoffPhase"),
    "E2BGuestProvisioner": ("cayu.runners.e2b", "E2BGuestProvisioner"),
    "E2BRunner": ("cayu.runners.e2b", "E2BRunner"),
    "E2BWorkspaceCapability": ("cayu.runners.e2b", "E2BWorkspaceCapability"),
    "E2BWorkspaceEntry": ("cayu.runners.e2b", "E2BWorkspaceEntry"),
    "E2B_SANDBOX_ID_MAX_BYTES": ("cayu.runners.e2b", "E2B_SANDBOX_ID_MAX_BYTES"),
    "ExecCommand": ("cayu.runners.base", "ExecCommand"),
    "ExecResult": ("cayu.runners.base", "ExecResult"),
    "HttpxLambdaMicroVMEndpointTransport": (
        "cayu.runners.aws_lambda_microvm",
        "HttpxLambdaMicroVMEndpointTransport",
    ),
    "LambdaMicroVMCloseAction": ("cayu.runners.aws_lambda_microvm", "LambdaMicroVMCloseAction"),
    "LambdaMicroVMEndpointTransientError": (
        "cayu.runners.aws_lambda_microvm",
        "LambdaMicroVMEndpointTransientError",
    ),
    "LambdaMicroVMEndpointTransport": (
        "cayu.runners.aws_lambda_microvm",
        "LambdaMicroVMEndpointTransport",
    ),
    "LambdaMicroVMEndpointUnauthorized": (
        "cayu.runners.aws_lambda_microvm",
        "LambdaMicroVMEndpointUnauthorized",
    ),
    "LambdaMicroVMError": ("cayu.runners.aws_lambda_microvm", "LambdaMicroVMError"),
    "LambdaMicroVMProtocolError": ("cayu.runners.aws_lambda_microvm", "LambdaMicroVMProtocolError"),
    "LambdaMicroVMRunner": ("cayu.runners.aws_lambda_microvm", "LambdaMicroVMRunner"),
    "LocalRunner": ("cayu.runners.local", "LocalRunner"),
    "MICROSANDBOX_LIVENESS_TIMEOUT_SECONDS": (
        "cayu.runners.microsandbox",
        "MICROSANDBOX_LIVENESS_TIMEOUT_SECONDS",
    ),
    "MICROSANDBOX_NAME_MAX_BYTES": ("cayu.runners.microsandbox", "MICROSANDBOX_NAME_MAX_BYTES"),
    "MicrosandboxCleanupError": ("cayu.runners.microsandbox", "MicrosandboxCleanupError"),
    "MicrosandboxCloseAction": ("cayu.runners.microsandbox", "MicrosandboxCloseAction"),
    "MicrosandboxReconnectIdentityError": (
        "cayu.runners.microsandbox",
        "MicrosandboxReconnectIdentityError",
    ),
    "MicrosandboxRunner": ("cayu.runners.microsandbox", "MicrosandboxRunner"),
    "MicrosandboxUnavailableError": ("cayu.runners.microsandbox", "MicrosandboxUnavailableError"),
    "MicrosandboxWorkspaceCapability": (
        "cayu.runners.microsandbox",
        "MicrosandboxWorkspaceCapability",
    ),
    "MicrosandboxWorkspaceEntry": ("cayu.runners.microsandbox", "MicrosandboxWorkspaceEntry"),
    "PINNED_BROWSER_FETCH_IMAGE": ("cayu.runners.workloads", "PINNED_BROWSER_FETCH_IMAGE"),
    "PINNED_BROWSER_FETCH_WORKLOAD": ("cayu.runners.workloads", "PINNED_BROWSER_FETCH_WORKLOAD"),
    "PINNED_BROWSER_SESSION_IMAGE": ("cayu.runners.workloads", "PINNED_BROWSER_SESSION_IMAGE"),
    "PINNED_BROWSER_SESSION_WORKLOAD": (
        "cayu.runners.workloads",
        "PINNED_BROWSER_SESSION_WORKLOAD",
    ),
    "RemoteWorkspaceBranchCapability": ("cayu.runners.base", "RemoteWorkspaceBranchCapability"),
    "Runner": ("cayu.runners.base", "Runner"),
    "RunnerBinaryStreamCapability": ("cayu.runners.base", "RunnerBinaryStreamCapability"),
    "RunnerCleanupPolicy": ("cayu.runners._cleanup", "RunnerCleanupPolicy"),
    "RunnerExecutionAdmissionObserver": ("cayu.runners.base", "RunnerExecutionAdmissionObserver"),
    "RunnerExecutionError": ("cayu.runners.base", "RunnerExecutionError"),
    "RunnerLifecycleState": ("cayu.runners.base", "RunnerLifecycleState"),
    "RunnerSystemExecutionMode": ("cayu.runners.base", "RunnerSystemExecutionMode"),
    "RunnerUnavailableError": ("cayu.runners.base", "RunnerUnavailableError"),
    "RunnerWorkloadAuthority": ("cayu.runners.base", "RunnerWorkloadAuthority"),
    "RunnerWorkspaceCapability": ("cayu.runners.base", "RunnerWorkspaceCapability"),
    "attach_cancellation_artifacts": ("cayu.runners.base", "attach_cancellation_artifacts"),
}

PUBLIC_NAMES = [
    "BROWSER_FETCH_WORKLOAD_NAME",
    "BROWSER_SESSION_WORKLOAD_NAME",
    "DEFAULT_DOCKER_CWD",
    "DEFAULT_DOCKER_IMAGE",
    "DEFAULT_E2B_CWD",
    "DEFAULT_E2B_HANDOFF_CLEANUP_TIMEOUT_SECONDS",
    "DEFAULT_E2B_HANDOFF_TIMEOUT_SECONDS",
    "DEFAULT_E2B_PROTECTED_FILE_MAX_BYTES",
    "DEFAULT_EXEC_OUTPUT_LIMIT_BYTES",
    "DEFAULT_LAMBDA_MICROVM_CWD",
    "DEFAULT_MICROSANDBOX_CWD",
    "DEFAULT_MICROSANDBOX_IMAGE",
    "DEFAULT_MICROSANDBOX_RECONNECT_TIMEOUT_SECONDS",
    "DEFAULT_MICROSANDBOX_REMOVE_TIMEOUT_SECONDS",
    "DEFAULT_RUNNER_CANCELLATION_CLEANUP_POLICY",
    "DEFAULT_RUNNER_TIMEOUT_CLEANUP_POLICY",
    "DockerCloseAction",
    "DockerContainerOwnershipError",
    "DockerImageIdentity",
    "DockerRunner",
    "DockerRuntimeConfigurationError",
    "DockerTmpfsMount",
    "DockerWorkloadRestrictions",
    "E2BCloseAction",
    "E2BGuestHandoffError",
    "E2BGuestHandoffPhase",
    "E2BGuestProvisioner",
    "E2BRunner",
    "E2BWorkspaceCapability",
    "E2BWorkspaceEntry",
    "E2B_SANDBOX_ID_MAX_BYTES",
    "ExecCommand",
    "ExecResult",
    "HttpxLambdaMicroVMEndpointTransport",
    "LambdaMicroVMCloseAction",
    "LambdaMicroVMEndpointTransientError",
    "LambdaMicroVMEndpointTransport",
    "LambdaMicroVMEndpointUnauthorized",
    "LambdaMicroVMError",
    "LambdaMicroVMProtocolError",
    "LambdaMicroVMRunner",
    "LocalRunner",
    "MICROSANDBOX_LIVENESS_TIMEOUT_SECONDS",
    "MICROSANDBOX_NAME_MAX_BYTES",
    "MicrosandboxCleanupError",
    "MicrosandboxCloseAction",
    "MicrosandboxReconnectIdentityError",
    "MicrosandboxRunner",
    "MicrosandboxUnavailableError",
    "MicrosandboxWorkspaceCapability",
    "MicrosandboxWorkspaceEntry",
    "PINNED_BROWSER_FETCH_IMAGE",
    "PINNED_BROWSER_FETCH_WORKLOAD",
    "PINNED_BROWSER_SESSION_IMAGE",
    "PINNED_BROWSER_SESSION_WORKLOAD",
    "RemoteWorkspaceBranchCapability",
    "Runner",
    "RunnerBinaryStreamCapability",
    "RunnerCleanupPolicy",
    "RunnerExecutionAdmissionObserver",
    "RunnerExecutionError",
    "RunnerLifecycleState",
    "RunnerSystemExecutionMode",
    "RunnerUnavailableError",
    "RunnerWorkloadAuthority",
    "RunnerWorkspaceCapability",
    "attach_cancellation_artifacts",
]
