"""Explicit public exports; implementations load on first access."""

EXPORTS: dict[str, tuple[str, str]] = {
    "BUSINESS_APPROVAL_RESOLUTION_METADATA_KEY": (
        "cayu.approvals.business",
        "BUSINESS_APPROVAL_RESOLUTION_METADATA_KEY",
    ),
    "BUSINESS_APPROVAL_ROUTING_METADATA_KEY": (
        "cayu.approvals.business",
        "BUSINESS_APPROVAL_ROUTING_METADATA_KEY",
    ),
    "BusinessApprovalError": ("cayu.approvals.business", "BusinessApprovalError"),
    "BusinessApprovalOutcome": ("cayu.approvals.business", "BusinessApprovalOutcome"),
    "BusinessApprovalRecord": ("cayu.approvals.business", "BusinessApprovalRecord"),
    "BusinessApprovalResolutionState": (
        "cayu.approvals.business",
        "BusinessApprovalResolutionState",
    ),
    "BusinessApprovalRouting": ("cayu.approvals.business", "BusinessApprovalRouting"),
    "BusinessApprovalRoutingMissing": ("cayu.approvals.business", "BusinessApprovalRoutingMissing"),
    "BusinessApprovalTierMismatch": ("cayu.approvals.business", "BusinessApprovalTierMismatch"),
    "HumanReviewCall": ("cayu.approvals.review", "HumanReviewCall"),
    "HumanReviewConflict": ("cayu.approvals.review", "HumanReviewConflict"),
    "HumanReviewContext": ("cayu.approvals.review", "HumanReviewContext"),
    "HumanReviewDenied": ("cayu.approvals.review", "HumanReviewDenied"),
    "HumanReviewDisclosure": ("cayu.approvals.review", "HumanReviewDisclosure"),
    "HumanReviewField": ("cayu.approvals.review", "HumanReviewField"),
    "HumanReviewPolicy": ("cayu.approvals.review", "HumanReviewPolicy"),
    "HumanReviewReference": ("cayu.approvals.review", "HumanReviewReference"),
    "HumanReviewSource": ("cayu.approvals.review", "HumanReviewSource"),
    "HumanReviewView": ("cayu.approvals.review", "HumanReviewView"),
    "PendingToolApproval": ("cayu.approvals.tools", "PendingToolApproval"),
    "PendingToolApprovalEventView": ("cayu.approvals.tools", "PendingToolApprovalEventView"),
    "PendingToolCallApproval": ("cayu.approvals.tools", "PendingToolCallApproval"),
    "PendingToolCallApprovalEventView": (
        "cayu.approvals.tools",
        "PendingToolCallApprovalEventView",
    ),
    "PendingUserInput": ("cayu.approvals.user_input", "PendingUserInput"),
    "ResolutionActor": ("cayu.approvals.tools", "ResolutionActor"),
    "ResolutionActorSource": ("cayu.approvals.tools", "ResolutionActorSource"),
    "TieredApprovalPolicy": ("cayu.approvals.business", "TieredApprovalPolicy"),
    "ToolApprovalDecision": ("cayu.approvals.tools", "ToolApprovalDecision"),
    "ToolApprovalRecoveryOutcome": ("cayu.approvals.tools", "ToolApprovalRecoveryOutcome"),
    "ToolApprovalRecoveryRequest": ("cayu.approvals.tools", "ToolApprovalRecoveryRequest"),
    "ToolApprovalRequest": ("cayu.approvals.tools", "ToolApprovalRequest"),
    "ToolPolicyEvidence": ("cayu.approvals.tools", "ToolPolicyEvidence"),
    "UserInputRecoveryRequest": ("cayu.approvals.user_input", "UserInputRecoveryRequest"),
    "UserInputResponse": ("cayu.approvals.user_input", "UserInputResponse"),
    "business_approval_audit": ("cayu.approvals.business", "business_approval_audit"),
    "business_approval_routing": ("cayu.approvals.business", "business_approval_routing"),
    "business_approval_routing_metadata": (
        "cayu.approvals.business",
        "business_approval_routing_metadata",
    ),
    "resolve_business_approval": ("cayu.approvals.business", "resolve_business_approval"),
}

PUBLIC_NAMES = [
    "BUSINESS_APPROVAL_RESOLUTION_METADATA_KEY",
    "BUSINESS_APPROVAL_ROUTING_METADATA_KEY",
    "BusinessApprovalError",
    "BusinessApprovalOutcome",
    "BusinessApprovalRecord",
    "BusinessApprovalResolutionState",
    "BusinessApprovalRouting",
    "BusinessApprovalRoutingMissing",
    "BusinessApprovalTierMismatch",
    "HumanReviewCall",
    "HumanReviewConflict",
    "HumanReviewContext",
    "HumanReviewDenied",
    "HumanReviewDisclosure",
    "HumanReviewField",
    "HumanReviewPolicy",
    "HumanReviewReference",
    "HumanReviewSource",
    "HumanReviewView",
    "PendingToolApproval",
    "PendingToolApprovalEventView",
    "PendingToolCallApproval",
    "PendingToolCallApprovalEventView",
    "PendingUserInput",
    "ResolutionActor",
    "ResolutionActorSource",
    "TieredApprovalPolicy",
    "ToolApprovalDecision",
    "ToolApprovalRecoveryOutcome",
    "ToolApprovalRecoveryRequest",
    "ToolApprovalRequest",
    "ToolPolicyEvidence",
    "UserInputRecoveryRequest",
    "UserInputResponse",
    "business_approval_audit",
    "business_approval_routing",
    "business_approval_routing_metadata",
    "resolve_business_approval",
]
