"""Explicit public exports; implementations load on first access."""

EXPORTS: dict[str, tuple[str, str]] = {
    "GITHUB_DELIVERY_RESULT_KIND": ("cayu.delivery.github", "GITHUB_DELIVERY_RESULT_KIND"),
    "GITHUB_DELIVERY_SCHEMA_VERSION": ("cayu.delivery.github", "GITHUB_DELIVERY_SCHEMA_VERSION"),
    "GitHubCheckBundle": ("cayu.delivery.github", "GitHubCheckBundle"),
    "GitHubCheckObservation": ("cayu.delivery.github", "GitHubCheckObservation"),
    "GitHubCheckPolicy": ("cayu.delivery.github", "GitHubCheckPolicy"),
    "GitHubCheckState": ("cayu.delivery.github", "GitHubCheckState"),
    "GitHubConnectorProfile": ("cayu.delivery.github", "GitHubConnectorProfile"),
    "GitHubConnectorTransport": ("cayu.delivery.github", "GitHubConnectorTransport"),
    "GitHubCredentials": ("cayu.delivery.github", "GitHubCredentials"),
    "GitHubDeliveryAdmissionError": ("cayu.delivery.github", "GitHubDeliveryAdmissionError"),
    "GitHubDeliveryApproval": ("cayu.delivery.github", "GitHubDeliveryApproval"),
    "GitHubDeliveryError": ("cayu.delivery.github", "GitHubDeliveryError"),
    "GitHubDeliveryLimits": ("cayu.delivery.github", "GitHubDeliveryLimits"),
    "GitHubDeliveryPublication": ("cayu.delivery.github", "GitHubDeliveryPublication"),
    "GitHubDeliveryReconstructionRequiredError": (
        "cayu.delivery.github",
        "GitHubDeliveryReconstructionRequiredError",
    ),
    "GitHubDeliveryRepository": ("cayu.delivery.github", "GitHubDeliveryRepository"),
    "GitHubDeliveryResult": ("cayu.delivery.github", "GitHubDeliveryResult"),
    "GitHubDeliveryState": ("cayu.delivery.github", "GitHubDeliveryState"),
    "GitHubFeedbackObservation": ("cayu.delivery.github", "GitHubFeedbackObservation"),
    "GitHubFollowUpCodingInput": ("cayu.delivery.github", "GitHubFollowUpCodingInput"),
    "GitHubLifecycleReceipt": ("cayu.delivery.github", "GitHubLifecycleReceipt"),
    "GitHubOperation": ("cayu.delivery.github", "GitHubOperation"),
    "GitHubOperationEvidence": ("cayu.delivery.github", "GitHubOperationEvidence"),
    "GitHubProviderError": ("cayu.delivery.github", "GitHubProviderError"),
    "GitHubPullRequestConnector": ("cayu.delivery.github", "GitHubPullRequestConnector"),
    "GitHubPullRequestDeliveryRequest": (
        "cayu.delivery.github",
        "GitHubPullRequestDeliveryRequest",
    ),
    "GitHubPullRequestMetadata": ("cayu.delivery.github", "GitHubPullRequestMetadata"),
    "GitHubPullRequestSnapshot": ("cayu.delivery.github", "GitHubPullRequestSnapshot"),
    "GitHubRepositoryAuthority": ("cayu.delivery.github", "GitHubRepositoryAuthority"),
    "GitHubRepositoryConfig": ("cayu.delivery.github", "GitHubRepositoryConfig"),
    "GitHubRestTransport": ("cayu.delivery.github", "GitHubRestTransport"),
    "GitHubReviewBundle": ("cayu.delivery.github", "GitHubReviewBundle"),
    "GitHubReviewPolicy": ("cayu.delivery.github", "GitHubReviewPolicy"),
    "GitHubReviewState": ("cayu.delivery.github", "GitHubReviewState"),
    "GitHubSecurityAuthority": ("cayu.delivery.github", "GitHubSecurityAuthority"),
    "GitHubSourceAuthority": ("cayu.delivery.github", "GitHubSourceAuthority"),
    "REMOTE_GIT_DELIVERY_RESULT_KIND": ("cayu.delivery.git", "REMOTE_GIT_DELIVERY_RESULT_KIND"),
    "REMOTE_GIT_DELIVERY_SCHEMA_VERSION": (
        "cayu.delivery.git",
        "REMOTE_GIT_DELIVERY_SCHEMA_VERSION",
    ),
    "RemoteGitBrokerProfile": ("cayu.delivery.git", "RemoteGitBrokerProfile"),
    "RemoteGitCommitAuthority": ("cayu.delivery.git", "RemoteGitCommitAuthority"),
    "RemoteGitDeliveryAdmissionError": ("cayu.delivery.git", "RemoteGitDeliveryAdmissionError"),
    "RemoteGitDeliveryApproval": ("cayu.delivery.git", "RemoteGitDeliveryApproval"),
    "RemoteGitDeliveryBroker": ("cayu.delivery.git", "RemoteGitDeliveryBroker"),
    "RemoteGitDeliveryConflictError": ("cayu.delivery.git", "RemoteGitDeliveryConflictError"),
    "RemoteGitDeliveryError": ("cayu.delivery.git", "RemoteGitDeliveryError"),
    "RemoteGitDeliveryLimits": ("cayu.delivery.git", "RemoteGitDeliveryLimits"),
    "RemoteGitDeliveryPublication": ("cayu.delivery.git", "RemoteGitDeliveryPublication"),
    "RemoteGitDeliveryReconstructionRequiredError": (
        "cayu.delivery.git",
        "RemoteGitDeliveryReconstructionRequiredError",
    ),
    "RemoteGitDeliveryRepository": ("cayu.delivery.git", "RemoteGitDeliveryRepository"),
    "RemoteGitDeliveryRequest": ("cayu.delivery.git", "RemoteGitDeliveryRequest"),
    "RemoteGitDeliveryResult": ("cayu.delivery.git", "RemoteGitDeliveryResult"),
    "RemoteGitDeliveryState": ("cayu.delivery.git", "RemoteGitDeliveryState"),
    "RemoteGitHttpCredentials": ("cayu.delivery.git", "RemoteGitHttpCredentials"),
    "RemoteGitLifecycleReceipt": ("cayu.delivery.git", "RemoteGitLifecycleReceipt"),
    "RemoteGitPreparedIntent": ("cayu.delivery.git", "RemoteGitPreparedIntent"),
    "RemoteGitRemoteConfig": ("cayu.delivery.git", "RemoteGitRemoteConfig"),
    "RemoteGitRepositoryAuthority": ("cayu.delivery.git", "RemoteGitRepositoryAuthority"),
    "RemoteGitSecurityAuthority": ("cayu.delivery.git", "RemoteGitSecurityAuthority"),
    "RemoteGitSourceAuthority": ("cayu.delivery.git", "RemoteGitSourceAuthority"),
    "RemoteGitStepEvidence": ("cayu.delivery.git", "RemoteGitStepEvidence"),
    "approve_github_delivery": ("cayu.delivery.github", "approve_github_delivery"),
    "approve_remote_git_delivery": ("cayu.delivery.git", "approve_remote_git_delivery"),
    "github_connector_behavior_fingerprint": (
        "cayu.delivery.github",
        "github_connector_behavior_fingerprint",
    ),
    "github_follow_up_coding_input": ("cayu.delivery.github", "github_follow_up_coding_input"),
    "github_pull_request_delivery_request": (
        "cayu.delivery.github",
        "github_pull_request_delivery_request",
    ),
    "remote_git_broker_behavior_fingerprint": (
        "cayu.delivery.git",
        "remote_git_broker_behavior_fingerprint",
    ),
    "remote_git_delivery_request": ("cayu.delivery.git", "remote_git_delivery_request"),
}

PUBLIC_NAMES = [
    "GITHUB_DELIVERY_RESULT_KIND",
    "GITHUB_DELIVERY_SCHEMA_VERSION",
    "GitHubCheckBundle",
    "GitHubCheckObservation",
    "GitHubCheckPolicy",
    "GitHubCheckState",
    "GitHubConnectorProfile",
    "GitHubConnectorTransport",
    "GitHubCredentials",
    "GitHubDeliveryAdmissionError",
    "GitHubDeliveryApproval",
    "GitHubDeliveryError",
    "GitHubDeliveryLimits",
    "GitHubDeliveryPublication",
    "GitHubDeliveryReconstructionRequiredError",
    "GitHubDeliveryRepository",
    "GitHubDeliveryResult",
    "GitHubDeliveryState",
    "GitHubFeedbackObservation",
    "GitHubFollowUpCodingInput",
    "GitHubLifecycleReceipt",
    "GitHubOperation",
    "GitHubOperationEvidence",
    "GitHubProviderError",
    "GitHubPullRequestConnector",
    "GitHubPullRequestDeliveryRequest",
    "GitHubPullRequestMetadata",
    "GitHubPullRequestSnapshot",
    "GitHubRepositoryAuthority",
    "GitHubRepositoryConfig",
    "GitHubRestTransport",
    "GitHubReviewBundle",
    "GitHubReviewPolicy",
    "GitHubReviewState",
    "GitHubSecurityAuthority",
    "GitHubSourceAuthority",
    "REMOTE_GIT_DELIVERY_RESULT_KIND",
    "REMOTE_GIT_DELIVERY_SCHEMA_VERSION",
    "RemoteGitBrokerProfile",
    "RemoteGitCommitAuthority",
    "RemoteGitDeliveryAdmissionError",
    "RemoteGitDeliveryApproval",
    "RemoteGitDeliveryBroker",
    "RemoteGitDeliveryConflictError",
    "RemoteGitDeliveryError",
    "RemoteGitDeliveryLimits",
    "RemoteGitDeliveryPublication",
    "RemoteGitDeliveryReconstructionRequiredError",
    "RemoteGitDeliveryRepository",
    "RemoteGitDeliveryRequest",
    "RemoteGitDeliveryResult",
    "RemoteGitDeliveryState",
    "RemoteGitHttpCredentials",
    "RemoteGitLifecycleReceipt",
    "RemoteGitPreparedIntent",
    "RemoteGitRemoteConfig",
    "RemoteGitRepositoryAuthority",
    "RemoteGitSecurityAuthority",
    "RemoteGitSourceAuthority",
    "RemoteGitStepEvidence",
    "approve_github_delivery",
    "approve_remote_git_delivery",
    "github_connector_behavior_fingerprint",
    "github_follow_up_coding_input",
    "github_pull_request_delivery_request",
    "remote_git_broker_behavior_fingerprint",
    "remote_git_delivery_request",
]
