"""Explicit public exports; implementations load on first access."""

EXPORTS: dict[str, tuple[str, str]] = {
    "ArtifactClosureClaim": ("cayu.artifacts._closure", "ArtifactClosureClaim"),
    "ArtifactClosureItem": ("cayu.artifacts._closure", "ArtifactClosureItem"),
    "copy_artifact_closure_claim": ("cayu.artifacts._closure", "copy_artifact_closure_claim"),
    "ArtifactListResult": ("cayu.artifacts.base", "ArtifactListResult"),
    "ArtifactMetadata": ("cayu.artifacts.base", "ArtifactMetadata"),
    "ArtifactReadResult": ("cayu.artifacts.base", "ArtifactReadResult"),
    "ArtifactScope": ("cayu.artifacts.base", "ArtifactScope"),
    "ArtifactStore": ("cayu.artifacts.base", "ArtifactStore"),
    "ArtifactStoreUnavailableError": ("cayu.artifacts.base", "ArtifactStoreUnavailableError"),
    "ArtifactToWorkspaceResult": ("cayu.artifacts.workspace", "ArtifactToWorkspaceResult"),
    "ArtifactWriteSettlementEvidence": (
        "cayu.artifacts.settlement",
        "ArtifactWriteSettlementEvidence",
    ),
    "ArtifactWriteSettlementFailureCode": (
        "cayu.artifacts.settlement",
        "ArtifactWriteSettlementFailureCode",
    ),
    "ArtifactWriteSettlementObservation": (
        "cayu.artifacts.settlement",
        "ArtifactWriteSettlementObservation",
    ),
    "ArtifactWriteSettlementObserver": (
        "cayu.artifacts.settlement",
        "ArtifactWriteSettlementObserver",
    ),
    "ArtifactWriteSettlementPhase": ("cayu.artifacts.settlement", "ArtifactWriteSettlementPhase"),
    "ArtifactWriteSettlementRegistration": (
        "cayu.artifacts.settlement",
        "ArtifactWriteSettlementRegistration",
    ),
    "ArtifactWriteSettlementStatus": ("cayu.artifacts.settlement", "ArtifactWriteSettlementStatus"),
    "DEFAULT_ARTIFACT_WORKSPACE_COPY_LIMIT_BYTES": (
        "cayu.artifacts.workspace",
        "DEFAULT_ARTIFACT_WORKSPACE_COPY_LIMIT_BYTES",
    ),
    "DEFAULT_MAX_FILE_ATTACHMENTS_PER_REQUEST": (
        "cayu.artifacts.attachments",
        "DEFAULT_MAX_FILE_ATTACHMENTS_PER_REQUEST",
    ),
    "DEFAULT_MAX_FILE_ATTACHMENT_BYTES": (
        "cayu.artifacts.attachments",
        "DEFAULT_MAX_FILE_ATTACHMENT_BYTES",
    ),
    "DEFAULT_MAX_TOTAL_FILE_ATTACHMENT_BYTES": (
        "cayu.artifacts.attachments",
        "DEFAULT_MAX_TOTAL_FILE_ATTACHMENT_BYTES",
    ),
    "FILE_ATTACHMENT_DOCUMENT_CONTENT_TYPES": (
        "cayu.artifacts.attachments",
        "FILE_ATTACHMENT_DOCUMENT_CONTENT_TYPES",
    ),
    "FILE_ATTACHMENT_IMAGE_CONTENT_TYPES": (
        "cayu.artifacts.attachments",
        "FILE_ATTACHMENT_IMAGE_CONTENT_TYPES",
    ),
    "FILE_ATTACHMENT_TYPE": ("cayu.artifacts.attachments", "FILE_ATTACHMENT_TYPE"),
    "FileAttachment": ("cayu.artifacts.attachments", "FileAttachment"),
    "FileAttachmentKind": ("cayu.artifacts.attachments", "FileAttachmentKind"),
    "InvalidArtifactIdError": ("cayu.artifacts.base", "InvalidArtifactIdError"),
    "LocalArtifactStore": ("cayu.artifacts.local", "LocalArtifactStore"),
    "RESOLVED_FILE_ATTACHMENTS_OPTION": (
        "cayu.artifacts.attachments",
        "RESOLVED_FILE_ATTACHMENTS_OPTION",
    ),
    "ResolvedFileAttachment": ("cayu.artifacts.attachments", "ResolvedFileAttachment"),
    "S3ArtifactStore": ("cayu.artifacts.aws_s3", "S3ArtifactStore"),
    "WorkspaceToArtifactResult": ("cayu.artifacts.workspace", "WorkspaceToArtifactResult"),
    "artifact_store_identity_sha256": (
        "cayu.artifacts.settlement",
        "artifact_store_identity_sha256",
    ),
    "artifact_write_settlements": ("cayu.artifacts.settlement", "artifact_write_settlements"),
    "copy_artifact_read_result": ("cayu.artifacts.base", "copy_artifact_read_result"),
    "copy_artifact_to_workspace": ("cayu.artifacts.workspace", "copy_artifact_to_workspace"),
    "copy_artifact_write_settlement": (
        "cayu.artifacts.settlement",
        "copy_artifact_write_settlement",
    ),
    "copy_workspace_file_to_artifact": (
        "cayu.artifacts.workspace",
        "copy_workspace_file_to_artifact",
    ),
    "file_attachment": ("cayu.artifacts.attachments", "file_attachment"),
    "file_attachment_from_payload": ("cayu.artifacts.attachments", "file_attachment_from_payload"),
    "record_artifact_write_settlement": (
        "cayu.artifacts.settlement",
        "record_artifact_write_settlement",
    ),
    "register_artifact_write_operation": (
        "cayu.artifacts.settlement",
        "register_artifact_write_operation",
    ),
    "resolved_file_attachment": ("cayu.artifacts.attachments", "resolved_file_attachment"),
    "resolved_file_attachments_from_options": (
        "cayu.artifacts.attachments",
        "resolved_file_attachments_from_options",
    ),
    "validate_file_attachment_bytes": (
        "cayu.artifacts.attachments",
        "validate_file_attachment_bytes",
    ),
    "validate_file_attachment_content_type": (
        "cayu.artifacts.attachments",
        "validate_file_attachment_content_type",
    ),
}

PUBLIC_NAMES = [
    "ArtifactClosureClaim",
    "ArtifactClosureItem",
    "copy_artifact_closure_claim",
    "ArtifactListResult",
    "ArtifactMetadata",
    "ArtifactReadResult",
    "ArtifactScope",
    "ArtifactStore",
    "ArtifactStoreUnavailableError",
    "ArtifactToWorkspaceResult",
    "ArtifactWriteSettlementEvidence",
    "ArtifactWriteSettlementFailureCode",
    "ArtifactWriteSettlementObservation",
    "ArtifactWriteSettlementObserver",
    "ArtifactWriteSettlementPhase",
    "ArtifactWriteSettlementRegistration",
    "ArtifactWriteSettlementStatus",
    "DEFAULT_ARTIFACT_WORKSPACE_COPY_LIMIT_BYTES",
    "DEFAULT_MAX_FILE_ATTACHMENTS_PER_REQUEST",
    "DEFAULT_MAX_FILE_ATTACHMENT_BYTES",
    "DEFAULT_MAX_TOTAL_FILE_ATTACHMENT_BYTES",
    "FILE_ATTACHMENT_DOCUMENT_CONTENT_TYPES",
    "FILE_ATTACHMENT_IMAGE_CONTENT_TYPES",
    "FILE_ATTACHMENT_TYPE",
    "FileAttachment",
    "FileAttachmentKind",
    "InvalidArtifactIdError",
    "LocalArtifactStore",
    "RESOLVED_FILE_ATTACHMENTS_OPTION",
    "ResolvedFileAttachment",
    "S3ArtifactStore",
    "WorkspaceToArtifactResult",
    "artifact_store_identity_sha256",
    "artifact_write_settlements",
    "copy_artifact_read_result",
    "copy_artifact_to_workspace",
    "copy_artifact_write_settlement",
    "copy_workspace_file_to_artifact",
    "file_attachment",
    "file_attachment_from_payload",
    "record_artifact_write_settlement",
    "register_artifact_write_operation",
    "resolved_file_attachment",
    "resolved_file_attachments_from_options",
    "validate_file_attachment_bytes",
    "validate_file_attachment_content_type",
]
