"""Explicit public exports; implementations load on first access."""

EXPORTS: dict[str, tuple[str, str]] = {
    "ChainVault": ("cayu.vaults.composite", "ChainVault"),
    "LocalEnvVault": ("cayu.vaults.local_env", "LocalEnvVault"),
    "REDACTED_SECRET": ("cayu.vaults.redaction", "REDACTED_SECRET"),
    "ResolvedSecret": ("cayu.vaults.base", "ResolvedSecret"),
    "RoutedVault": ("cayu.vaults.composite", "RoutedVault"),
    "SecretEnv": ("cayu.vaults.base", "SecretEnv"),
    "SecretNotFound": ("cayu.vaults.base", "SecretNotFound"),
    "SecretRedactionCapacityError": ("cayu.vaults.redaction", "SecretRedactionCapacityError"),
    "SecretRedactionStream": ("cayu.vaults.redaction", "SecretRedactionStream"),
    "SecretRedactionTail": ("cayu.vaults.redaction", "SecretRedactionTail"),
    "SecretRedactor": ("cayu.vaults.redaction", "SecretRedactor"),
    "SecretRef": ("cayu.vaults.base", "SecretRef"),
    "SecretResolver": ("cayu.vaults.base", "SecretResolver"),
    "SecretsManagerVault": ("cayu.vaults.aws_secrets_manager", "SecretsManagerVault"),
    "StaticVault": ("cayu.vaults.static", "StaticVault"),
    "Vault": ("cayu.vaults.base", "Vault"),
    "VaultError": ("cayu.vaults.base", "VaultError"),
    "contains_redacted_secret": ("cayu.vaults.redaction", "contains_redacted_secret"),
    "copy_resolved_secret": ("cayu.vaults.base", "copy_resolved_secret"),
    "copy_secret_env": ("cayu.vaults.base", "copy_secret_env"),
    "copy_secret_ref": ("cayu.vaults.base", "copy_secret_ref"),
    "resolve_secret_env": ("cayu.vaults.base", "resolve_secret_env"),
    "secret_env_refs": ("cayu.vaults.base", "secret_env_refs"),
    "validate_secret_resolver": ("cayu.vaults.base", "validate_secret_resolver"),
}

PUBLIC_NAMES = [
    "ChainVault",
    "LocalEnvVault",
    "REDACTED_SECRET",
    "ResolvedSecret",
    "RoutedVault",
    "SecretEnv",
    "SecretNotFound",
    "SecretRedactionCapacityError",
    "SecretRedactionStream",
    "SecretRedactionTail",
    "SecretRedactor",
    "SecretRef",
    "SecretResolver",
    "SecretsManagerVault",
    "StaticVault",
    "Vault",
    "VaultError",
    "contains_redacted_secret",
    "copy_resolved_secret",
    "copy_secret_env",
    "copy_secret_ref",
    "resolve_secret_env",
    "secret_env_refs",
    "validate_secret_resolver",
]
