"""Explicit public exports; implementations load on first access."""

EXPORTS: dict[str, tuple[str, str]] = {
    "BoundWorkspace": ("cayu.environments.bindings", "BoundWorkspace"),
    "DEFAULT_ENVIRONMENT_FACTORY_RELEASE_TIMEOUT_SECONDS": (
        "cayu.environments.factory",
        "DEFAULT_ENVIRONMENT_FACTORY_RELEASE_TIMEOUT_SECONDS",
    ),
    "DEFAULT_ENVIRONMENT_LIFECYCLE_TIMEOUT_SECONDS": (
        "cayu.environments.lifecycle",
        "DEFAULT_ENVIRONMENT_LIFECYCLE_TIMEOUT_SECONDS",
    ),
    "DEFAULT_ENVIRONMENT_PHASE_TIMEOUT_SECONDS": (
        "cayu.environments.lifecycle",
        "DEFAULT_ENVIRONMENT_PHASE_TIMEOUT_SECONDS",
    ),
    "DEFAULT_ENVIRONMENT_PROGRESS_MIN_INTERVAL_SECONDS": (
        "cayu.environments.lifecycle",
        "DEFAULT_ENVIRONMENT_PROGRESS_MIN_INTERVAL_SECONDS",
    ),
    "DEFAULT_IMMUTABLE_INPUT_MAX_FILES": (
        "cayu.immutable_inputs",
        "DEFAULT_IMMUTABLE_INPUT_MAX_FILES",
    ),
    "DEFAULT_IMMUTABLE_INPUT_MAX_FILE_BYTES": (
        "cayu.immutable_inputs",
        "DEFAULT_IMMUTABLE_INPUT_MAX_FILE_BYTES",
    ),
    "DEFAULT_IMMUTABLE_INPUT_MAX_TOTAL_BYTES": (
        "cayu.immutable_inputs",
        "DEFAULT_IMMUTABLE_INPUT_MAX_TOTAL_BYTES",
    ),
    "DEFAULT_MAX_ENVIRONMENT_PROGRESS_EVENTS": (
        "cayu.environments.lifecycle",
        "DEFAULT_MAX_ENVIRONMENT_PROGRESS_EVENTS",
    ),
    "DEFAULT_SYNC_BINDING_STAGING_CAPACITY": (
        "cayu.environments._sync_staging",
        "DEFAULT_SYNC_BINDING_STAGING_CAPACITY",
    ),
    "DEFAULT_SYNC_STAGING_MAX_BYTES": (
        "cayu.environments._sync_staging",
        "DEFAULT_SYNC_STAGING_MAX_BYTES",
    ),
    "DEFAULT_SYNC_STAGING_MAX_CONCURRENCY": (
        "cayu.environments._sync_staging",
        "DEFAULT_SYNC_STAGING_MAX_CONCURRENCY",
    ),
    "DEFAULT_WORKSPACE_INSTRUCTIONS_MAX_BYTES": (
        "cayu.environments.base",
        "DEFAULT_WORKSPACE_INSTRUCTIONS_MAX_BYTES",
    ),
    "DEFAULT_WORKSPACE_INSTRUCTION_PATHS": (
        "cayu.environments.base",
        "DEFAULT_WORKSPACE_INSTRUCTION_PATHS",
    ),
    "DOCKER_CODING_COMMAND_AUTHORITY_SCHEMA": (
        "cayu.environments.docker_toolchains",
        "DOCKER_CODING_COMMAND_AUTHORITY_SCHEMA",
    ),
    "DOCKER_CODING_PROTECTED_DIRECTORY_NAMES": (
        "cayu.environments.docker_coding",
        "DOCKER_CODING_PROTECTED_DIRECTORY_NAMES",
    ),
    "DOCKER_CODING_TOOLCHAIN_PROFILE_SCHEMA": (
        "cayu.environments.docker_toolchains",
        "DOCKER_CODING_TOOLCHAIN_PROFILE_SCHEMA",
    ),
    "DeterministicWorkspaceBinding": (
        "cayu.environments.bindings",
        "DeterministicWorkspaceBinding",
    ),
    "DockerCodingAdmissionProbe": (
        "cayu.environments.docker_toolchains",
        "DockerCodingAdmissionProbe",
    ),
    "DockerCodingCommandAuthority": (
        "cayu.environments.docker_toolchains",
        "DockerCodingCommandAuthority",
    ),
    "DockerCodingDependencyInput": (
        "cayu.environments.docker_toolchains",
        "DockerCodingDependencyInput",
    ),
    "DockerCodingEnvironmentFactory": (
        "cayu.environments.docker_coding",
        "DockerCodingEnvironmentFactory",
    ),
    "DockerCodingFixedEnvironmentVariable": (
        "cayu.environments.docker_toolchains",
        "DockerCodingFixedEnvironmentVariable",
    ),
    "DockerCodingToolchainError": (
        "cayu.environments.docker_toolchains",
        "DockerCodingToolchainError",
    ),
    "DockerCodingToolchainProfile": (
        "cayu.environments.docker_toolchains",
        "DockerCodingToolchainProfile",
    ),
    "DockerCodingWorkspaceBinding": (
        "cayu.environments.docker_coding",
        "DockerCodingWorkspaceBinding",
    ),
    "DockerImmutableInputMount": ("cayu.immutable_inputs", "DockerImmutableInputMount"),
    "DockerWorkspaceTransferLimits": (
        "cayu.environments.docker_coding",
        "DockerWorkspaceTransferLimits",
    ),
    "EFSAccessPointBinding": ("cayu.environments.aws_filesystems", "EFSAccessPointBinding"),
    "ENVIRONMENT_ALLOCATION_INTENT_SCHEMA_VERSION": (
        "cayu.environments.factory",
        "ENVIRONMENT_ALLOCATION_INTENT_SCHEMA_VERSION",
    ),
    "ENVIRONMENT_LIFECYCLE_PROGRESS_SCHEMA_VERSION": (
        "cayu.environments.lifecycle",
        "ENVIRONMENT_LIFECYCLE_PROGRESS_SCHEMA_VERSION",
    ),
    "ENVIRONMENT_LIFECYCLE_TRANSITION_SCHEMA_VERSION": (
        "cayu.environments.lifecycle",
        "ENVIRONMENT_LIFECYCLE_TRANSITION_SCHEMA_VERSION",
    ),
    "EXECUTION_CAPABILITY_EVIDENCE_SCHEMA": (
        "cayu.environments.admission",
        "EXECUTION_CAPABILITY_EVIDENCE_SCHEMA",
    ),
    "EXECUTION_LIVE_EVIDENCE_MAX_TTL_SECONDS": (
        "cayu.environments.admission",
        "EXECUTION_LIVE_EVIDENCE_MAX_TTL_SECONDS",
    ),
    "EXECUTION_TOOL_REQUIREMENT_EVIDENCE_SCHEMA": (
        "cayu.environments.admission",
        "EXECUTION_TOOL_REQUIREMENT_EVIDENCE_SCHEMA",
    ),
    "Environment": ("cayu.environments.base", "Environment"),
    "EnvironmentAllocationContext": ("cayu.environments.factory", "EnvironmentAllocationContext"),
    "EnvironmentAllocationIntent": ("cayu.environments.factory", "EnvironmentAllocationIntent"),
    "EnvironmentAllocationScope": ("cayu.environments.factory", "EnvironmentAllocationScope"),
    "EnvironmentAllocationState": ("cayu.environments.factory", "EnvironmentAllocationState"),
    "EnvironmentAllocationUnsupportedError": (
        "cayu.environments.factory",
        "EnvironmentAllocationUnsupportedError",
    ),
    "EnvironmentFactory": ("cayu.environments.factory", "EnvironmentFactory"),
    "EnvironmentFactoryOperation": ("cayu.environments.factory", "EnvironmentFactoryOperation"),
    "EnvironmentFactoryRelease": ("cayu.environments.factory", "EnvironmentFactoryRelease"),
    "EnvironmentFactoryReleaseAction": (
        "cayu.environments.factory",
        "EnvironmentFactoryReleaseAction",
    ),
    "EnvironmentFactoryRequest": ("cayu.environments.factory", "EnvironmentFactoryRequest"),
    "EnvironmentFactoryResult": ("cayu.environments.factory", "EnvironmentFactoryResult"),
    "EnvironmentLifecycleDeadlineExceeded": (
        "cayu.environments.lifecycle",
        "EnvironmentLifecycleDeadlineExceeded",
    ),
    "EnvironmentLifecycleOperation": (
        "cayu.environments.lifecycle",
        "EnvironmentLifecycleOperation",
    ),
    "EnvironmentLifecyclePhase": ("cayu.environments.lifecycle", "EnvironmentLifecyclePhase"),
    "EnvironmentLifecyclePolicy": ("cayu.environments.lifecycle", "EnvironmentLifecyclePolicy"),
    "EnvironmentLifecycleProgress": ("cayu.environments.lifecycle", "EnvironmentLifecycleProgress"),
    "EnvironmentLifecycleProgressReporter": (
        "cayu.environments.lifecycle",
        "EnvironmentLifecycleProgressReporter",
    ),
    "EnvironmentLifecycleProgressStatus": (
        "cayu.environments.lifecycle",
        "EnvironmentLifecycleProgressStatus",
    ),
    "EnvironmentLifecycleTransition": (
        "cayu.environments.lifecycle",
        "EnvironmentLifecycleTransition",
    ),
    "EnvironmentLifecycleTransitionOutcome": (
        "cayu.environments.lifecycle",
        "EnvironmentLifecycleTransitionOutcome",
    ),
    "EnvironmentLifecycleTransitionPhase": (
        "cayu.environments.lifecycle",
        "EnvironmentLifecycleTransitionPhase",
    ),
    "EnvironmentSpec": ("cayu.environments.base", "EnvironmentSpec"),
    "ExecutionAdmissionCandidate": ("cayu.environments.admission", "ExecutionAdmissionCandidate"),
    "ExecutionAdmissionDecision": ("cayu.environments.admission", "ExecutionAdmissionDecision"),
    "ExecutionAdmissionError": ("cayu.environments.admission", "ExecutionAdmissionError"),
    "ExecutionAdmissionRefusal": ("cayu.environments.admission", "ExecutionAdmissionRefusal"),
    "ExecutionCapabilityClaim": ("cayu.environments.admission", "ExecutionCapabilityClaim"),
    "ExecutionCapabilityEvidence": ("cayu.environments.admission", "ExecutionCapabilityEvidence"),
    "ExecutionEnvironmentAuthority": (
        "cayu.environments.admission",
        "ExecutionEnvironmentAuthority",
    ),
    "ExecutionEvidenceOverride": ("cayu.environments.admission", "ExecutionEvidenceOverride"),
    "ExecutionExecutableEvidence": ("cayu.environments.admission", "ExecutionExecutableEvidence"),
    "ExecutionRequirements": ("cayu.environments.admission", "ExecutionRequirements"),
    "ExecutionToolRequirement": ("cayu.environments.admission", "ExecutionToolRequirement"),
    "ExecutionToolRequirementEvidence": (
        "cayu.environments.admission",
        "ExecutionToolRequirementEvidence",
    ),
    "GitRepositoryBinding": ("cayu.environments.bindings", "GitRepositoryBinding"),
    "IMMUTABLE_INPUT_FORMAT_VERSION": ("cayu.immutable_inputs", "IMMUTABLE_INPUT_FORMAT_VERSION"),
    "ImmutableInputAdapterCapability": ("cayu.immutable_inputs", "ImmutableInputAdapterCapability"),
    "ImmutableInputAttachment": ("cayu.immutable_inputs", "ImmutableInputAttachment"),
    "ImmutableInputAttachmentStateError": (
        "cayu.immutable_inputs",
        "ImmutableInputAttachmentStateError",
    ),
    "ImmutableInputDiagnostic": ("cayu.immutable_inputs", "ImmutableInputDiagnostic"),
    "ImmutableInputMutationError": ("cayu.immutable_inputs", "ImmutableInputMutationError"),
    "ImmutableInputProjection": ("cayu.immutable_inputs", "ImmutableInputProjection"),
    "ImmutableInputProjectionCapability": (
        "cayu.immutable_inputs",
        "ImmutableInputProjectionCapability",
    ),
    "ImmutableInputProjectionUnsupportedError": (
        "cayu.immutable_inputs",
        "ImmutableInputProjectionUnsupportedError",
    ),
    "ImmutableInputStore": ("cayu.immutable_inputs", "ImmutableInputStore"),
    "LocalImmutableInput": ("cayu.immutable_inputs", "LocalImmutableInput"),
    "MAX_ENVIRONMENT_PROGRESS_COUNTER": (
        "cayu.environments.lifecycle",
        "MAX_ENVIRONMENT_PROGRESS_COUNTER",
    ),
    "NativeBinding": ("cayu.environments.bindings", "NativeBinding"),
    "NoWorkspaceBinding": ("cayu.environments.bindings", "NoWorkspaceBinding"),
    "S3FilesAccessPointBinding": ("cayu.environments.aws_filesystems", "S3FilesAccessPointBinding"),
    "SyncBinding": ("cayu.environments.bindings", "SyncBinding"),
    "SyncBindingContext": ("cayu.environments.bindings", "SyncBindingContext"),
    "SyncBindingSourceConflictError": (
        "cayu.environments.bindings",
        "SyncBindingSourceConflictError",
    ),
    "SyncBindingStagingCapacity": ("cayu.environments._sync_staging", "SyncBindingStagingCapacity"),
    "SyncBindingStagingCapacityError": (
        "cayu.environments._sync_staging",
        "SyncBindingStagingCapacityError",
    ),
    "SyncBindingStagingSnapshot": ("cayu.environments._sync_staging", "SyncBindingStagingSnapshot"),
    "SyncTargetWorkspacePlan": ("cayu.environments.bindings", "SyncTargetWorkspacePlan"),
    "WorkspaceBinding": ("cayu.environments.bindings", "WorkspaceBinding"),
    "WorkspaceInstructions": ("cayu.environments.base", "WorkspaceInstructions"),
    "WorkspaceInstructionsConfig": ("cayu.environments.base", "WorkspaceInstructionsConfig"),
    "WorkspaceMountError": ("cayu.environments.aws_filesystems", "WorkspaceMountError"),
    "WorkspaceSnapshot": ("cayu.environments.bindings", "WorkspaceSnapshot"),
    "copy_bound_workspace": ("cayu.environments.bindings", "copy_bound_workspace"),
    "copy_environment": ("cayu.environments.base", "copy_environment"),
    "copy_environment_factory_request": (
        "cayu.environments.factory",
        "copy_environment_factory_request",
    ),
    "copy_environment_factory_result": (
        "cayu.environments.factory",
        "copy_environment_factory_result",
    ),
    "copy_environment_lifecycle_policy": (
        "cayu.environments.lifecycle",
        "copy_environment_lifecycle_policy",
    ),
    "copy_workspace_snapshot": ("cayu.environments.bindings", "copy_workspace_snapshot"),
    "current_environment_lifecycle_progress_reporter": (
        "cayu.environments.lifecycle",
        "current_environment_lifecycle_progress_reporter",
    ),
    "docker_immutable_input_capability": (
        "cayu.immutable_inputs",
        "docker_immutable_input_capability",
    ),
    "environment_lifecycle_progress_from_event": (
        "cayu.environments.lifecycle",
        "environment_lifecycle_progress_from_event",
    ),
    "environment_lifecycle_transition_from_event": (
        "cayu.environments.lifecycle",
        "environment_lifecycle_transition_from_event",
    ),
    "evaluate_execution_admission": ("cayu.environments.admission", "evaluate_execution_admission"),
    "inspect_local_immutable_input": ("cayu.immutable_inputs", "inspect_local_immutable_input"),
    "load_workspace_instructions": ("cayu.environments.base", "load_workspace_instructions"),
    "require_immutable_input_projection": (
        "cayu.immutable_inputs",
        "require_immutable_input_projection",
    ),
    "verify_docker_coding_toolchain_dependencies": (
        "cayu.environments.docker_toolchains",
        "verify_docker_coding_toolchain_dependencies",
    ),
    "verify_local_docker_coding_toolchain_dependencies": (
        "cayu.environments.docker_toolchains",
        "verify_local_docker_coding_toolchain_dependencies",
    ),
}

PUBLIC_NAMES = [
    "BoundWorkspace",
    "DEFAULT_ENVIRONMENT_FACTORY_RELEASE_TIMEOUT_SECONDS",
    "DEFAULT_ENVIRONMENT_LIFECYCLE_TIMEOUT_SECONDS",
    "DEFAULT_ENVIRONMENT_PHASE_TIMEOUT_SECONDS",
    "DEFAULT_ENVIRONMENT_PROGRESS_MIN_INTERVAL_SECONDS",
    "DEFAULT_IMMUTABLE_INPUT_MAX_FILES",
    "DEFAULT_IMMUTABLE_INPUT_MAX_FILE_BYTES",
    "DEFAULT_IMMUTABLE_INPUT_MAX_TOTAL_BYTES",
    "DEFAULT_MAX_ENVIRONMENT_PROGRESS_EVENTS",
    "DEFAULT_SYNC_BINDING_STAGING_CAPACITY",
    "DEFAULT_SYNC_STAGING_MAX_BYTES",
    "DEFAULT_SYNC_STAGING_MAX_CONCURRENCY",
    "DEFAULT_WORKSPACE_INSTRUCTIONS_MAX_BYTES",
    "DEFAULT_WORKSPACE_INSTRUCTION_PATHS",
    "DOCKER_CODING_COMMAND_AUTHORITY_SCHEMA",
    "DOCKER_CODING_PROTECTED_DIRECTORY_NAMES",
    "DOCKER_CODING_TOOLCHAIN_PROFILE_SCHEMA",
    "DeterministicWorkspaceBinding",
    "DockerCodingAdmissionProbe",
    "DockerCodingCommandAuthority",
    "DockerCodingDependencyInput",
    "DockerCodingEnvironmentFactory",
    "DockerCodingFixedEnvironmentVariable",
    "DockerCodingToolchainError",
    "DockerCodingToolchainProfile",
    "DockerCodingWorkspaceBinding",
    "DockerImmutableInputMount",
    "DockerWorkspaceTransferLimits",
    "EFSAccessPointBinding",
    "ENVIRONMENT_ALLOCATION_INTENT_SCHEMA_VERSION",
    "ENVIRONMENT_LIFECYCLE_PROGRESS_SCHEMA_VERSION",
    "ENVIRONMENT_LIFECYCLE_TRANSITION_SCHEMA_VERSION",
    "EXECUTION_CAPABILITY_EVIDENCE_SCHEMA",
    "EXECUTION_LIVE_EVIDENCE_MAX_TTL_SECONDS",
    "EXECUTION_TOOL_REQUIREMENT_EVIDENCE_SCHEMA",
    "Environment",
    "EnvironmentAllocationContext",
    "EnvironmentAllocationIntent",
    "EnvironmentAllocationScope",
    "EnvironmentAllocationState",
    "EnvironmentAllocationUnsupportedError",
    "EnvironmentFactory",
    "EnvironmentFactoryOperation",
    "EnvironmentFactoryRelease",
    "EnvironmentFactoryReleaseAction",
    "EnvironmentFactoryRequest",
    "EnvironmentFactoryResult",
    "EnvironmentLifecycleDeadlineExceeded",
    "EnvironmentLifecycleOperation",
    "EnvironmentLifecyclePhase",
    "EnvironmentLifecyclePolicy",
    "EnvironmentLifecycleProgress",
    "EnvironmentLifecycleProgressReporter",
    "EnvironmentLifecycleProgressStatus",
    "EnvironmentLifecycleTransition",
    "EnvironmentLifecycleTransitionOutcome",
    "EnvironmentLifecycleTransitionPhase",
    "EnvironmentSpec",
    "ExecutionAdmissionCandidate",
    "ExecutionAdmissionDecision",
    "ExecutionAdmissionError",
    "ExecutionAdmissionRefusal",
    "ExecutionCapabilityClaim",
    "ExecutionCapabilityEvidence",
    "ExecutionEnvironmentAuthority",
    "ExecutionEvidenceOverride",
    "ExecutionExecutableEvidence",
    "ExecutionRequirements",
    "ExecutionToolRequirement",
    "ExecutionToolRequirementEvidence",
    "GitRepositoryBinding",
    "IMMUTABLE_INPUT_FORMAT_VERSION",
    "ImmutableInputAdapterCapability",
    "ImmutableInputAttachment",
    "ImmutableInputAttachmentStateError",
    "ImmutableInputDiagnostic",
    "ImmutableInputMutationError",
    "ImmutableInputProjection",
    "ImmutableInputProjectionCapability",
    "ImmutableInputProjectionUnsupportedError",
    "ImmutableInputStore",
    "LocalImmutableInput",
    "MAX_ENVIRONMENT_PROGRESS_COUNTER",
    "NativeBinding",
    "NoWorkspaceBinding",
    "S3FilesAccessPointBinding",
    "SyncBinding",
    "SyncBindingContext",
    "SyncBindingSourceConflictError",
    "SyncBindingStagingCapacity",
    "SyncBindingStagingCapacityError",
    "SyncBindingStagingSnapshot",
    "SyncTargetWorkspacePlan",
    "WorkspaceBinding",
    "WorkspaceInstructions",
    "WorkspaceInstructionsConfig",
    "WorkspaceMountError",
    "WorkspaceSnapshot",
    "copy_bound_workspace",
    "copy_environment",
    "copy_environment_factory_request",
    "copy_environment_factory_result",
    "copy_environment_lifecycle_policy",
    "copy_workspace_snapshot",
    "current_environment_lifecycle_progress_reporter",
    "docker_immutable_input_capability",
    "environment_lifecycle_progress_from_event",
    "environment_lifecycle_transition_from_event",
    "evaluate_execution_admission",
    "inspect_local_immutable_input",
    "load_workspace_instructions",
    "require_immutable_input_projection",
    "verify_docker_coding_toolchain_dependencies",
    "verify_local_docker_coding_toolchain_dependencies",
]
