"""Explicit public exports; implementations load on first access."""

EXPORTS: dict[str, tuple[str, str]] = {
    "AfterToolCallDecision": ("cayu.observability.hooks", "AfterToolCallDecision"),
    "BeforeToolCallDecision": ("cayu.observability.hooks", "BeforeToolCallDecision"),
    "BeforeToolCallHookContext": ("cayu.observability.hooks", "BeforeToolCallHookContext"),
    "EventSink": ("cayu.observability.events", "EventSink"),
    "EventWatcher": ("cayu.observability.watchers", "EventWatcher"),
    "EventWatcherClaim": ("cayu.observability.watchers", "EventWatcherClaim"),
    "EventWatcherContext": ("cayu.observability.watchers", "EventWatcherContext"),
    "EventWatcherDeadLetter": ("cayu.observability.watchers", "EventWatcherDeadLetter"),
    "EventWatcherDelivery": ("cayu.observability.watchers", "EventWatcherDelivery"),
    "EventWatcherDeliveryStatus": ("cayu.observability.watchers", "EventWatcherDeliveryStatus"),
    "EventWatcherLeaseLost": ("cayu.observability.watchers", "EventWatcherLeaseLost"),
    "EventWatcherRunResult": ("cayu.observability.watchers", "EventWatcherRunResult"),
    "EventWatcherState": ("cayu.observability.watchers", "EventWatcherState"),
    "EventWatcherStore": ("cayu.observability.watchers", "EventWatcherStore"),
    "InMemoryEventSink": ("cayu.observability.events", "InMemoryEventSink"),
    "InMemoryEventWatcherStore": ("cayu.observability.watchers", "InMemoryEventWatcherStore"),
    "LoggingEventSink": ("cayu.observability.logging", "LoggingEventSink"),
    "OpenTelemetryEventSink": ("cayu.observability.otel", "OpenTelemetryEventSink"),
    "RuntimeHook": ("cayu.observability.hooks", "RuntimeHook"),
    "RuntimeHookContext": ("cayu.observability.hooks", "RuntimeHookContext"),
    "RuntimeHookPhase": ("cayu.observability.hooks", "RuntimeHookPhase"),
    "TRACE_LEVEL": ("cayu.observability.logging", "TRACE_LEVEL"),
    "ToolCallHookContext": ("cayu.observability.hooks", "ToolCallHookContext"),
    "ModelStepPreparationTiming": ("cayu.observability.timing", "ModelStepPreparationTiming"),
    "RuntimePhaseTiming": ("cayu.observability.timing", "RuntimePhaseTiming"),
    "RuntimeTimingConfig": ("cayu.observability.timing", "RuntimeTimingConfig"),
    "RuntimeTimingRecord": ("cayu.observability.timing", "RuntimeTimingRecord"),
    "RuntimeTimingSink": ("cayu.observability.timing", "RuntimeTimingSink"),
    "RuntimeTimingStatus": ("cayu.observability.timing", "RuntimeTimingStatus"),
    "ToolCallTiming": ("cayu.observability.timing", "ToolCallTiming"),
    "ToolRoundTiming": ("cayu.observability.timing", "ToolRoundTiming"),
}

PUBLIC_NAMES = [
    "ModelStepPreparationTiming",
    "RuntimePhaseTiming",
    "RuntimeTimingConfig",
    "RuntimeTimingRecord",
    "RuntimeTimingSink",
    "RuntimeTimingStatus",
    "ToolCallTiming",
    "ToolRoundTiming",
    "AfterToolCallDecision",
    "BeforeToolCallDecision",
    "BeforeToolCallHookContext",
    "EventSink",
    "EventWatcher",
    "EventWatcherClaim",
    "EventWatcherContext",
    "EventWatcherDeadLetter",
    "EventWatcherDelivery",
    "EventWatcherDeliveryStatus",
    "EventWatcherLeaseLost",
    "EventWatcherRunResult",
    "EventWatcherState",
    "EventWatcherStore",
    "InMemoryEventSink",
    "InMemoryEventWatcherStore",
    "LoggingEventSink",
    "OpenTelemetryEventSink",
    "RuntimeHook",
    "RuntimeHookContext",
    "RuntimeHookPhase",
    "TRACE_LEVEL",
    "ToolCallHookContext",
]
