"""Storage contracts."""

from cayu.storage.budget_ledger import SQLiteBudgetLedger
from cayu.storage.event_watchers import SQLiteEventWatcherStore
from cayu.storage.knowledge_indexer import (
    DEFAULT_KNOWLEDGE_CHUNK_OVERLAP_BYTES,
    DEFAULT_KNOWLEDGE_CHUNK_TARGET_BYTES,
    DEFAULT_KNOWLEDGE_INDEX_MAX_CHUNKS,
    KnowledgeIndexer,
    KnowledgeIndexRequest,
    KnowledgeIndexResult,
)
from cayu.storage.knowledge_review import KnowledgeReviewWorkflow
from cayu.storage.knowledge_sqlite import SQLiteKnowledgeStore
from cayu.storage.knowledge_transition import (
    KNOWLEDGE_REVISION_RESET_POLICY_VERSION,
    KnowledgeRevisionResetRequired,
    KnowledgeRevisionTransitionAction,
    KnowledgeRevisionTransitionAssessment,
    assess_knowledge_revision_transition,
    require_empty_knowledge_revision_transition,
)
from cayu.storage.memory import (
    BUILTIN_KNOWLEDGE_KINDS,
    DEFAULT_KNOWLEDGE_EMBEDDING_WORK_RECORD_LIMIT,
    DEFAULT_KNOWLEDGE_KIND,
    DEFAULT_KNOWLEDGE_LIMIT,
    DEFAULT_KNOWLEDGE_MAX_BYTES,
    DEFAULT_KNOWLEDGE_NAMESPACE,
    KNOWLEDGE_CHUNK_TEXT_GENERATOR,
    KNOWLEDGE_CHUNK_TEXT_GENERATOR_VERSION,
    KNOWLEDGE_CHUNK_TEXT_PREPROCESSING_VERSION,
    KNOWLEDGE_CHUNK_TEXT_PROJECTION,
    KNOWLEDGE_VECTOR_INDEX_REPRESENTATION_VERSION,
    MAX_KNOWLEDGE_CHANGE_LIMIT,
    MAX_KNOWLEDGE_CHANGE_SEQUENCE,
    MAX_KNOWLEDGE_CHUNK_ID_BYTES,
    MAX_KNOWLEDGE_CHUNK_INDEX,
    MAX_KNOWLEDGE_EMBEDDING_DIMENSIONS,
    MAX_KNOWLEDGE_EMBEDDING_WORK_RECORD_LIMIT,
    MAX_KNOWLEDGE_ENTRY_ID_BYTES,
    MAX_KNOWLEDGE_EVIDENCE_BYTES,
    MAX_KNOWLEDGE_EVIDENCE_JSON_BYTES,
    MAX_KNOWLEDGE_INDEX_READINESS_LIMIT,
    MAX_KNOWLEDGE_REVISION,
    InMemoryEmbeddingKnowledgeStore,
    InMemoryKnowledgeStore,
    KnowledgeAccessDenied,
    KnowledgeAccessScope,
    KnowledgeActorType,
    KnowledgeChange,
    KnowledgeChangeBatch,
    KnowledgeChangeClaim,
    KnowledgeChangeConsumerConflict,
    KnowledgeChangeConsumerState,
    KnowledgeChangeKind,
    KnowledgeChunk,
    KnowledgeChunkConflict,
    KnowledgeEmbeddingBackfillResult,
    KnowledgeEmbeddingIdentity,
    KnowledgeEmbeddingProjection,
    KnowledgeEmbeddingProjectionConflict,
    KnowledgeEmbeddingProjectionWriteResult,
    KnowledgeEmbeddingWorkerResult,
    KnowledgeEntry,
    KnowledgeEvidence,
    KnowledgeEvidenceConflict,
    KnowledgeEvidenceDisposition,
    KnowledgeEvidenceResult,
    KnowledgeEvidenceRole,
    KnowledgeFacet,
    KnowledgeHit,
    KnowledgeIndexCoverage,
    KnowledgeIndexReadiness,
    KnowledgeIndexReadinessBatch,
    KnowledgeIndexReadinessConflict,
    KnowledgeIndexReadinessUpdate,
    KnowledgeIndexState,
    KnowledgeListGroup,
    KnowledgeListItem,
    KnowledgeListQuery,
    KnowledgeListResult,
    KnowledgePublicationConflict,
    KnowledgePublicationReceipt,
    KnowledgeQuery,
    KnowledgeRevisionConflict,
    KnowledgeSearchMode,
    KnowledgeSearchResult,
    KnowledgeStatus,
    KnowledgeStore,
    KnowledgeVisibility,
    knowledge_chunk_embedding_identity,
    prepare_knowledge_publication,
)
from cayu.storage.sqlite import SQLiteSessionStore, SQLiteTaskStore

__all__ = [
    "BUILTIN_KNOWLEDGE_KINDS",
    "DEFAULT_KNOWLEDGE_CHUNK_OVERLAP_BYTES",
    "DEFAULT_KNOWLEDGE_CHUNK_TARGET_BYTES",
    "DEFAULT_KNOWLEDGE_EMBEDDING_WORK_RECORD_LIMIT",
    "DEFAULT_KNOWLEDGE_INDEX_MAX_CHUNKS",
    "DEFAULT_KNOWLEDGE_KIND",
    "DEFAULT_KNOWLEDGE_LIMIT",
    "DEFAULT_KNOWLEDGE_MAX_BYTES",
    "DEFAULT_KNOWLEDGE_NAMESPACE",
    "KNOWLEDGE_CHUNK_TEXT_GENERATOR",
    "KNOWLEDGE_CHUNK_TEXT_GENERATOR_VERSION",
    "KNOWLEDGE_CHUNK_TEXT_PREPROCESSING_VERSION",
    "KNOWLEDGE_CHUNK_TEXT_PROJECTION",
    "KNOWLEDGE_REVISION_RESET_POLICY_VERSION",
    "KNOWLEDGE_VECTOR_INDEX_REPRESENTATION_VERSION",
    "MAX_KNOWLEDGE_CHANGE_LIMIT",
    "MAX_KNOWLEDGE_CHANGE_SEQUENCE",
    "MAX_KNOWLEDGE_CHUNK_ID_BYTES",
    "MAX_KNOWLEDGE_CHUNK_INDEX",
    "MAX_KNOWLEDGE_EMBEDDING_DIMENSIONS",
    "MAX_KNOWLEDGE_EMBEDDING_WORK_RECORD_LIMIT",
    "MAX_KNOWLEDGE_ENTRY_ID_BYTES",
    "MAX_KNOWLEDGE_EVIDENCE_BYTES",
    "MAX_KNOWLEDGE_EVIDENCE_JSON_BYTES",
    "MAX_KNOWLEDGE_INDEX_READINESS_LIMIT",
    "MAX_KNOWLEDGE_REVISION",
    "InMemoryEmbeddingKnowledgeStore",
    "InMemoryKnowledgeStore",
    "KnowledgeAccessDenied",
    "KnowledgeAccessScope",
    "KnowledgeActorType",
    "KnowledgeChange",
    "KnowledgeChangeBatch",
    "KnowledgeChangeClaim",
    "KnowledgeChangeConsumerConflict",
    "KnowledgeChangeConsumerState",
    "KnowledgeChangeKind",
    "KnowledgeChunk",
    "KnowledgeChunkConflict",
    "KnowledgeEmbeddingBackfillResult",
    "KnowledgeEmbeddingIdentity",
    "KnowledgeEmbeddingProjection",
    "KnowledgeEmbeddingProjectionConflict",
    "KnowledgeEmbeddingProjectionWriteResult",
    "KnowledgeEmbeddingWorkerResult",
    "KnowledgeEntry",
    "KnowledgeEvidence",
    "KnowledgeEvidenceConflict",
    "KnowledgeEvidenceDisposition",
    "KnowledgeEvidenceResult",
    "KnowledgeEvidenceRole",
    "KnowledgeFacet",
    "KnowledgeHit",
    "KnowledgeIndexCoverage",
    "KnowledgeIndexReadiness",
    "KnowledgeIndexReadinessBatch",
    "KnowledgeIndexReadinessConflict",
    "KnowledgeIndexReadinessUpdate",
    "KnowledgeIndexRequest",
    "KnowledgeIndexResult",
    "KnowledgeIndexState",
    "KnowledgeIndexer",
    "KnowledgeListGroup",
    "KnowledgeListItem",
    "KnowledgeListQuery",
    "KnowledgeListResult",
    "KnowledgePublicationConflict",
    "KnowledgePublicationReceipt",
    "KnowledgeQuery",
    "KnowledgeReviewWorkflow",
    "KnowledgeRevisionConflict",
    "KnowledgeRevisionResetRequired",
    "KnowledgeRevisionTransitionAction",
    "KnowledgeRevisionTransitionAssessment",
    "KnowledgeSearchMode",
    "KnowledgeSearchResult",
    "KnowledgeStatus",
    "KnowledgeStore",
    "KnowledgeVisibility",
    "PostgresBudgetLedger",
    "PostgresEmbeddingKnowledgeStore",
    "PostgresEvalStore",
    "PostgresEventWatcherStore",
    "PostgresKnowledgeStore",
    "PostgresSessionStore",
    "PostgresTaskStore",
    "SQLiteBudgetLedger",
    "SQLiteEvalStore",
    "SQLiteEventWatcherStore",
    "SQLiteKnowledgeStore",
    "SQLiteSessionStore",
    "SQLiteTaskStore",
    "assess_knowledge_revision_transition",
    "knowledge_chunk_embedding_identity",
    "prepare_knowledge_publication",
    "require_empty_knowledge_revision_transition",
]


def __getattr__(name: str):
    # Postgres stores require the optional ``postgres`` extra (psycopg). Import
    # them lazily so the base package import does not depend on psycopg.
    if name == "SQLiteEvalStore":
        from cayu.storage.evals_sqlite import SQLiteEvalStore

        return SQLiteEvalStore
    if name in {
        "PostgresBudgetLedger",
        "PostgresEmbeddingKnowledgeStore",
        "PostgresEvalStore",
        "PostgresEventWatcherStore",
        "PostgresKnowledgeStore",
        "PostgresSessionStore",
        "PostgresTaskStore",
    }:
        if name == "PostgresEvalStore":
            from cayu.storage.evals_postgres import PostgresEvalStore

            return PostgresEvalStore
        from cayu.storage import postgres

        return getattr(postgres, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
