"""Explicit public exports; implementations load on first access."""

EXPORTS: dict[str, tuple[str, str]] = {
    "BUILTIN_KNOWLEDGE_KINDS": ("cayu.knowledge.records", "BUILTIN_KNOWLEDGE_KINDS"),
    "DEFAULT_KNOWLEDGE_CHUNK_OVERLAP_BYTES": (
        "cayu.storage.knowledge_indexer",
        "DEFAULT_KNOWLEDGE_CHUNK_OVERLAP_BYTES",
    ),
    "DEFAULT_KNOWLEDGE_CHUNK_TARGET_BYTES": (
        "cayu.storage.knowledge_indexer",
        "DEFAULT_KNOWLEDGE_CHUNK_TARGET_BYTES",
    ),
    "DEFAULT_KNOWLEDGE_EMBEDDING_WORK_RECORD_LIMIT": (
        "cayu.knowledge.indexing",
        "DEFAULT_KNOWLEDGE_EMBEDDING_WORK_RECORD_LIMIT",
    ),
    "DEFAULT_KNOWLEDGE_INDEX_MAX_CHUNKS": (
        "cayu.storage.knowledge_indexer",
        "DEFAULT_KNOWLEDGE_INDEX_MAX_CHUNKS",
    ),
    "DEFAULT_KNOWLEDGE_KIND": ("cayu.knowledge.records", "DEFAULT_KNOWLEDGE_KIND"),
    "DEFAULT_KNOWLEDGE_LIMIT": ("cayu.knowledge.records", "DEFAULT_KNOWLEDGE_LIMIT"),
    "DEFAULT_KNOWLEDGE_MAX_BYTES": ("cayu.knowledge.records", "DEFAULT_KNOWLEDGE_MAX_BYTES"),
    "DEFAULT_KNOWLEDGE_NAMESPACE": ("cayu.knowledge.records", "DEFAULT_KNOWLEDGE_NAMESPACE"),
    "InMemoryEmbeddingKnowledgeStore": ("cayu.storage.memory", "InMemoryEmbeddingKnowledgeStore"),
    "InMemoryKnowledgeStore": ("cayu.storage.memory", "InMemoryKnowledgeStore"),
    "KNOWLEDGE_CHUNK_TEXT_GENERATOR": ("cayu.knowledge.indexing", "KNOWLEDGE_CHUNK_TEXT_GENERATOR"),
    "KNOWLEDGE_CHUNK_TEXT_GENERATOR_VERSION": (
        "cayu.knowledge.indexing",
        "KNOWLEDGE_CHUNK_TEXT_GENERATOR_VERSION",
    ),
    "KNOWLEDGE_CHUNK_TEXT_PREPROCESSING_VERSION": (
        "cayu.knowledge.indexing",
        "KNOWLEDGE_CHUNK_TEXT_PREPROCESSING_VERSION",
    ),
    "KNOWLEDGE_CHUNK_TEXT_PROJECTION": (
        "cayu.knowledge.indexing",
        "KNOWLEDGE_CHUNK_TEXT_PROJECTION",
    ),
    "KNOWLEDGE_REVISION_RESET_POLICY_VERSION": (
        "cayu.storage.knowledge_transition",
        "KNOWLEDGE_REVISION_RESET_POLICY_VERSION",
    ),
    "KNOWLEDGE_VECTOR_INDEX_REPRESENTATION_VERSION": (
        "cayu.knowledge.indexing",
        "KNOWLEDGE_VECTOR_INDEX_REPRESENTATION_VERSION",
    ),
    "KnowledgeAccessDenied": ("cayu.knowledge.scopes", "KnowledgeAccessDenied"),
    "KnowledgeAccessScope": ("cayu.knowledge.scopes", "KnowledgeAccessScope"),
    "KnowledgeActivationAuthority": (
        "cayu.knowledge.activation_contracts",
        "KnowledgeActivationAuthority",
    ),
    "KnowledgeActivationConflict": (
        "cayu.knowledge.activation_contracts",
        "KnowledgeActivationConflict",
    ),
    "KnowledgeActivationDecision": (
        "cayu.knowledge.activation_contracts",
        "KnowledgeActivationDecision",
    ),
    "KnowledgeActivationDisposition": (
        "cayu.knowledge.activation_contracts",
        "KnowledgeActivationDisposition",
    ),
    "KnowledgeActivationReceipt": (
        "cayu.knowledge.activation_contracts",
        "KnowledgeActivationReceipt",
    ),
    "KnowledgeActivationRequest": (
        "cayu.knowledge.activation_contracts",
        "KnowledgeActivationRequest",
    ),
    "KnowledgeActivationSource": (
        "cayu.knowledge.activation_contracts",
        "KnowledgeActivationSource",
    ),
    "KnowledgeActorType": ("cayu.knowledge.records", "KnowledgeActorType"),
    "KnowledgeChange": ("cayu.knowledge.changes", "KnowledgeChange"),
    "KnowledgeChangeBatch": ("cayu.knowledge.changes", "KnowledgeChangeBatch"),
    "KnowledgeChangeClaim": ("cayu.knowledge.changes", "KnowledgeChangeClaim"),
    "KnowledgeChangeConsumerConflict": (
        "cayu.knowledge.changes",
        "KnowledgeChangeConsumerConflict",
    ),
    "KnowledgeChangeConsumerState": ("cayu.knowledge.changes", "KnowledgeChangeConsumerState"),
    "KnowledgeChangeKind": ("cayu.knowledge.changes", "KnowledgeChangeKind"),
    "KnowledgeChunk": ("cayu.knowledge.records", "KnowledgeChunk"),
    "KnowledgeChunkConflict": ("cayu.knowledge.records", "KnowledgeChunkConflict"),
    "KnowledgeEmbeddingBackfillResult": (
        "cayu.knowledge.indexing",
        "KnowledgeEmbeddingBackfillResult",
    ),
    "KnowledgeEmbeddingIdentity": ("cayu.knowledge.indexing", "KnowledgeEmbeddingIdentity"),
    "KnowledgeEmbeddingProjection": ("cayu.knowledge.indexing", "KnowledgeEmbeddingProjection"),
    "KnowledgeEmbeddingProjectionConflict": (
        "cayu.knowledge.indexing",
        "KnowledgeEmbeddingProjectionConflict",
    ),
    "KnowledgeEmbeddingProjectionWriteResult": (
        "cayu.knowledge.indexing",
        "KnowledgeEmbeddingProjectionWriteResult",
    ),
    "KnowledgeEmbeddingWorkerResult": ("cayu.knowledge.indexing", "KnowledgeEmbeddingWorkerResult"),
    "KnowledgeEntry": ("cayu.knowledge.records", "KnowledgeEntry"),
    "KnowledgeEntryReadLimitExceeded": (
        "cayu.knowledge.records",
        "KnowledgeEntryReadLimitExceeded",
    ),
    "KnowledgeEvidence": ("cayu.knowledge.records", "KnowledgeEvidence"),
    "KnowledgeEvidenceConflict": ("cayu.knowledge.records", "KnowledgeEvidenceConflict"),
    "KnowledgeEvidenceDisposition": ("cayu.knowledge.records", "KnowledgeEvidenceDisposition"),
    "KnowledgeEvidenceResult": ("cayu.knowledge.records", "KnowledgeEvidenceResult"),
    "KnowledgeEvidenceRole": ("cayu.knowledge.records", "KnowledgeEvidenceRole"),
    "KnowledgeFacet": ("cayu.storage.memory", "KnowledgeFacet"),
    "KnowledgeGovernanceConfig": (
        "cayu.knowledge.activation_contracts",
        "KnowledgeGovernanceConfig",
    ),
    "KnowledgeGovernanceMode": ("cayu.knowledge.activation_contracts", "KnowledgeGovernanceMode"),
    "KnowledgeHit": ("cayu.storage.memory", "KnowledgeHit"),
    "KnowledgeIndexCoverage": ("cayu.knowledge.indexing", "KnowledgeIndexCoverage"),
    "KnowledgeIndexReadiness": ("cayu.knowledge.indexing", "KnowledgeIndexReadiness"),
    "KnowledgeIndexReadinessBatch": ("cayu.knowledge.indexing", "KnowledgeIndexReadinessBatch"),
    "KnowledgeIndexReadinessConflict": (
        "cayu.knowledge.indexing",
        "KnowledgeIndexReadinessConflict",
    ),
    "KnowledgeIndexReadinessUpdate": ("cayu.knowledge.indexing", "KnowledgeIndexReadinessUpdate"),
    "KnowledgeIndexRequest": ("cayu.storage.knowledge_indexer", "KnowledgeIndexRequest"),
    "KnowledgeIndexResult": ("cayu.storage.knowledge_indexer", "KnowledgeIndexResult"),
    "KnowledgeIndexState": ("cayu.knowledge.indexing", "KnowledgeIndexState"),
    "KnowledgeIndexer": ("cayu.storage.knowledge_indexer", "KnowledgeIndexer"),
    "KnowledgeLineageCurrentness": ("cayu.knowledge.relations", "KnowledgeLineageCurrentness"),
    "KnowledgeLineageLink": ("cayu.knowledge.relations", "KnowledgeLineageLink"),
    "KnowledgeLineageQuery": ("cayu.knowledge.relations", "KnowledgeLineageQuery"),
    "KnowledgeLineageResult": ("cayu.knowledge.relations", "KnowledgeLineageResult"),
    "KnowledgeLineageRole": ("cayu.knowledge.relations", "KnowledgeLineageRole"),
    "KnowledgeListGroup": ("cayu.storage.memory", "KnowledgeListGroup"),
    "KnowledgeListItem": ("cayu.storage.memory", "KnowledgeListItem"),
    "KnowledgeListQuery": ("cayu.storage.memory", "KnowledgeListQuery"),
    "KnowledgeListResult": ("cayu.storage.memory", "KnowledgeListResult"),
    "KnowledgeMaintenanceConflict": (
        "cayu.knowledge.maintenance_contracts",
        "KnowledgeMaintenanceConflict",
    ),
    "KnowledgeMaintenanceDecision": (
        "cayu.knowledge.maintenance_contracts",
        "KnowledgeMaintenanceDecision",
    ),
    "KnowledgeMaintenanceDecisionKind": (
        "cayu.knowledge.maintenance_contracts",
        "KnowledgeMaintenanceDecisionKind",
    ),
    "KnowledgeMaintenanceDecisionReceipt": (
        "cayu.knowledge.maintenance_contracts",
        "KnowledgeMaintenanceDecisionReceipt",
    ),
    "KnowledgeMaintenanceOutcome": (
        "cayu.knowledge.maintenance_contracts",
        "KnowledgeMaintenanceOutcome",
    ),
    "KnowledgeMaintenanceProposal": (
        "cayu.knowledge.maintenance_contracts",
        "KnowledgeMaintenanceProposal",
    ),
    "KnowledgeMaintenanceStale": (
        "cayu.knowledge.maintenance_contracts",
        "KnowledgeMaintenanceStale",
    ),
    "KnowledgePublicationConflict": ("cayu.storage.memory", "KnowledgePublicationConflict"),
    "KnowledgePublicationReceipt": ("cayu.storage.memory", "KnowledgePublicationReceipt"),
    "KnowledgeQuery": ("cayu.storage.memory", "KnowledgeQuery"),
    "KnowledgeRelation": ("cayu.knowledge.relations", "KnowledgeRelation"),
    "KnowledgeRelationConflict": ("cayu.knowledge.relations", "KnowledgeRelationConflict"),
    "KnowledgeRelationDirection": ("cayu.knowledge.relations", "KnowledgeRelationDirection"),
    "KnowledgeRelationKind": ("cayu.knowledge.relations", "KnowledgeRelationKind"),
    "KnowledgeRelationPublicationReceipt": (
        "cayu.knowledge.relations",
        "KnowledgeRelationPublicationReceipt",
    ),
    "KnowledgeRelationQuery": ("cayu.knowledge.relations", "KnowledgeRelationQuery"),
    "KnowledgeRelationResult": ("cayu.knowledge.relations", "KnowledgeRelationResult"),
    "KnowledgeReviewApproval": ("cayu.knowledge.activation_contracts", "KnowledgeReviewApproval"),
    "KnowledgeReviewWorkflow": ("cayu.storage.knowledge_review", "KnowledgeReviewWorkflow"),
    "KnowledgeRevisionConflict": ("cayu.knowledge.records", "KnowledgeRevisionConflict"),
    "KnowledgeRevisionRef": ("cayu.knowledge.records", "KnowledgeRevisionRef"),
    "KnowledgeRevisionResetRequired": (
        "cayu.storage.knowledge_transition",
        "KnowledgeRevisionResetRequired",
    ),
    "KnowledgeRevisionTransitionAction": (
        "cayu.storage.knowledge_transition",
        "KnowledgeRevisionTransitionAction",
    ),
    "KnowledgeRevisionTransitionAssessment": (
        "cayu.storage.knowledge_transition",
        "KnowledgeRevisionTransitionAssessment",
    ),
    "KnowledgeSearchMode": ("cayu.storage.memory", "KnowledgeSearchMode"),
    "KnowledgeSearchResult": ("cayu.storage.memory", "KnowledgeSearchResult"),
    "KnowledgeStatus": ("cayu.knowledge.records", "KnowledgeStatus"),
    "KnowledgeStore": ("cayu.storage.memory", "KnowledgeStore"),
    "KnowledgeVisibility": ("cayu.knowledge.records", "KnowledgeVisibility"),
    "MAX_KNOWLEDGE_ACTIVATION_ANNOTATION_BYTES": (
        "cayu.knowledge.activation_contracts",
        "MAX_KNOWLEDGE_ACTIVATION_ANNOTATION_BYTES",
    ),
    "MAX_KNOWLEDGE_ACTIVATION_CHUNKS": (
        "cayu.knowledge.activation_contracts",
        "MAX_KNOWLEDGE_ACTIVATION_CHUNKS",
    ),
    "MAX_KNOWLEDGE_ACTIVATION_EVALUATOR_RESULT_BYTES": (
        "cayu.knowledge.activation_contracts",
        "MAX_KNOWLEDGE_ACTIVATION_EVALUATOR_RESULT_BYTES",
    ),
    "MAX_KNOWLEDGE_ACTIVATION_EVIDENCE_RECORDS": (
        "cayu.knowledge.activation_contracts",
        "MAX_KNOWLEDGE_ACTIVATION_EVIDENCE_RECORDS",
    ),
    "MAX_KNOWLEDGE_ACTIVATION_IDENTITY_BYTES": (
        "cayu.knowledge.records",
        "MAX_KNOWLEDGE_ACTIVATION_IDENTITY_BYTES",
    ),
    "MAX_KNOWLEDGE_ACTIVATION_RECEIPT_BYTES": (
        "cayu.knowledge.activation_contracts",
        "MAX_KNOWLEDGE_ACTIVATION_RECEIPT_BYTES",
    ),
    "MAX_KNOWLEDGE_ACTIVATION_REQUEST_BYTES": (
        "cayu.knowledge.activation_contracts",
        "MAX_KNOWLEDGE_ACTIVATION_REQUEST_BYTES",
    ),
    "MAX_KNOWLEDGE_CHANGE_LIMIT": ("cayu.knowledge.changes", "MAX_KNOWLEDGE_CHANGE_LIMIT"),
    "MAX_KNOWLEDGE_CHANGE_SEQUENCE": ("cayu.knowledge.changes", "MAX_KNOWLEDGE_CHANGE_SEQUENCE"),
    "MAX_KNOWLEDGE_CHUNK_ID_BYTES": ("cayu.knowledge.records", "MAX_KNOWLEDGE_CHUNK_ID_BYTES"),
    "MAX_KNOWLEDGE_CHUNK_INDEX": ("cayu.knowledge.records", "MAX_KNOWLEDGE_CHUNK_INDEX"),
    "MAX_KNOWLEDGE_EMBEDDING_DIMENSIONS": (
        "cayu.knowledge.indexing",
        "MAX_KNOWLEDGE_EMBEDDING_DIMENSIONS",
    ),
    "MAX_KNOWLEDGE_EMBEDDING_WORK_RECORD_LIMIT": (
        "cayu.knowledge.indexing",
        "MAX_KNOWLEDGE_EMBEDDING_WORK_RECORD_LIMIT",
    ),
    "MAX_KNOWLEDGE_ENTRY_ID_BYTES": ("cayu.knowledge.records", "MAX_KNOWLEDGE_ENTRY_ID_BYTES"),
    "MAX_KNOWLEDGE_EVIDENCE_BYTES": ("cayu.knowledge.records", "MAX_KNOWLEDGE_EVIDENCE_BYTES"),
    "MAX_KNOWLEDGE_EVIDENCE_JSON_BYTES": (
        "cayu.knowledge.records",
        "MAX_KNOWLEDGE_EVIDENCE_JSON_BYTES",
    ),
    "MAX_KNOWLEDGE_INDEX_READINESS_LIMIT": (
        "cayu.knowledge.indexing",
        "MAX_KNOWLEDGE_INDEX_READINESS_LIMIT",
    ),
    "MAX_KNOWLEDGE_MAINTENANCE_BYTES": (
        "cayu.knowledge.maintenance_contracts",
        "MAX_KNOWLEDGE_MAINTENANCE_BYTES",
    ),
    "MAX_KNOWLEDGE_MAINTENANCE_METADATA_BYTES": (
        "cayu.knowledge.maintenance_contracts",
        "MAX_KNOWLEDGE_MAINTENANCE_METADATA_BYTES",
    ),
    "MAX_KNOWLEDGE_MAINTENANCE_SOURCES": (
        "cayu.knowledge.maintenance_contracts",
        "MAX_KNOWLEDGE_MAINTENANCE_SOURCES",
    ),
    "MAX_KNOWLEDGE_MAINTENANCE_TEXT_BYTES": (
        "cayu.knowledge.maintenance_contracts",
        "MAX_KNOWLEDGE_MAINTENANCE_TEXT_BYTES",
    ),
    "MAX_KNOWLEDGE_RELATION_BATCH": ("cayu.knowledge.relations", "MAX_KNOWLEDGE_RELATION_BATCH"),
    "MAX_KNOWLEDGE_RELATION_BYTES": ("cayu.knowledge.relations", "MAX_KNOWLEDGE_RELATION_BYTES"),
    "MAX_KNOWLEDGE_RELATION_CURSOR_BYTES": (
        "cayu.knowledge.relations",
        "MAX_KNOWLEDGE_RELATION_CURSOR_BYTES",
    ),
    "MAX_KNOWLEDGE_RELATION_LIMIT": ("cayu.knowledge.relations", "MAX_KNOWLEDGE_RELATION_LIMIT"),
    "MAX_KNOWLEDGE_REVISION": ("cayu.knowledge.records", "MAX_KNOWLEDGE_REVISION"),
    "MAX_KNOWLEDGE_REVISION_SEARCH_REFS": (
        "cayu.knowledge.records",
        "MAX_KNOWLEDGE_REVISION_SEARCH_REFS",
    ),
    "PostgresAgentWorkContextStore": ("cayu.storage.postgres", "PostgresAgentWorkContextStore"),
    "PostgresBudgetLedger": ("cayu.storage.postgres", "PostgresBudgetLedger"),
    "PostgresEmbeddingKnowledgeStore": ("cayu.storage.postgres", "PostgresEmbeddingKnowledgeStore"),
    "PostgresEvalStore": ("cayu.storage.evals_postgres", "PostgresEvalStore"),
    "PostgresEventWatcherStore": ("cayu.storage.postgres", "PostgresEventWatcherStore"),
    "PostgresKnowledgeStore": ("cayu.storage.postgres", "PostgresKnowledgeStore"),
    "PostgresProductOperationStore": (
        "cayu.storage.product_operations_postgres",
        "PostgresProductOperationStore",
    ),
    "PostgresSessionStore": ("cayu.storage.postgres", "PostgresSessionStore"),
    "PostgresTaskStore": ("cayu.storage.postgres", "PostgresTaskStore"),
    "SQLiteAgentWorkContextStore": (
        "cayu.storage.work_context_sqlite",
        "SQLiteAgentWorkContextStore",
    ),
    "SQLiteBudgetLedger": ("cayu.storage.budget_ledger", "SQLiteBudgetLedger"),
    "SQLiteEvalStore": ("cayu.storage.evals_sqlite", "SQLiteEvalStore"),
    "SQLiteEvalWriterContentionPolicy": (
        "cayu.storage.evals_sqlite",
        "SQLiteEvalWriterContentionPolicy",
    ),
    "SQLiteEventWatcherStore": ("cayu.storage.event_watchers", "SQLiteEventWatcherStore"),
    "SQLiteKnowledgeStore": ("cayu.storage.knowledge_sqlite", "SQLiteKnowledgeStore"),
    "SQLiteProductOperationStore": (
        "cayu.storage.product_operations_sqlite",
        "SQLiteProductOperationStore",
    ),
    "SQLiteSessionStore": ("cayu.storage.sqlite", "SQLiteSessionStore"),
    "SQLiteTaskStore": ("cayu.storage.tasks_sqlite", "SQLiteTaskStore"),
    "assess_knowledge_revision_transition": (
        "cayu.storage.knowledge_transition",
        "assess_knowledge_revision_transition",
    ),
    "copy_knowledge_revision_refs": ("cayu.knowledge.records", "copy_knowledge_revision_refs"),
    "knowledge_access_scope_sha256": ("cayu.knowledge.scopes", "knowledge_access_scope_sha256"),
    "knowledge_chunk_embedding_identity": (
        "cayu.knowledge.indexing",
        "knowledge_chunk_embedding_identity",
    ),
    "prepare_knowledge_activation_request": (
        "cayu.knowledge.activation_contracts",
        "prepare_knowledge_activation_request",
    ),
    "prepare_knowledge_maintenance_decision": (
        "cayu.knowledge.maintenance_contracts",
        "prepare_knowledge_maintenance_decision",
    ),
    "prepare_knowledge_publication": ("cayu.storage.memory", "prepare_knowledge_publication"),
    "prepare_knowledge_relations": ("cayu.knowledge.relations", "prepare_knowledge_relations"),
    "require_empty_knowledge_revision_transition": (
        "cayu.storage.knowledge_transition",
        "require_empty_knowledge_revision_transition",
    ),
}

PUBLIC_NAMES = [
    "BUILTIN_KNOWLEDGE_KINDS",
    "DEFAULT_KNOWLEDGE_CHUNK_OVERLAP_BYTES",
    "DEFAULT_KNOWLEDGE_CHUNK_TARGET_BYTES",
    "DEFAULT_KNOWLEDGE_EMBEDDING_WORK_RECORD_LIMIT",
    "DEFAULT_KNOWLEDGE_INDEX_MAX_CHUNKS",
    "DEFAULT_KNOWLEDGE_KIND",
    "DEFAULT_KNOWLEDGE_LIMIT",
    "DEFAULT_KNOWLEDGE_MAX_BYTES",
    "DEFAULT_KNOWLEDGE_NAMESPACE",
    "InMemoryEmbeddingKnowledgeStore",
    "InMemoryKnowledgeStore",
    "KNOWLEDGE_CHUNK_TEXT_GENERATOR",
    "KNOWLEDGE_CHUNK_TEXT_GENERATOR_VERSION",
    "KNOWLEDGE_CHUNK_TEXT_PREPROCESSING_VERSION",
    "KNOWLEDGE_CHUNK_TEXT_PROJECTION",
    "KNOWLEDGE_REVISION_RESET_POLICY_VERSION",
    "KNOWLEDGE_VECTOR_INDEX_REPRESENTATION_VERSION",
    "KnowledgeAccessDenied",
    "KnowledgeAccessScope",
    "KnowledgeActivationAuthority",
    "KnowledgeActivationConflict",
    "KnowledgeActivationDecision",
    "KnowledgeActivationDisposition",
    "KnowledgeActivationReceipt",
    "KnowledgeActivationRequest",
    "KnowledgeActivationSource",
    "KnowledgeActorType",
    "KnowledgeChange",
    "KnowledgeChangeBatch",
    "KnowledgeChangeClaim",
    "KnowledgeChangeConsumerConflict",
    "KnowledgeChangeConsumerState",
    "KnowledgeChangeKind",
    "KnowledgeChunk",
    "KnowledgeChunkConflict",
    "KnowledgeEmbeddingBackfillResult",
    "KnowledgeEmbeddingIdentity",
    "KnowledgeEmbeddingProjection",
    "KnowledgeEmbeddingProjectionConflict",
    "KnowledgeEmbeddingProjectionWriteResult",
    "KnowledgeEmbeddingWorkerResult",
    "KnowledgeEntry",
    "KnowledgeEntryReadLimitExceeded",
    "KnowledgeEvidence",
    "KnowledgeEvidenceConflict",
    "KnowledgeEvidenceDisposition",
    "KnowledgeEvidenceResult",
    "KnowledgeEvidenceRole",
    "KnowledgeFacet",
    "KnowledgeGovernanceConfig",
    "KnowledgeGovernanceMode",
    "KnowledgeHit",
    "KnowledgeIndexCoverage",
    "KnowledgeIndexReadiness",
    "KnowledgeIndexReadinessBatch",
    "KnowledgeIndexReadinessConflict",
    "KnowledgeIndexReadinessUpdate",
    "KnowledgeIndexRequest",
    "KnowledgeIndexResult",
    "KnowledgeIndexState",
    "KnowledgeIndexer",
    "KnowledgeLineageCurrentness",
    "KnowledgeLineageLink",
    "KnowledgeLineageQuery",
    "KnowledgeLineageResult",
    "KnowledgeLineageRole",
    "KnowledgeListGroup",
    "KnowledgeListItem",
    "KnowledgeListQuery",
    "KnowledgeListResult",
    "KnowledgeMaintenanceConflict",
    "KnowledgeMaintenanceDecision",
    "KnowledgeMaintenanceDecisionKind",
    "KnowledgeMaintenanceDecisionReceipt",
    "KnowledgeMaintenanceOutcome",
    "KnowledgeMaintenanceProposal",
    "KnowledgeMaintenanceStale",
    "KnowledgePublicationConflict",
    "KnowledgePublicationReceipt",
    "KnowledgeQuery",
    "KnowledgeRelation",
    "KnowledgeRelationConflict",
    "KnowledgeRelationDirection",
    "KnowledgeRelationKind",
    "KnowledgeRelationPublicationReceipt",
    "KnowledgeRelationQuery",
    "KnowledgeRelationResult",
    "KnowledgeReviewApproval",
    "KnowledgeReviewWorkflow",
    "KnowledgeRevisionConflict",
    "KnowledgeRevisionRef",
    "KnowledgeRevisionResetRequired",
    "KnowledgeRevisionTransitionAction",
    "KnowledgeRevisionTransitionAssessment",
    "KnowledgeSearchMode",
    "KnowledgeSearchResult",
    "KnowledgeStatus",
    "KnowledgeStore",
    "KnowledgeVisibility",
    "MAX_KNOWLEDGE_ACTIVATION_ANNOTATION_BYTES",
    "MAX_KNOWLEDGE_ACTIVATION_CHUNKS",
    "MAX_KNOWLEDGE_ACTIVATION_EVALUATOR_RESULT_BYTES",
    "MAX_KNOWLEDGE_ACTIVATION_EVIDENCE_RECORDS",
    "MAX_KNOWLEDGE_ACTIVATION_IDENTITY_BYTES",
    "MAX_KNOWLEDGE_ACTIVATION_RECEIPT_BYTES",
    "MAX_KNOWLEDGE_ACTIVATION_REQUEST_BYTES",
    "MAX_KNOWLEDGE_CHANGE_LIMIT",
    "MAX_KNOWLEDGE_CHANGE_SEQUENCE",
    "MAX_KNOWLEDGE_CHUNK_ID_BYTES",
    "MAX_KNOWLEDGE_CHUNK_INDEX",
    "MAX_KNOWLEDGE_EMBEDDING_DIMENSIONS",
    "MAX_KNOWLEDGE_EMBEDDING_WORK_RECORD_LIMIT",
    "MAX_KNOWLEDGE_ENTRY_ID_BYTES",
    "MAX_KNOWLEDGE_EVIDENCE_BYTES",
    "MAX_KNOWLEDGE_EVIDENCE_JSON_BYTES",
    "MAX_KNOWLEDGE_INDEX_READINESS_LIMIT",
    "MAX_KNOWLEDGE_MAINTENANCE_BYTES",
    "MAX_KNOWLEDGE_MAINTENANCE_METADATA_BYTES",
    "MAX_KNOWLEDGE_MAINTENANCE_SOURCES",
    "MAX_KNOWLEDGE_MAINTENANCE_TEXT_BYTES",
    "MAX_KNOWLEDGE_RELATION_BATCH",
    "MAX_KNOWLEDGE_RELATION_BYTES",
    "MAX_KNOWLEDGE_RELATION_CURSOR_BYTES",
    "MAX_KNOWLEDGE_RELATION_LIMIT",
    "MAX_KNOWLEDGE_REVISION",
    "MAX_KNOWLEDGE_REVISION_SEARCH_REFS",
    "PostgresAgentWorkContextStore",
    "PostgresBudgetLedger",
    "PostgresEmbeddingKnowledgeStore",
    "PostgresEvalStore",
    "PostgresEventWatcherStore",
    "PostgresKnowledgeStore",
    "PostgresProductOperationStore",
    "PostgresSessionStore",
    "PostgresTaskStore",
    "SQLiteAgentWorkContextStore",
    "SQLiteBudgetLedger",
    "SQLiteEvalStore",
    "SQLiteEvalWriterContentionPolicy",
    "SQLiteEventWatcherStore",
    "SQLiteKnowledgeStore",
    "SQLiteProductOperationStore",
    "SQLiteSessionStore",
    "SQLiteTaskStore",
    "assess_knowledge_revision_transition",
    "copy_knowledge_revision_refs",
    "knowledge_access_scope_sha256",
    "knowledge_chunk_embedding_identity",
    "prepare_knowledge_activation_request",
    "prepare_knowledge_maintenance_decision",
    "prepare_knowledge_publication",
    "prepare_knowledge_relations",
    "require_empty_knowledge_revision_transition",
]
