"""Lazy public participant-administration exports."""

EXPORTS: dict[str, tuple[str, str]] = {
    "PreparedRecipientAdmission": (
        "cayu.collaboration.prepared_admission",
        "PreparedRecipientAdmission",
    ),
    "FreshRecipientAdmissionTarget": (
        "cayu.collaboration.prepared_admission",
        "FreshRecipientAdmissionTarget",
    ),
    "PreparedAdmissionRegistration": (
        "cayu.collaboration.request_access",
        "PreparedAdmissionRegistration",
    ),
    "RequestAdmissionReader": ("cayu.collaboration.request_access", "RequestAdmissionReader"),
    "ClarificationQuestionRecovery": (
        "cayu.collaboration._clarification_recovery_types",
        "ClarificationQuestionRecovery",
    ),
    "ClarificationDueQuestion": (
        "cayu.collaboration._clarification_recovery_types",
        "ClarificationDueQuestion",
    ),
    "ClarificationDueQuestionPage": (
        "cayu.collaboration._clarification_recovery_types",
        "ClarificationDueQuestionPage",
    ),
    "ClarificationExpiryRequest": (
        "cayu.collaboration._clarification_recovery_types",
        "ClarificationExpiryRequest",
    ),
    "ClarificationExpiryReceipt": (
        "cayu.collaboration._clarification_recovery_types",
        "ClarificationExpiryReceipt",
    ),
    "ClarificationDeliveryRecovery": (
        "cayu.collaboration._clarification_recovery_types",
        "ClarificationDeliveryRecovery",
    ),
    "ClarificationPendingDelivery": (
        "cayu.collaboration._clarification_recovery_types",
        "ClarificationPendingDelivery",
    ),
    "ClarificationPendingDeliveryPage": (
        "cayu.collaboration._clarification_recovery_types",
        "ClarificationPendingDeliveryPage",
    ),
    "ClarificationServiceInspection": (
        "cayu.collaboration._clarification_recovery_types",
        "ClarificationServiceInspection",
    ),
    "ClarificationServiceInspectionPage": (
        "cayu.collaboration._clarification_recovery_types",
        "ClarificationServiceInspectionPage",
    ),
    "ClarificationServiceRecovery": (
        "cayu.collaboration._clarification_recovery_types",
        "ClarificationServiceRecovery",
    ),
    "ClarificationPendingService": (
        "cayu.collaboration._clarification_recovery_types",
        "ClarificationPendingService",
    ),
    "ClarificationPendingServicePage": (
        "cayu.collaboration._clarification_recovery_types",
        "ClarificationPendingServicePage",
    ),
    "ClarificationDueCursor": ("cayu.collaboration.clarifications", "ClarificationDueCursor"),
    "ClarificationReplyRequest": (
        "cayu.collaboration._clarification_reply_api",
        "ClarificationReplyRequest",
    ),
    "ClarificationReplyAcceptance": (
        "cayu.collaboration._clarification_reply_api",
        "ClarificationReplyAcceptance",
    ),
    "ClarificationServiceRequest": (
        "cayu.collaboration._clarification_service_api",
        "ClarificationServiceRequest",
    ),
    "ClarificationServiceReceipt": (
        "cayu.collaboration._clarification_service_api",
        "ClarificationServiceReceipt",
    ),
    "ClarificationDeliveryIntent": (
        "cayu.collaboration._clarification_deliveries",
        "ClarificationDeliveryIntent",
    ),
    "ClarificationDeliveryRecord": (
        "cayu.collaboration._clarification_deliveries",
        "ClarificationDeliveryRecord",
    ),
    "ClarificationDeliveryReceipt": (
        "cayu.collaboration._clarification_deliveries",
        "ClarificationDeliveryReceipt",
    ),
    "ClarificationQuestionState": (
        "cayu.collaboration._clarification_state",
        "ClarificationQuestionState",
    ),
    "ClarificationCloseCommand": (
        "cayu.collaboration._clarification_commands",
        "ClarificationCloseCommand",
    ),
    "ClarificationCloseReceipt": (
        "cayu.collaboration._clarification_commands",
        "ClarificationCloseReceipt",
    ),
    "ClarificationOpenCommand": (
        "cayu.collaboration._clarification_commands",
        "ClarificationOpenCommand",
    ),
    "ClarificationOpenReceipt": (
        "cayu.collaboration._clarification_commands",
        "ClarificationOpenReceipt",
    ),
    "ClarificationQuestion": ("cayu.collaboration.clarifications", "ClarificationQuestion"),
    "ClarificationSource": ("cayu.collaboration.clarifications", "ClarificationSource"),
    "ClarificationPolicy": ("cayu.collaboration.clarifications", "ClarificationPolicy"),
    "CollaborationWait": ("cayu.collaboration.waits", "CollaborationWait"),
    "WaitEvidence": ("cayu.collaboration.waits", "WaitEvidence"),
    "WaitElection": ("cayu.collaboration.waits", "WaitElection"),
    "WaitRegistration": ("cayu.collaboration.waits", "WaitRegistration"),
    "WaitSnapshot": ("cayu.collaboration.waits", "WaitSnapshot"),
    "ParticipantSessionWaitExclusionReceipt": (
        "cayu.collaboration.waits",
        "ParticipantSessionWaitExclusionReceipt",
    ),
    "WaitControl": ("cayu.collaboration.waits", "WaitControl"),
    "CollaborationWaitLatchReceiver": (
        "cayu.collaboration._wait_coordinator",
        "CollaborationWaitLatchReceiver",
    ),
    "PeerContentAppendAuthorization": (
        "cayu.collaboration.peer_content",
        "PeerContentAppendAuthorization",
    ),
    "PeerAppendKey": ("cayu.collaboration.peer_content", "PeerAppendKey"),
    "PeerContentAppendRequest": (
        "cayu.collaboration.peer_content",
        "PeerContentAppendRequest",
    ),
    "PeerContentConflict": ("cayu.collaboration.peer_content", "PeerContentConflict"),
    "PeerContentOccurrence": (
        "cayu.collaboration.peer_content",
        "PeerContentOccurrence",
    ),
    "PeerContentPayload": ("cayu.collaboration.peer_content", "PeerContentPayload"),
    "PeerContentReceipt": ("cayu.collaboration.peer_content", "PeerContentReceipt"),
    "PeerContentExposureRequest": ("cayu.collaboration.peer_content", "PeerContentExposureRequest"),
    "PeerContentExposureItem": ("cayu.collaboration.peer_content", "PeerContentExposureItem"),
    "PeerContentExposureReceipt": ("cayu.collaboration.peer_content", "PeerContentExposureReceipt"),
    "PeerContentExposureReceiver": (
        "cayu.collaboration.peer_content",
        "PeerContentExposureReceiver",
    ),
    "RegisteredPeerContentExposureReceiver": (
        "cayu.collaboration.peer_content",
        "RegisteredPeerContentExposureReceiver",
    ),
    "PeerModelAttemptOrigin": ("cayu.collaboration.peer_content", "PeerModelAttemptOrigin"),
    "PeerContentUnavailable": (
        "cayu.collaboration.peer_content",
        "PeerContentUnavailable",
    ),
    "PeerDeliveryAttemptKey": (
        "cayu.collaboration.peer_content",
        "PeerDeliveryAttemptKey",
    ),
    "RequestDueCursor": ("cayu.collaboration.requests", "RequestDueCursor"),
    "RequestDuePage": ("cayu.collaboration.requests", "RequestDuePage"),
    "RequestRegistration": ("cayu.collaboration.request_access", "RequestRegistration"),
    "CollaborationRequest": ("cayu.collaboration.requests", "CollaborationRequest"),
    "RequestAlias": ("cayu.collaboration.requests", "RequestAlias"),
    "RequestRef": ("cayu.collaboration.requests", "RequestRef"),
    "RequestIntent": ("cayu.collaboration.requests", "RequestIntent"),
    "RequestSelection": ("cayu.collaboration.requests", "RequestSelection"),
    "RequestEvent": ("cayu.collaboration.requests", "RequestEvent"),
    "RequestCommand": ("cayu.collaboration.requests", "RequestCommand"),
    "RequestAdmissionCommand": ("cayu.collaboration.requests", "RequestAdmissionCommand"),
    "RequestAdmissionReceipt": ("cayu.collaboration.requests", "RequestAdmissionReceipt"),
    "RequestReceivingAuthorization": (
        "cayu.collaboration.request_access",
        "RequestReceivingAuthorization",
    ),
    "RequestReceivingOwner": ("cayu.collaboration.request_access", "RequestReceivingOwner"),
    "SessionExportRequestReceivingOwner": (
        "cayu.collaboration._session_export_participant",
        "SessionExportRequestReceivingOwner",
    ),
    "RequestProgressCommand": ("cayu.collaboration.requests", "RequestProgressCommand"),
    "RequestProgressReceipt": ("cayu.collaboration.requests", "RequestProgressReceipt"),
    "RequestOutcomeCommand": ("cayu.collaboration.requests", "RequestOutcomeCommand"),
    "RequestOutcomeReceipt": ("cayu.collaboration.requests", "RequestOutcomeReceipt"),
    "RequestObservation": ("cayu.collaboration.requests", "RequestObservation"),
    "RequestObservationReceipt": ("cayu.collaboration.requests", "RequestObservationReceipt"),
    "RequestObservationPage": ("cayu.collaboration.requests", "RequestObservationPage"),
    "RequestControl": ("cayu.collaboration.requests", "RequestControl"),
    "RequestControlCommand": ("cayu.collaboration.requests", "RequestControlCommand"),
    "RequestControlReceipt": ("cayu.collaboration.requests", "RequestControlReceipt"),
    "RequestReceipt": ("cayu.collaboration.requests", "RequestReceipt"),
    "RequestSnapshot": ("cayu.collaboration.requests", "RequestSnapshot"),
    "SessionExportRuntimeOrigin": ("cayu.collaboration.exports", "SessionExportRuntimeOrigin"),
    "CollaborationMandate": ("cayu.collaboration.mandates", "CollaborationMandate"),
    "InputChannel": ("cayu.collaboration.mandates", "InputChannel"),
    "MandateAccessContext": ("cayu.collaboration.mandates", "MandateAccessContext"),
    "MandateAction": ("cayu.collaboration.mandates", "MandateAction"),
    "MandateChain": ("cayu.collaboration.mandates", "MandateChain"),
    "MandateDenied": ("cayu.collaboration.mandates", "MandateDenied"),
    "MandateResolution": ("cayu.collaboration.mandates", "MandateResolution"),
    "MandateResolver": ("cayu.collaboration.mandates", "MandateResolver"),
    "MandateRestrictions": ("cayu.collaboration.mandates", "MandateRestrictions"),
    "PrincipalResolution": ("cayu.collaboration.mandates", "PrincipalResolution"),
    "ResourceSelector": ("cayu.collaboration.mandates", "ResourceSelector"),
    "ResourceSelectorOwner": ("cayu.collaboration.mandates", "ResourceSelectorOwner"),
    "ContentExposure": ("cayu.collaboration.releases", "ContentExposure"),
    "ContentReleaseExpectation": ("cayu.collaboration.releases", "ContentReleaseExpectation"),
    "ContentReleaseReader": ("cayu.collaboration.releases", "ContentReleaseReader"),
    "ContentReleaseReceipt": ("cayu.collaboration.releases", "ContentReleaseReceipt"),
    "ContentReleaseRequest": ("cayu.collaboration.releases", "ContentReleaseRequest"),
    "ReleasedContent": ("cayu.collaboration.releases", "ReleasedContent"),
    "SessionExportReconciliation": ("cayu.collaboration.exports", "SessionExportReconciliation"),
    "ExportLimits": ("cayu.collaboration.exports", "ExportLimits"),
    "SessionExportAcceptance": ("cayu.collaboration.exports", "SessionExportAcceptance"),
    "SessionExportAcceptanceReader": (
        "cayu.collaboration.exports",
        "SessionExportAcceptanceReader",
    ),
    "SessionExportAccessContext": ("cayu.collaboration.exports", "SessionExportAccessContext"),
    "SessionExportAction": ("cayu.collaboration.exports", "SessionExportAction"),
    "SessionExportAuthorization": ("cayu.collaboration.exports", "SessionExportAuthorization"),
    "SessionExportCapacityExceeded": (
        "cayu.collaboration.exports",
        "SessionExportCapacityExceeded",
    ),
    "SessionExportConflict": ("cayu.collaboration.exports", "SessionExportConflict"),
    "SessionExportDenied": ("cayu.collaboration.exports", "SessionExportDenied"),
    "SessionExportIntent": ("cayu.collaboration.exports", "SessionExportIntent"),
    "SessionExportNamespace": ("cayu.collaboration.exports", "SessionExportNamespace"),
    "SessionExportPolicy": ("cayu.collaboration.exports", "SessionExportPolicy"),
    "SessionExportProjector": ("cayu.collaboration.exports", "SessionExportProjector"),
    "SessionExportReceipt": ("cayu.collaboration.exports", "SessionExportReceipt"),
    "SessionExportRef": ("cayu.collaboration.exports", "SessionExportRef"),
    "SessionExportRegistration": ("cayu.collaboration.exports", "SessionExportRegistration"),
    "SessionExportRequest": ("cayu.collaboration.exports", "SessionExportRequest"),
    "SessionExportSettlementReceipt": (
        "cayu.collaboration.exports",
        "SessionExportSettlementReceipt",
    ),
    "SessionExportSettlementRequest": (
        "cayu.collaboration.exports",
        "SessionExportSettlementRequest",
    ),
    "SessionExportUnavailable": ("cayu.collaboration.exports", "SessionExportUnavailable"),
    "CollaborationHistoryUnavailable": (
        "cayu.collaboration.lifecycle",
        "CollaborationHistoryUnavailable",
    ),
    "CollaborationNamespaceRetired": (
        "cayu.collaboration.lifecycle",
        "CollaborationNamespaceRetired",
    ),
    "LifecycleCommand": ("cayu.collaboration.lifecycle", "LifecycleCommand"),
    "LifecycleIntent": ("cayu.collaboration.lifecycle", "LifecycleIntent"),
    "LifecycleReceipt": ("cayu.collaboration.lifecycle", "LifecycleReceipt"),
    "NamespaceInspection": ("cayu.collaboration.lifecycle", "NamespaceInspection"),
    "NamespacePrune": ("cayu.collaboration.lifecycle", "NamespacePrune"),
    "NamespaceRef": ("cayu.collaboration.lifecycle", "NamespaceRef"),
    "NamespaceRetire": ("cayu.collaboration.lifecycle", "NamespaceRetire"),
    "NamespaceRetirementEvidence": ("cayu.collaboration.lifecycle", "NamespaceRetirementEvidence"),
    "NamespaceRotate": ("cayu.collaboration.lifecycle", "NamespaceRotate"),
    "NamespaceSeal": ("cayu.collaboration.lifecycle", "NamespaceSeal"),
    "NamespaceSnapshot": ("cayu.collaboration.lifecycle", "NamespaceSnapshot"),
    "ParticipantLifecycleChange": ("cayu.collaboration.lifecycle", "ParticipantLifecycleChange"),
    "ParticipantCommand": ("cayu.collaboration.participants", "ParticipantCommand"),
    "CollaborationConflict": ("cayu.collaboration._contracts", "CollaborationConflict"),
    "CollaborationContractError": ("cayu.collaboration._contracts", "CollaborationContractError"),
    "CollaborationCapabilityUnavailable": (
        "cayu.collaboration._capabilities",
        "CollaborationCapabilityUnavailable",
    ),
    "CollaborationAccessContext": ("cayu.collaboration.access", "CollaborationAccessContext"),
    "CollaborationAccessDenied": ("cayu.collaboration.access", "CollaborationAccessDenied"),
    "CollaborationAccessGrant": ("cayu.collaboration.access", "CollaborationAccessGrant"),
    "CollaborationAccessPolicy": ("cayu.collaboration.access", "CollaborationAccessPolicy"),
    "CollaborationRegistration": ("cayu.collaboration.access", "CollaborationRegistration"),
    "CollaborationStore": ("cayu.collaboration.base", "CollaborationStore"),
    "InMemoryCollaborationStore": ("cayu.collaboration.memory", "InMemoryCollaborationStore"),
    "CollaborationBootstrap": ("cayu.collaboration.participants", "CollaborationBootstrap"),
    "CollaborationCapacityExceeded": (
        "cayu.collaboration.participants",
        "CollaborationCapacityExceeded",
    ),
    "CollaborationInitialization": (
        "cayu.collaboration.participants",
        "CollaborationInitialization",
    ),
    "CollaborationLimits": ("cayu.collaboration.participants", "CollaborationLimits"),
    "CollaborationNotInitialized": (
        "cayu.collaboration.participants",
        "CollaborationNotInitialized",
    ),
    "CollaborationUnavailable": ("cayu.collaboration.participants", "CollaborationUnavailable"),
    "ParticipantAlias": ("cayu.collaboration.participants", "ParticipantAlias"),
    "ParticipantAliasChange": ("cayu.collaboration.participants", "ParticipantAliasChange"),
    "ParticipantConfiguration": ("cayu.collaboration.participants", "ParticipantConfiguration"),
    "ParticipantConfigurationRef": (
        "cayu.collaboration.participants",
        "ParticipantConfigurationRef",
    ),
    "ParticipantConfigure": ("cayu.collaboration.participants", "ParticipantConfigure"),
    "ParticipantCreate": ("cayu.collaboration.participants", "ParticipantCreate"),
    "ParticipantCursor": ("cayu.collaboration.participants", "ParticipantCursor"),
    "ParticipantEvent": ("cayu.collaboration.participants", "ParticipantEvent"),
    "ParticipantEventCursor": ("cayu.collaboration.participants", "ParticipantEventCursor"),
    "ParticipantEventPage": ("cayu.collaboration.participants", "ParticipantEventPage"),
    "ParticipantInspection": ("cayu.collaboration.participants", "ParticipantInspection"),
    "ParticipantIntent": ("cayu.collaboration.participants", "ParticipantIntent"),
    "ParticipantObligation": ("cayu.collaboration.obligations", "ParticipantObligation"),
    "ParticipantObligationCursor": (
        "cayu.collaboration.obligations",
        "ParticipantObligationCursor",
    ),
    "ParticipantObligationPage": ("cayu.collaboration.obligations", "ParticipantObligationPage"),
    "ParticipantPage": ("cayu.collaboration.participants", "ParticipantPage"),
    "ParticipantReceipt": ("cayu.collaboration.participants", "ParticipantReceipt"),
    "ParticipantRef": ("cayu.collaboration.participants", "ParticipantRef"),
    "ParticipantSnapshot": ("cayu.collaboration.participants", "ParticipantSnapshot"),
    "PostgresCollaborationStore": (
        "cayu.storage.collaboration_postgres",
        "PostgresCollaborationStore",
    ),
    "SQLiteCollaborationStore": ("cayu.storage.collaboration_sqlite", "SQLiteCollaborationStore"),
}

PUBLIC_NAMES = tuple(EXPORTS)
