"""Lazy public participant-administration exports."""

EXPORTS: dict[str, tuple[str, str]] = {
    "ExportLimits": ("cayu.collaboration.exports", "ExportLimits"),
    "SessionExportAcceptance": ("cayu.collaboration.exports", "SessionExportAcceptance"),
    "SessionExportAcceptanceReader": (
        "cayu.collaboration.exports",
        "SessionExportAcceptanceReader",
    ),
    "SessionExportAccessContext": ("cayu.collaboration.exports", "SessionExportAccessContext"),
    "SessionExportAction": ("cayu.collaboration.exports", "SessionExportAction"),
    "SessionExportAuthorization": ("cayu.collaboration.exports", "SessionExportAuthorization"),
    "SessionExportCapacityExceeded": (
        "cayu.collaboration.exports",
        "SessionExportCapacityExceeded",
    ),
    "SessionExportConflict": ("cayu.collaboration.exports", "SessionExportConflict"),
    "SessionExportDenied": ("cayu.collaboration.exports", "SessionExportDenied"),
    "SessionExportIntent": ("cayu.collaboration.exports", "SessionExportIntent"),
    "SessionExportNamespace": ("cayu.collaboration.exports", "SessionExportNamespace"),
    "SessionExportPolicy": ("cayu.collaboration.exports", "SessionExportPolicy"),
    "SessionExportProjector": ("cayu.collaboration.exports", "SessionExportProjector"),
    "SessionExportReceipt": ("cayu.collaboration.exports", "SessionExportReceipt"),
    "SessionExportRef": ("cayu.collaboration.exports", "SessionExportRef"),
    "SessionExportRegistration": ("cayu.collaboration.exports", "SessionExportRegistration"),
    "SessionExportRequest": ("cayu.collaboration.exports", "SessionExportRequest"),
    "SessionExportSettlementReceipt": (
        "cayu.collaboration.exports",
        "SessionExportSettlementReceipt",
    ),
    "SessionExportSettlementRequest": (
        "cayu.collaboration.exports",
        "SessionExportSettlementRequest",
    ),
    "SessionExportUnavailable": ("cayu.collaboration.exports", "SessionExportUnavailable"),
    "CollaborationHistoryUnavailable": (
        "cayu.collaboration.lifecycle",
        "CollaborationHistoryUnavailable",
    ),
    "CollaborationNamespaceRetired": (
        "cayu.collaboration.lifecycle",
        "CollaborationNamespaceRetired",
    ),
    "LifecycleCommand": ("cayu.collaboration.lifecycle", "LifecycleCommand"),
    "LifecycleIntent": ("cayu.collaboration.lifecycle", "LifecycleIntent"),
    "LifecycleReceipt": ("cayu.collaboration.lifecycle", "LifecycleReceipt"),
    "NamespaceInspection": ("cayu.collaboration.lifecycle", "NamespaceInspection"),
    "NamespacePrune": ("cayu.collaboration.lifecycle", "NamespacePrune"),
    "NamespaceRef": ("cayu.collaboration.lifecycle", "NamespaceRef"),
    "NamespaceRetire": ("cayu.collaboration.lifecycle", "NamespaceRetire"),
    "NamespaceRetirementEvidence": ("cayu.collaboration.lifecycle", "NamespaceRetirementEvidence"),
    "NamespaceRotate": ("cayu.collaboration.lifecycle", "NamespaceRotate"),
    "NamespaceSeal": ("cayu.collaboration.lifecycle", "NamespaceSeal"),
    "NamespaceSnapshot": ("cayu.collaboration.lifecycle", "NamespaceSnapshot"),
    "ParticipantLifecycleChange": ("cayu.collaboration.lifecycle", "ParticipantLifecycleChange"),
    "ParticipantCommand": ("cayu.collaboration.participants", "ParticipantCommand"),
    "CollaborationConflict": ("cayu.collaboration._contracts", "CollaborationConflict"),
    "CollaborationContractError": ("cayu.collaboration._contracts", "CollaborationContractError"),
    "CollaborationCapabilityUnavailable": (
        "cayu.collaboration._capabilities",
        "CollaborationCapabilityUnavailable",
    ),
    "CollaborationAccessContext": ("cayu.collaboration.access", "CollaborationAccessContext"),
    "CollaborationAccessDenied": ("cayu.collaboration.access", "CollaborationAccessDenied"),
    "CollaborationAccessGrant": ("cayu.collaboration.access", "CollaborationAccessGrant"),
    "CollaborationAccessPolicy": ("cayu.collaboration.access", "CollaborationAccessPolicy"),
    "CollaborationRegistration": ("cayu.collaboration.access", "CollaborationRegistration"),
    "CollaborationStore": ("cayu.collaboration.base", "CollaborationStore"),
    "InMemoryCollaborationStore": ("cayu.collaboration.memory", "InMemoryCollaborationStore"),
    "CollaborationBootstrap": ("cayu.collaboration.participants", "CollaborationBootstrap"),
    "CollaborationCapacityExceeded": (
        "cayu.collaboration.participants",
        "CollaborationCapacityExceeded",
    ),
    "CollaborationInitialization": (
        "cayu.collaboration.participants",
        "CollaborationInitialization",
    ),
    "CollaborationLimits": ("cayu.collaboration.participants", "CollaborationLimits"),
    "CollaborationNotInitialized": (
        "cayu.collaboration.participants",
        "CollaborationNotInitialized",
    ),
    "CollaborationUnavailable": ("cayu.collaboration.participants", "CollaborationUnavailable"),
    "ParticipantAlias": ("cayu.collaboration.participants", "ParticipantAlias"),
    "ParticipantAliasChange": ("cayu.collaboration.participants", "ParticipantAliasChange"),
    "ParticipantConfiguration": ("cayu.collaboration.participants", "ParticipantConfiguration"),
    "ParticipantConfigurationRef": (
        "cayu.collaboration.participants",
        "ParticipantConfigurationRef",
    ),
    "ParticipantConfigure": ("cayu.collaboration.participants", "ParticipantConfigure"),
    "ParticipantCreate": ("cayu.collaboration.participants", "ParticipantCreate"),
    "ParticipantCursor": ("cayu.collaboration.participants", "ParticipantCursor"),
    "ParticipantEvent": ("cayu.collaboration.participants", "ParticipantEvent"),
    "ParticipantEventCursor": ("cayu.collaboration.participants", "ParticipantEventCursor"),
    "ParticipantEventPage": ("cayu.collaboration.participants", "ParticipantEventPage"),
    "ParticipantInspection": ("cayu.collaboration.participants", "ParticipantInspection"),
    "ParticipantIntent": ("cayu.collaboration.participants", "ParticipantIntent"),
    "ParticipantObligation": ("cayu.collaboration.obligations", "ParticipantObligation"),
    "ParticipantObligationCursor": (
        "cayu.collaboration.obligations",
        "ParticipantObligationCursor",
    ),
    "ParticipantObligationPage": ("cayu.collaboration.obligations", "ParticipantObligationPage"),
    "ParticipantPage": ("cayu.collaboration.participants", "ParticipantPage"),
    "ParticipantReceipt": ("cayu.collaboration.participants", "ParticipantReceipt"),
    "ParticipantRef": ("cayu.collaboration.participants", "ParticipantRef"),
    "ParticipantSnapshot": ("cayu.collaboration.participants", "ParticipantSnapshot"),
    "PostgresCollaborationStore": (
        "cayu.storage.collaboration_postgres",
        "PostgresCollaborationStore",
    ),
    "SQLiteCollaborationStore": ("cayu.storage.collaboration_sqlite", "SQLiteCollaborationStore"),
}

PUBLIC_NAMES = tuple(EXPORTS)
