"""Model provider contracts."""

from cayu.providers.anthropic import (
    AnthropicAPIError,
    AnthropicError,
    AnthropicProtocolError,
    AnthropicProvider,
    AnthropicTransport,
    HttpxAnthropicTransport,
    anthropic_response_events,
    build_anthropic_payload,
)
from cayu.providers.base import (
    ModelCompletion,
    ModelFinishReason,
    ModelProvider,
    ModelRequest,
    ModelStreamEvent,
    ModelStreamEventType,
    copy_model_stream_event,
    normalize_model_completion,
)
from cayu.providers.cache import CacheBreakpoint, CachePolicy
from cayu.providers.chat_completions import (
    ChatCompletionsAPIError,
    ChatCompletionsError,
    ChatCompletionsProtocolError,
    ChatCompletionsProvider,
    ChatCompletionsTransport,
    HttpxChatCompletionsTransport,
    build_chat_completions_payload,
    chat_completions_stream_events,
)
from cayu.providers.openai import (
    HttpxOpenAITransport,
    OpenAIAPIError,
    OpenAIError,
    OpenAIProtocolError,
    OpenAIProvider,
    OpenAITransport,
    build_openai_payload,
    openai_response_events,
)

__all__ = [
    "AnthropicAPIError",
    "AnthropicError",
    "AnthropicProtocolError",
    "AnthropicProvider",
    "AnthropicTransport",
    "CacheBreakpoint",
    "CachePolicy",
    "ChatCompletionsAPIError",
    "ChatCompletionsError",
    "ChatCompletionsProtocolError",
    "ChatCompletionsProvider",
    "ChatCompletionsTransport",
    "HttpxAnthropicTransport",
    "HttpxChatCompletionsTransport",
    "HttpxOpenAITransport",
    "ModelCompletion",
    "ModelFinishReason",
    "ModelProvider",
    "ModelRequest",
    "ModelStreamEvent",
    "ModelStreamEventType",
    "OpenAIAPIError",
    "OpenAIError",
    "OpenAIProtocolError",
    "OpenAIProvider",
    "OpenAITransport",
    "anthropic_response_events",
    "build_anthropic_payload",
    "build_chat_completions_payload",
    "build_openai_payload",
    "chat_completions_stream_events",
    "copy_model_stream_event",
    "normalize_model_completion",
    "openai_response_events",
]
