"""Explicit public exports; implementations load on first access."""

EXPORTS: dict[str, tuple[str, str]] = {
    "AuxiliaryInferenceUnsupportedError": (
        "cayu.providers.base",
        "AuxiliaryInferenceUnsupportedError",
    ),
    "ModelResponse": ("cayu.providers.response", "ModelResponse"),
    "AnthropicAPIError": ("cayu.providers.anthropic", "AnthropicAPIError"),
    "AnthropicContextOverflowError": ("cayu.providers.anthropic", "AnthropicContextOverflowError"),
    "AnthropicError": ("cayu.providers.anthropic", "AnthropicError"),
    "AnthropicProtocolError": ("cayu.providers.anthropic", "AnthropicProtocolError"),
    "AnthropicProvider": ("cayu.providers.anthropic", "AnthropicProvider"),
    "AnthropicTransport": ("cayu.providers.anthropic", "AnthropicTransport"),
    "BedrockAPIError": ("cayu.providers.bedrock", "BedrockAPIError"),
    "BedrockContextOverflowError": ("cayu.providers.bedrock", "BedrockContextOverflowError"),
    "BedrockError": ("cayu.providers.bedrock", "BedrockError"),
    "BedrockProtocolError": ("cayu.providers.bedrock", "BedrockProtocolError"),
    "BedrockProvider": ("cayu.providers.bedrock", "BedrockProvider"),
    "CacheBreakpoint": ("cayu.providers.cache", "CacheBreakpoint"),
    "CachePolicy": ("cayu.providers.cache", "CachePolicy"),
    "ChatCompletionsAPIError": ("cayu.providers.chat_completions", "ChatCompletionsAPIError"),
    "ChatCompletionsContextOverflowError": (
        "cayu.providers.chat_completions",
        "ChatCompletionsContextOverflowError",
    ),
    "ChatCompletionsError": ("cayu.providers.chat_completions", "ChatCompletionsError"),
    "ChatCompletionsProtocolError": (
        "cayu.providers.chat_completions",
        "ChatCompletionsProtocolError",
    ),
    "ChatCompletionsProvider": ("cayu.providers.chat_completions", "ChatCompletionsProvider"),
    "ChatCompletionsTransport": ("cayu.providers.chat_completions", "ChatCompletionsTransport"),
    "DEFAULT_MAX_CONCURRENT_PROVIDER_STREAMS": (
        "cayu.providers.deadlines",
        "DEFAULT_MAX_CONCURRENT_PROVIDER_STREAMS",
    ),
    "DEFAULT_OPENAI_SUBSCRIPTION_BASE_URL": (
        "cayu.providers.openai_subscription",
        "DEFAULT_OPENAI_SUBSCRIPTION_BASE_URL",
    ),
    "HostedToolCapabilityError": ("cayu.providers.hosted", "HostedToolCapabilityError"),
    "HttpxAnthropicTransport": ("cayu.providers.anthropic", "HttpxAnthropicTransport"),
    "HttpxChatCompletionsTransport": (
        "cayu.providers.chat_completions",
        "HttpxChatCompletionsTransport",
    ),
    "HttpxOpenAISubscriptionOAuthTransport": (
        "cayu.providers.openai_subscription",
        "HttpxOpenAISubscriptionOAuthTransport",
    ),
    "HttpxOpenAITransport": ("cayu.providers.openai", "HttpxOpenAITransport"),
    "HttpxVertexTransport": ("cayu.providers.vertex", "HttpxVertexTransport"),
    "InputTokenCountConfidence": ("cayu.providers.base", "InputTokenCountConfidence"),
    "InputTokenCountMethod": ("cayu.providers.base", "InputTokenCountMethod"),
    "InputTokenCountResult": ("cayu.providers.base", "InputTokenCountResult"),
    "ModelCompletion": ("cayu.providers.base", "ModelCompletion"),
    "ModelContextOverflowError": ("cayu.providers.base", "ModelContextOverflowError"),
    "ModelContextPressureProfile": ("cayu.providers.base", "ModelContextPressureProfile"),
    "ModelFinishReason": ("cayu.providers.base", "ModelFinishReason"),
    "ModelProvider": ("cayu.providers.base", "ModelProvider"),
    "ModelProviderError": ("cayu.providers.base", "ModelProviderError"),
    "ModelRequest": ("cayu.providers.base", "ModelRequest"),
    "ModelStreamDeadlineError": ("cayu.providers.base", "ModelStreamDeadlineError"),
    "ModelStreamEvent": ("cayu.providers.base", "ModelStreamEvent"),
    "ModelStreamEventType": ("cayu.providers.base", "ModelStreamEventType"),
    "NativeStructuredOutputSchemaInvalid": (
        "cayu.providers.base",
        "NativeStructuredOutputSchemaInvalid",
    ),
    "OpenAIAPIError": ("cayu.providers.openai", "OpenAIAPIError"),
    "OpenAIBackgroundTransport": ("cayu.providers.openai", "OpenAIBackgroundTransport"),
    "OpenAIContextOverflowError": ("cayu.providers.openai", "OpenAIContextOverflowError"),
    "OpenAIError": ("cayu.providers.openai", "OpenAIError"),
    "OpenAIProtocolError": ("cayu.providers.openai", "OpenAIProtocolError"),
    "OpenAIProvider": ("cayu.providers.openai", "OpenAIProvider"),
    "OpenAISubscriptionAuth": ("cayu.providers.openai_subscription", "OpenAISubscriptionAuth"),
    "OpenAISubscriptionAuthError": (
        "cayu.providers.openai_subscription",
        "OpenAISubscriptionAuthError",
    ),
    "OpenAISubscriptionAuthStore": (
        "cayu.providers.openai_subscription",
        "OpenAISubscriptionAuthStore",
    ),
    "OpenAISubscriptionCredentials": (
        "cayu.providers.openai_subscription",
        "OpenAISubscriptionCredentials",
    ),
    "OpenAISubscriptionProvider": (
        "cayu.providers.openai_subscription",
        "OpenAISubscriptionProvider",
    ),
    "OpenAITransport": ("cayu.providers.openai", "OpenAITransport"),
    "OpenAIUnsupportedSearchSourceError": (
        "cayu.providers.openai",
        "OpenAIUnsupportedSearchSourceError",
    ),
    "OpenAIWebSearch": ("cayu.providers.hosted", "OpenAIWebSearch"),
    "PROVIDER_OPERATION_RECOVERY_OPAQUE_MAX_BYTES": (
        "cayu.providers.operations",
        "PROVIDER_OPERATION_RECOVERY_OPAQUE_MAX_BYTES",
    ),
    "ProviderDeadlineKind": ("cayu.providers.deadlines", "ProviderDeadlineKind"),
    "ProviderErrorCapture": ("cayu.providers.diagnostics", "ProviderErrorCapture"),
    "ProviderOperationAdapter": ("cayu.providers.operations", "ProviderOperationAdapter"),
    "ProviderOperationCancellationSupport": (
        "cayu.providers.operations",
        "ProviderOperationCancellationSupport",
    ),
    "ProviderOperationConnection": ("cayu.providers.operations", "ProviderOperationConnection"),
    "ProviderOperationMalformedError": (
        "cayu.providers.operations",
        "ProviderOperationMalformedError",
    ),
    "ProviderOperationMode": ("cayu.providers.operations", "ProviderOperationMode"),
    "ProviderOperationRecoveryMetadata": (
        "cayu.providers.operations",
        "ProviderOperationRecoveryMetadata",
    ),
    "ProviderOperationSnapshot": ("cayu.providers.operations", "ProviderOperationSnapshot"),
    "ProviderOperationStartIdempotencySupport": (
        "cayu.providers.operations",
        "ProviderOperationStartIdempotencySupport",
    ),
    "ProviderOperationStartRecoveryRequest": (
        "cayu.providers.operations",
        "ProviderOperationStartRecoveryRequest",
    ),
    "ProviderOperationStartRequest": ("cayu.providers.operations", "ProviderOperationStartRequest"),
    "ProviderOperationState": ("cayu.providers.operations", "ProviderOperationState"),
    "ProviderOperationStatus": ("cayu.providers.operations", "ProviderOperationStatus"),
    "ProviderProgressKind": ("cayu.providers.deadlines", "ProviderProgressKind"),
    "ProviderStreamDeadlineEvidence": (
        "cayu.providers.deadlines",
        "ProviderStreamDeadlineEvidence",
    ),
    "ProviderStreamDeadlines": ("cayu.providers.deadlines", "ProviderStreamDeadlines"),
    "RequestCacheProjection": ("cayu.providers.cache", "RequestCacheProjection"),
    "TargetedToolProjectionRequest": ("cayu.providers.base", "TargetedToolProjectionRequest"),
    "ToolDiscoveryProjectionRequest": ("cayu.providers.base", "ToolDiscoveryProjectionRequest"),
    "ToolDiscoveryProjectionResult": ("cayu.providers.base", "ToolDiscoveryProjectionResult"),
    "UsageDialect": ("cayu.providers.base", "UsageDialect"),
    "VertexAPIError": ("cayu.providers.vertex", "VertexAPIError"),
    "VertexContextOverflowError": ("cayu.providers.vertex", "VertexContextOverflowError"),
    "VertexError": ("cayu.providers.vertex", "VertexError"),
    "VertexProtocolError": ("cayu.providers.vertex", "VertexProtocolError"),
    "VertexProvider": ("cayu.providers.vertex", "VertexProvider"),
    "VertexTransport": ("cayu.providers.vertex", "VertexTransport"),
    "anthropic_response_events": ("cayu.providers.anthropic", "anthropic_response_events"),
    "anthropic_stream_events": ("cayu.providers.anthropic", "anthropic_stream_events"),
    "bedrock_billing_identity": ("cayu.providers.bedrock", "bedrock_billing_identity"),
    "bedrock_converse_stream_events": ("cayu.providers.bedrock", "bedrock_converse_stream_events"),
    "build_anthropic_payload": ("cayu.providers.anthropic", "build_anthropic_payload"),
    "build_bedrock_converse_payload": ("cayu.providers.bedrock", "build_bedrock_converse_payload"),
    "build_chat_completions_payload": (
        "cayu.providers.chat_completions",
        "build_chat_completions_payload",
    ),
    "build_openai_embedding_payload": ("cayu.providers.openai", "build_openai_embedding_payload"),
    "build_openai_payload": ("cayu.providers.openai", "build_openai_payload"),
    "capture_provider_errors": ("cayu.providers.diagnostics", "capture_provider_errors"),
    "chat_completions_stream_events": (
        "cayu.providers.chat_completions",
        "chat_completions_stream_events",
    ),
    "completed_bedrock_billing_identity": (
        "cayu.providers.bedrock",
        "completed_bedrock_billing_identity",
    ),
    "copy_input_token_count_result": ("cayu.providers.base", "copy_input_token_count_result"),
    "copy_model_context_pressure_profile": (
        "cayu.providers.base",
        "copy_model_context_pressure_profile",
    ),
    "copy_model_stream_event": ("cayu.providers.base", "copy_model_stream_event"),
    "copy_provider_operation_connection": (
        "cayu.providers.operations",
        "copy_provider_operation_connection",
    ),
    "copy_provider_operation_snapshot": (
        "cayu.providers.operations",
        "copy_provider_operation_snapshot",
    ),
    "copy_provider_operation_state": ("cayu.providers.operations", "copy_provider_operation_state"),
    "copy_usage_dialect": ("cayu.providers.base", "copy_usage_dialect"),
    "normalize_model_completion": ("cayu.providers.base", "normalize_model_completion"),
    "openai_embedding_result": ("cayu.providers.openai", "openai_embedding_result"),
    "openai_response_events": ("cayu.providers.openai", "openai_response_events"),
    "preflight_openai_native_structured_output_schema": (
        "cayu.providers.openai",
        "preflight_openai_native_structured_output_schema",
    ),
}

PUBLIC_NAMES = [
    "AuxiliaryInferenceUnsupportedError",
    "ModelResponse",
    "AnthropicAPIError",
    "AnthropicContextOverflowError",
    "AnthropicError",
    "AnthropicProtocolError",
    "AnthropicProvider",
    "AnthropicTransport",
    "BedrockAPIError",
    "BedrockContextOverflowError",
    "BedrockError",
    "BedrockProtocolError",
    "BedrockProvider",
    "CacheBreakpoint",
    "CachePolicy",
    "ChatCompletionsAPIError",
    "ChatCompletionsContextOverflowError",
    "ChatCompletionsError",
    "ChatCompletionsProtocolError",
    "ChatCompletionsProvider",
    "ChatCompletionsTransport",
    "DEFAULT_MAX_CONCURRENT_PROVIDER_STREAMS",
    "DEFAULT_OPENAI_SUBSCRIPTION_BASE_URL",
    "HostedToolCapabilityError",
    "HttpxAnthropicTransport",
    "HttpxChatCompletionsTransport",
    "HttpxOpenAISubscriptionOAuthTransport",
    "HttpxOpenAITransport",
    "HttpxVertexTransport",
    "InputTokenCountConfidence",
    "InputTokenCountMethod",
    "InputTokenCountResult",
    "ModelCompletion",
    "ModelContextOverflowError",
    "ModelContextPressureProfile",
    "ModelFinishReason",
    "ModelProvider",
    "ModelProviderError",
    "ModelRequest",
    "ModelStreamDeadlineError",
    "ModelStreamEvent",
    "ModelStreamEventType",
    "NativeStructuredOutputSchemaInvalid",
    "OpenAIAPIError",
    "OpenAIBackgroundTransport",
    "OpenAIContextOverflowError",
    "OpenAIError",
    "OpenAIProtocolError",
    "OpenAIProvider",
    "OpenAISubscriptionAuth",
    "OpenAISubscriptionAuthError",
    "OpenAISubscriptionAuthStore",
    "OpenAISubscriptionCredentials",
    "OpenAISubscriptionProvider",
    "OpenAITransport",
    "OpenAIUnsupportedSearchSourceError",
    "OpenAIWebSearch",
    "PROVIDER_OPERATION_RECOVERY_OPAQUE_MAX_BYTES",
    "ProviderDeadlineKind",
    "ProviderErrorCapture",
    "ProviderOperationAdapter",
    "ProviderOperationCancellationSupport",
    "ProviderOperationConnection",
    "ProviderOperationMalformedError",
    "ProviderOperationMode",
    "ProviderOperationRecoveryMetadata",
    "ProviderOperationSnapshot",
    "ProviderOperationStartIdempotencySupport",
    "ProviderOperationStartRecoveryRequest",
    "ProviderOperationStartRequest",
    "ProviderOperationState",
    "ProviderOperationStatus",
    "ProviderProgressKind",
    "ProviderStreamDeadlineEvidence",
    "ProviderStreamDeadlines",
    "RequestCacheProjection",
    "TargetedToolProjectionRequest",
    "ToolDiscoveryProjectionRequest",
    "ToolDiscoveryProjectionResult",
    "UsageDialect",
    "VertexAPIError",
    "VertexContextOverflowError",
    "VertexError",
    "VertexProtocolError",
    "VertexProvider",
    "VertexTransport",
    "anthropic_response_events",
    "anthropic_stream_events",
    "bedrock_billing_identity",
    "bedrock_converse_stream_events",
    "build_anthropic_payload",
    "build_bedrock_converse_payload",
    "build_chat_completions_payload",
    "build_openai_embedding_payload",
    "build_openai_payload",
    "capture_provider_errors",
    "chat_completions_stream_events",
    "completed_bedrock_billing_identity",
    "copy_input_token_count_result",
    "copy_model_context_pressure_profile",
    "copy_model_stream_event",
    "copy_provider_operation_connection",
    "copy_provider_operation_snapshot",
    "copy_provider_operation_state",
    "copy_usage_dialect",
    "normalize_model_completion",
    "openai_embedding_result",
    "openai_response_events",
    "preflight_openai_native_structured_output_schema",
]
