"""Static OpenAI validation identities; values are part of the diagnostic API.

Keep existing reason codes stable when editing parser messages. Add new checks
here explicitly. No response value, exception text, or dynamic path is copied.
"""

# reason -> (stage, optional schema path); [] denotes an unspecified array index.
_PROTOCOL_DIAGNOSTICS: dict[str, tuple[str, str | None]] = {
    "unspecified": ("unknown", None),
    "background_stream_ended_early": ("recovery", None),
    "a_successful_search_tools_result_requires_the_canonical_structured_payload": ("request", None),
    "an_active_targeted_tool_projection_requires_one_exact_acquisition_marker": ("request", None),
    "annotation_added_requires_annotation_object": ("response", None),
    "annotation_added_requires_non_negative_content_index": ("response", None),
    "assistant_messages_can_only_contain_text_tool_call_provider_state_thinking_hosted_tool_call_and_citation_parts": (
        "request",
        None,
    ),
    "assistant_text_output_requires_a_text_part": ("request", None),
    "background_function_call_added_item_is_malformed": ("recovery", None),
    "background_operation_uses_an_unknown_stream_protocol": ("recovery", None),
    "background_reasoning_output_item_added_was_repeated": ("recovery", None),
    "background_reasoning_output_item_done_identity_conflicts_with_added_item": ("recovery", None),
    "background_reasoning_output_item_done_was_repeated": ("recovery", None),
    "background_recovery_metadata_has_an_invalid_targeted_tool_marker_id": ("recovery", None),
    "background_recovery_metadata_has_invalid_discovery_tool_names": ("recovery", None),
    "background_recovery_metadata_requires_a_nonnegative_sequence_number": ("recovery", None),
    "background_response_completed_with_unfinished_output_items": ("recovery", None),
    "background_sequence_number_did_not_advance": ("recovery", None),
    "background_start_must_begin_with_response_created": ("recovery", None),
    "background_stream_events_require_a_nonnegative_sequence_number": ("recovery", None),
    "background_tool_search_call_added_item_is_malformed": ("recovery", None),
    "background_tool_search_call_output_identity_mismatch": ("recovery", None),
    "background_tool_search_output_has_no_unique_adjacent_server_call": ("recovery", None),
    "cayu_s_hosted_tool_search_projection_accepts_only_loaded_functions_item_tool_is_unsupported": (
        "response",
        None,
    ),
    "citation_has_invalid_text_offsets": ("response", None),
    "citation_title_must_be_a_bounded_string": ("response", None),
    "client_tool_search_call_added_requires_exact_identities": ("response", None),
    "client_tool_search_replay_requires_the_provider_issued_item_id": ("request", None),
    "completed_function_call_state_is_malformed": ("response", None),
    "completed_hosted_search_replay_requires_action_evidence": ("request", None),
    "completed_reasoning_index_is_malformed": ("response", None),
    "completed_tool_search_state_is_malformed": ("response", None),
    "content_annotations_must_be_a_list": ("response", None),
    "content_requires_string": ("response", None),
    "embedding_item_must_be_an_object": ("response", None),
    "embedding_item_requires_index": ("response", None),
    "embedding_item_requires_vector": ("response", None),
    "embedding_item_vector_must_be_a_number": ("response", None),
    "embedding_response_count_did_not_match_request": ("response", None),
    "embedding_response_data_must_be_a_list": ("response", None),
    "embedding_response_has_unexpected_object": ("response", None),
    "embedding_response_indexes_did_not_match_request": ("response", None),
    "embedding_response_must_be_a_json_object": ("response", None),
    "embedding_response_requires_model": ("response", None),
    "embedding_usage_must_be_an_object": ("response", None),
    "embedding_usage_requires_nonnegative": ("response", None),
    "fallback_message_content_conflicts_with_streamed_visible_text": ("stream", None),
    "function_call_arguments_delta_arrived_before_output_item_added": ("stream", None),
    "function_call_arguments_delta_item_id_mismatch": ("stream", None),
    "function_call_arguments_delta_requires_string_delta": ("stream", None),
    "function_call_arguments_done_arrived_before_output_item_added": ("stream", None),
    "function_call_arguments_done_item_id_mismatch": ("response", None),
    "function_call_item_arguments_must_decode_to_an_object": ("response", None),
    "function_call_item_arguments_were_not_valid_json": ("response", None),
    "function_call_item_requires_nonblank_call_id": ("response", None),
    "function_call_item_requires_nonblank_name": ("response", None),
    "function_call_item_requires_string_arguments": ("response", None),
    "function_call_output_item_added_was_repeated": ("stream", None),
    "function_call_output_item_done_arrived_before_arguments_completion": ("stream", None),
    "function_call_output_item_done_conflicts_with_streamed_arguments": ("stream", None),
    "hosted_loaded_function_added_an_output_schema": ("response", None),
    "hosted_loaded_function_changed_strict_mode": ("response", None),
    "hosted_loaded_function_has_unsupported_fields": ("response", None),
    "hosted_loaded_function_is_malformed": ("response", None),
    "hosted_loaded_function_lost_defer_loading_authority": ("response", None),
    "hosted_loaded_function_requires_a_nonblank_name": ("response", None),
    "hosted_loaded_tools_are_not_bounded_and_canonical": ("response", None),
    "hosted_search_event_requires_a_call_identity": ("response", None),
    "hosted_tool_search_call_added_requires_null_call_id": ("response", None),
    "hosted_tool_search_call_item_arguments_are_oversized": ("response", None),
    "hosted_tool_search_call_item_arguments_must_be_an_object": ("response", None),
    "hosted_tool_search_call_item_has_invalid_id": ("response", None),
    "hosted_tool_search_call_item_has_unsupported_fields": ("response", None),
    "hosted_tool_search_call_item_must_be_completed": ("response", None),
    "hosted_tool_search_call_item_requires_null_call_id": ("response", None),
    "hosted_tool_search_call_must_be_followed_by_tool_search_output": ("response", None),
    "hosted_tool_search_cannot_mix_client_and_server_search_calls": ("response", None),
    "hosted_tool_search_function_calls_must_follow_the_loaded_output": ("response", None),
    "hosted_tool_search_must_contain_one_adjacent_call_output_pair": ("response", None),
    "hosted_tool_search_output_item_has_invalid_id": ("response", None),
    "hosted_tool_search_output_item_has_unsupported_fields": ("response", None),
    "hosted_tool_search_output_item_must_be_completed": ("response", None),
    "hosted_tool_search_output_item_must_use_server_execution": ("response", None),
    "hosted_tool_search_output_item_requires_a_tools_array": ("response", None),
    "hosted_tool_search_output_item_requires_null_call_id": ("response", None),
    "hosted_tool_search_output_must_follow_its_server_search_call": ("response", None),
    "hosted_tool_search_output_state_requires_hosted_tool_search": ("request", None),
    "hosted_tool_search_recovery_state_is_malformed": ("recovery", None),
    "hosted_tool_search_replay_called_a_deferred_function_outside_the_loaded_subset": (
        "request",
        None,
    ),
    "hosted_tool_search_replay_cannot_contain_a_client_search_call": ("request", None),
    "hosted_tool_search_replay_contains_an_orphan_loaded_output": ("request", None),
    "hosted_tool_search_replay_contains_multiple_search_pairs_in_one_response": ("request", None),
    "hosted_tool_search_replay_function_calls_must_follow_the_loaded_output": ("request", None),
    "hosted_tool_search_replay_loaded_a_function_outside_the_current_candidate_projection": (
        "request",
        None,
    ),
    "hosted_tool_search_replay_loaded_authority_has_no_exact_retained_output": ("request", None),
    "hosted_tool_search_replay_requires_an_adjacent_call_output_pair": ("request", None),
    "input_token_count_response_has_unexpected_object": ("response", None),
    "input_token_count_response_must_be_a_json_object": ("response", None),
    "input_token_count_response_requires_input_tokens": ("response", None),
    "message_output_content_must_be_an_object": ("response", None),
    "message_output_item_content_must_be_a_list": ("response", None),
    "message_output_item_done_conflicts_with_streamed_text": ("stream", None),
    "message_output_item_done_omitted_streamed_text_content": ("stream", None),
    "message_output_item_must_have_assistant_role": ("response", None),
    "missing_resolved_file_attachment": ("request", None),
    "external_url_must_be_bounded": ("response", None),
    "external_url_requires_http_or_https": ("response", None),
    "neutral_replay_cannot_attach_a_citation_without_assistant_text": ("request", None),
    "neutral_replay_citation_does_not_belong_to_its_assistant_text_item": ("request", None),
    "neutral_replay_contains_duplicate_tool_search_call_identity": ("request", None),
    "neutral_replay_has_tool_search_provider_state_without_terminal_tool_evidence": (
        "request",
        None,
    ),
    "output_annotation_must_be_an_object": ("response", None),
    "output_item_added_has_invalid_lifecycle_status": ("stream", None),
    "output_item_added_requires_item_object": ("stream", None),
    "output_item_added_requires_nonblank_id": ("stream", None),
    "output_item_done_identity_conflicts_with_added_item": ("stream", None),
    "output_item_done_item_must_be_completed": ("stream", None),
    "output_item_done_requires_item_object": ("stream", None),
    "output_item_done_was_repeated": ("stream", None),
    "output_item_must_be_an_object": ("response", None),
    "output_text_delta_must_be_a_string": ("stream", None),
    "pending_function_call_index_is_malformed": ("recovery", None),
    "pending_function_call_state_is_malformed": ("recovery", None),
    "pending_reasoning_index_is_malformed": ("recovery", None),
    "pending_reasoning_state_is_malformed": ("recovery", None),
    "pending_tool_search_state_is_malformed": ("recovery", None),
    "provider_state_must_be_an_object": ("request", None),
    "reasoning_delta_must_be_a_string": ("stream", None),
    "reasoning_output_item_added_has_invalid_lifecycle_status": ("stream", None),
    "reasoning_output_item_added_requires_nonblank_id": ("stream", None),
    "reasoning_output_item_added_was_repeated": ("stream", None),
    "reasoning_output_item_done_requires_nonblank_id": ("stream", None),
    "reasoning_output_item_encrypted_content_must_be_a_string": ("response", None),
    "reasoning_output_item_summary_must_be_a_list": ("response", None),
    "recovery_parser_state_is_malformed": ("recovery", None),
    "recovery_parser_state_must_be_an_object": ("recovery", None),
    "refusal_delta_must_be_a_string": ("stream", None),
    "replayable_output_item_added_was_repeated": ("stream", None),
    "response_contains_too_many_tool_search_calls": ("response", None),
    "response_created_requires_a_nonblank_response_id": ("response", None),
    "response_created_requires_queued_or_in_progress_status": ("response", None),
    "response_end_turn_must_be_a_boolean_or_null": ("response", None),
    "response_must_be_a_json_object": ("response", None),
    "response_field_must_be_a_string": ("response", None),
    "response_output_must_be_a_list": ("response", None),
    "response_usage_must_be_an_object": ("response", None),
    "search_tools_result_conflicts_with_the_trusted_loaded_definition": ("request", None),
    "search_tools_result_contains_an_unready_tool": ("request", None),
    "search_tools_result_match_is_not_canonical": ("request", None),
    "search_tools_result_matches_must_be_a_bounded_list": ("request", None),
    "search_tools_result_tool_names_must_be_unique": ("request", None),
    "server_completion_lost_its_provider_state": ("response", None),
    "server_completion_requires_one_exact_response_reference": ("response", None),
    "stream_contains_multiple_hosted_tool_search_calls": ("stream", None),
    "stream_contains_too_many_tool_search_calls": ("stream", None),
    "stream_emitted_conflicting_response_identities": ("stream", None),
    "stream_event_must_be_a_json_object": ("stream", None),
    "stream_event_output_index_must_be_non_negative": ("stream", None),
    "stream_event_requires_integer_output_index": ("stream", None),
    "stream_field_must_be_a_string": ("stream", None),
    "stream_terminal_event_requires_response_object": ("stream", None),
    "streaming_function_call_is_missing_arguments": ("stream", None),
    "streaming_function_call_is_missing_required_identity": ("stream", None),
    "streaming_response_completed_with_unfinished_function_calls": ("stream", None),
    "streaming_response_completed_with_unfinished_output_items": ("stream", None),
    "streaming_response_completed_with_unfinished_reasoning_items": ("stream", None),
    "streaming_response_completed_with_unfinished_tool_search_calls": ("stream", None),
    "streaming_response_completed_with_unfinished_web_search_calls": ("stream", None),
    "streaming_response_ended_before_response_completed": ("stream", None),
    "terminal_function_call_evidence_conflicts_with_lifecycle_evidence": ("stream", None),
    "terminal_function_call_evidence_conflicts_with_recovered_lifecycle_evidence": ("stream", None),
    "terminal_response_contains_a_nonterminal_web_search_call": ("stream", None),
    "terminal_response_contains_too_many_tool_search_calls": ("stream", None),
    "terminal_response_omitted_completed_web_search_lifecycle_evidence": ("stream", None),
    "terminal_tool_search_evidence_conflicts_with_lifecycle_evidence": ("stream", None),
    "terminal_tool_search_output_conflicts_with_lifecycle_evidence": ("stream", None),
    "terminal_tool_search_output_has_no_hosted_search_call": ("stream", None),
    "terminal_web_search_evidence_conflicts_with_lifecycle_evidence": ("stream", None),
    "terminal_web_search_identity_conflicts_with_lifecycle_evidence": ("stream", None),
    "terminal_web_search_output_conflicts_with_lifecycle_item_identity": ("stream", None),
    "text_delta_must_be_a_string": ("stream", None),
    "the_targeted_tool_acquisition_marker_is_not_canonical": ("request", None),
    "tool_call_arguments_must_be_an_object": ("request", None),
    "tool_messages_can_only_contain_tool_result_parts": ("request", None),
    "tool_search_call_added_has_unsupported_execution": ("response", None),
    "tool_search_call_item_arguments_must_be_an_object": ("response", None),
    "tool_search_call_item_has_an_invalid_limit": ("response", None),
    "tool_search_call_item_has_unsupported_arguments": ("response", None),
    "tool_search_call_item_has_unsupported_execution": ("response", None),
    "tool_search_call_item_must_be_completed": ("response", None),
    "tool_search_call_item_requires_a_bounded_query": ("response", None),
    "tool_search_call_item_requires_nonblank_call_id": ("response", None),
    "tool_search_call_item_requires_nonblank_id": ("response", None),
    "tool_search_call_output_identity_mismatch": ("response", None),
    "tool_search_call_output_item_added_must_be_in_progress": ("stream", None),
    "tool_search_call_output_item_added_was_repeated": ("stream", None),
    "tool_search_call_output_item_done_arrived_before_added": ("stream", None),
    "tool_search_call_output_item_done_conflicts_with_lifecycle_evidence": ("stream", None),
    "tool_search_call_state_requires_an_active_tool_search_projection": ("request", None),
    "tool_search_output_has_no_adjacent_hosted_search_call": ("response", None),
    "tool_search_output_has_no_matching_pending_search_call": ("request", None),
    "tool_search_output_has_no_unique_adjacent_server_call": ("response", None),
    "tool_search_output_output_item_done_conflicts_with_lifecycle_evidence": ("stream", None),
    "tool_search_provider_state_conflicts_with_neutral_tool_call_replay": ("request", None),
    "tool_search_replay_has_a_call_without_its_output": ("request", None),
    "tool_search_replay_repeats_a_provider_call_identity": ("request", None),
    "tool_search_replay_repeats_an_assistant_call_identity": ("request", None),
    "tool_search_replay_requires_matching_provider_and_assistant_calls": ("request", None),
    "unsupported_cayu_message_role": ("request", None),
    "unsupported_file_attachment_kind": ("request", None),
    "unsupported_openai_fallback_output_item_type": ("response", None),
    "unsupported_openai_message_output_content_type": ("response", None),
    "unsupported_openai_output_item_done_item_type": ("stream", None),
    "unsupported_openai_output_item_type": ("response", None),
    "unsupported_openai_provider_state_item_type": ("request", None),
    "user_file_parts_require_a_file_attachment_payload": ("request", None),
    "user_messages_can_only_contain_text_and_file_parts": ("request", None),
    "web_search_action_is_invalid": ("hosted_tool", "output[].action"),
    "web_search_action_must_be_a_bounded_string": ("hosted_tool", "output[].action"),
    "web_search_action_must_be_an_object": ("hosted_tool", "output[].action"),
    "web_search_action_queries_must_be_a_bounded_list": ("hosted_tool", "output[].action.queries"),
    "web_search_action_queries_must_be_a_bounded_string": (
        "hosted_tool",
        "output[].action.queries[]",
    ),
    "web_search_action_sources_must_be_a_bounded_list": (
        "hosted_tool",
        "output[].action.sources",
    ),
    "web_search_action_sources_must_be_an_object": ("hosted_tool", "output[].action.sources[]"),
    "web_search_action_sources_title_must_be_a_bounded_string": (
        "hosted_tool",
        "output[].action.sources[].title",
    ),
    "web_search_action_sources_type_is_unsupported": (
        "hosted_tool",
        "output[].action.sources[].type",
    ),
    "web_search_action_type_is_unsupported": ("hosted_tool", "output[].action.type"),
    "web_search_call_identity_is_duplicated_across_output_items": ("response", None),
    "web_search_call_identity_was_reused": ("response", None),
    "web_search_call_item_completed_without_action_evidence": ("response", None),
    "web_search_call_item_has_unsupported_status": ("response", None),
    "web_search_call_item_requires_nonblank_id": ("response", None),
    "web_search_call_output_identity_mismatch": ("response", None),
    "web_search_call_output_item_added_must_be_in_progress": ("stream", None),
    "web_search_call_output_item_added_was_repeated": ("stream", None),
    "web_search_call_output_item_done_arrived_before_added": ("stream", None),
    "web_search_lifecycle_arrived_before_output_item_added": ("stream", None),
    "web_search_lifecycle_item_id_mismatch": ("stream", None),
    "web_search_progress_has_no_pending_call": ("recovery", None),
}


def protocol_diagnostic_fields(reason_code: object) -> dict[str, str]:
    # Reject string subclasses as well as containers before lookup. Always emit
    # canonical catalogue keys, never caller-owned values or overridden methods.
    code = reason_code if type(reason_code) is str else "unspecified"
    if len(code) > 128 or code not in _PROTOCOL_DIAGNOSTICS:
        code = "unspecified"
    stage, field = _PROTOCOL_DIAGNOSTICS[code]
    fields = {"provider_protocol_reason": code, "provider_protocol_stage": stage}
    if field is not None:
        fields["provider_protocol_field"] = field
    return fields
