"""Explicit public exports; implementations load on first access."""

EXPORTS: dict[str, tuple[str, str]] = {
    "BoundedTarReader": ("cayu.workspaces.base", "BoundedTarReader"),
    "BoundedTarStreamReader": ("cayu.workspaces.base", "BoundedTarStreamReader"),
    "DEFAULT_E2B_WORKSPACE_LIST_DEPTH": ("cayu.workspaces.e2b", "DEFAULT_E2B_WORKSPACE_LIST_DEPTH"),
    "DEFAULT_E2B_WORKSPACE_LIST_LIMIT": ("cayu.workspaces.e2b", "DEFAULT_E2B_WORKSPACE_LIST_LIMIT"),
    "DEFAULT_E2B_WORKSPACE_READ_LIMIT_BYTES": (
        "cayu.workspaces.e2b",
        "DEFAULT_E2B_WORKSPACE_READ_LIMIT_BYTES",
    ),
    "DEFAULT_MICROSANDBOX_WORKSPACE_LIST_LIMIT": (
        "cayu.workspaces.microsandbox",
        "DEFAULT_MICROSANDBOX_WORKSPACE_LIST_LIMIT",
    ),
    "DEFAULT_MICROSANDBOX_WORKSPACE_READ_LIMIT_BYTES": (
        "cayu.workspaces.microsandbox",
        "DEFAULT_MICROSANDBOX_WORKSPACE_READ_LIMIT_BYTES",
    ),
    "DEFAULT_RUNNER_WORKSPACE_LIST_LIMIT": (
        "cayu.workspaces.runner",
        "DEFAULT_RUNNER_WORKSPACE_LIST_LIMIT",
    ),
    "DEFAULT_RUNNER_WORKSPACE_READ_LIMIT_BYTES": (
        "cayu.workspaces.runner",
        "DEFAULT_RUNNER_WORKSPACE_READ_LIMIT_BYTES",
    ),
    "E2BWorkspace": ("cayu.workspaces.e2b", "E2BWorkspace"),
    "LocalWorkspace": ("cayu.workspaces.local", "LocalWorkspace"),
    "MicrosandboxWorkspace": ("cayu.workspaces.microsandbox", "MicrosandboxWorkspace"),
    "RemoteWorkspaceBranchAuthorityProvider": (
        "cayu.workspaces.branches",
        "RemoteWorkspaceBranchAuthorityProvider",
    ),
    "RunnerBoundWorkspace": ("cayu.workspaces.base", "RunnerBoundWorkspace"),
    "RunnerWorkspace": ("cayu.workspaces.runner", "RunnerWorkspace"),
    "SessionWorkspaceBranchStore": (
        "cayu.workspaces.branch_lifecycle",
        "SessionWorkspaceBranchStore",
    ),
    "TarStreamReadResult": ("cayu.workspaces.base", "TarStreamReadResult"),
    "TarStreamWriter": ("cayu.workspaces.base", "TarStreamWriter"),
    "TarWriter": ("cayu.workspaces.base", "TarWriter"),
    "Workspace": ("cayu.workspaces.base", "Workspace"),
    "WorkspaceBranch": ("cayu.workspaces.branches", "WorkspaceBranch"),
    "WorkspaceBranchAuthority": ("cayu.workspaces.branches", "WorkspaceBranchAuthority"),
    "WorkspaceBranchBindingAuthority": (
        "cayu.workspaces.branches",
        "WorkspaceBranchBindingAuthority",
    ),
    "WorkspaceBranchBindingAuthorityClaim": (
        "cayu.workspaces.branches",
        "WorkspaceBranchBindingAuthorityClaim",
    ),
    "WorkspaceBranchBindingAuthorityClaimScope": (
        "cayu.workspaces.branches",
        "WorkspaceBranchBindingAuthorityClaimScope",
    ),
    "WorkspaceBranchBindingAuthorityProvider": (
        "cayu.workspaces.branches",
        "WorkspaceBranchBindingAuthorityProvider",
    ),
    "WorkspaceBranchBindingAuthorityRegistry": (
        "cayu.workspaces.branches",
        "WorkspaceBranchBindingAuthorityRegistry",
    ),
    "WorkspaceBranchCapabilities": ("cayu.workspaces.branches", "WorkspaceBranchCapabilities"),
    "WorkspaceBranchChange": ("cayu.workspaces.branches", "WorkspaceBranchChange"),
    "WorkspaceBranchChangeSet": ("cayu.workspaces.branches", "WorkspaceBranchChangeSet"),
    "WorkspaceBranchClosedError": ("cayu.workspaces.branches", "WorkspaceBranchClosedError"),
    "WorkspaceBranchConflict": ("cayu.workspaces.branches", "WorkspaceBranchConflict"),
    "WorkspaceBranchContentIdentity": (
        "cayu.workspaces.branches",
        "WorkspaceBranchContentIdentity",
    ),
    "WorkspaceBranchCreationResult": ("cayu.workspaces.branches", "WorkspaceBranchCreationResult"),
    "WorkspaceBranchDurableState": ("cayu.workspaces.branches", "WorkspaceBranchDurableState"),
    "WorkspaceBranchEvidence": ("cayu.workspaces.branches", "WorkspaceBranchEvidence"),
    "WorkspaceBranchFencedError": ("cayu.workspaces.branches", "WorkspaceBranchFencedError"),
    "WorkspaceBranchLifecycleInspection": (
        "cayu.workspaces.branches",
        "WorkspaceBranchLifecycleInspection",
    ),
    "WorkspaceBranchLifecycleStatus": (
        "cayu.workspaces.branches",
        "WorkspaceBranchLifecycleStatus",
    ),
    "WorkspaceBranchLifecycleSummary": (
        "cayu.workspaces.branches",
        "WorkspaceBranchLifecycleSummary",
    ),
    "WorkspaceBranchLimits": ("cayu.workspaces.branches", "WorkspaceBranchLimits"),
    "WorkspaceBranchOperationConflict": (
        "cayu.workspaces.branches",
        "WorkspaceBranchOperationConflict",
    ),
    "WorkspaceBranchOutcomeStatus": ("cayu.workspaces.branches", "WorkspaceBranchOutcomeStatus"),
    "WorkspaceBranchPublicationError": (
        "cayu.workspaces.branches",
        "WorkspaceBranchPublicationError",
    ),
    "WorkspaceBranchPublicationRequest": (
        "cayu.workspaces.branches",
        "WorkspaceBranchPublicationRequest",
    ),
    "WorkspaceBranchPublicationResult": (
        "cayu.workspaces.branches",
        "WorkspaceBranchPublicationResult",
    ),
    "WorkspaceBranchPublicationStrength": (
        "cayu.workspaces.branches",
        "WorkspaceBranchPublicationStrength",
    ),
    "WorkspaceBranchRecoveryRequest": (
        "cayu.workspaces.branches",
        "WorkspaceBranchRecoveryRequest",
    ),
    "WorkspaceBranchRecoveryResult": ("cayu.workspaces.branches", "WorkspaceBranchRecoveryResult"),
    "WorkspaceBranchRecoveryStrength": (
        "cayu.workspaces.branches",
        "WorkspaceBranchRecoveryStrength",
    ),
    "WorkspaceBranchRequest": ("cayu.workspaces.branches", "WorkspaceBranchRequest"),
    "WorkspaceBranchResourceExhaustedError": (
        "cayu.workspaces.branches",
        "WorkspaceBranchResourceExhaustedError",
    ),
    "WorkspaceBranchRetentionStrength": (
        "cayu.workspaces.branches",
        "WorkspaceBranchRetentionStrength",
    ),
    "WorkspaceBranchRollbackRequest": (
        "cayu.workspaces.branches",
        "WorkspaceBranchRollbackRequest",
    ),
    "WorkspaceBranchRollbackResult": ("cayu.workspaces.branches", "WorkspaceBranchRollbackResult"),
    "WorkspaceBranchStore": ("cayu.workspaces.branches", "WorkspaceBranchStore"),
    "WorkspaceBranchStoreDurability": (
        "cayu.workspaces.branches",
        "WorkspaceBranchStoreDurability",
    ),
    "WorkspaceDirectMutationReconciliation": (
        "cayu.workspaces.revisions",
        "WorkspaceDirectMutationReconciliation",
    ),
    "WorkspaceDirectoryPruner": ("cayu.workspaces.base", "WorkspaceDirectoryPruner"),
    "WorkspaceForkLineage": ("cayu.workspaces.revisions", "WorkspaceForkLineage"),
    "WorkspaceForkLineageStatus": ("cayu.workspaces.revisions", "WorkspaceForkLineageStatus"),
    "WorkspaceGitEntry": ("cayu.workspaces.base", "WorkspaceGitEntry"),
    "WorkspaceGitEntryListResult": ("cayu.workspaces.base", "WorkspaceGitEntryListResult"),
    "WorkspaceGitEntryObservationUnsupportedError": (
        "cayu.workspaces.base",
        "WorkspaceGitEntryObservationUnsupportedError",
    ),
    "WorkspaceGitMode": ("cayu.workspaces.base", "WorkspaceGitMode"),
    "WorkspaceGitModeMismatchError": ("cayu.workspaces.base", "WorkspaceGitModeMismatchError"),
    "WorkspaceGitModeMutator": ("cayu.workspaces.base", "WorkspaceGitModeMutator"),
    "WorkspaceIdentity": ("cayu.workspaces.revisions", "WorkspaceIdentity"),
    "WorkspaceListResult": ("cayu.workspaces.base", "WorkspaceListResult"),
    "WorkspaceMoveAmbiguousError": ("cayu.workspaces.base", "WorkspaceMoveAmbiguousError"),
    "WorkspaceMoveFidelity": ("cayu.workspaces.base", "WorkspaceMoveFidelity"),
    "WorkspaceMoveResult": ("cayu.workspaces.base", "WorkspaceMoveResult"),
    "WorkspaceMoveUnsupportedError": ("cayu.workspaces.base", "WorkspaceMoveUnsupportedError"),
    "WorkspaceMutationAttribution": ("cayu.workspaces.revisions", "WorkspaceMutationAttribution"),
    "WorkspaceMutationAttributionConfidence": (
        "cayu.workspaces.revisions",
        "WorkspaceMutationAttributionConfidence",
    ),
    "WorkspaceMutationResult": ("cayu.workspaces.base", "WorkspaceMutationResult"),
    "WorkspacePathRevision": ("cayu.workspaces.revisions", "WorkspacePathRevision"),
    "WorkspacePathRevisionDelta": ("cayu.workspaces.revisions", "WorkspacePathRevisionDelta"),
    "WorkspacePreconditionUnsupportedError": (
        "cayu.workspaces.base",
        "WorkspacePreconditionUnsupportedError",
    ),
    "WorkspaceReadOffsetError": ("cayu.workspaces.base", "WorkspaceReadOffsetError"),
    "WorkspaceReadResult": ("cayu.workspaces.base", "WorkspaceReadResult"),
    "WorkspaceReferenceBinding": ("cayu.workspaces.references", "WorkspaceReferenceBinding"),
    "WorkspaceReferenceBindingError": (
        "cayu.workspaces.references",
        "WorkspaceReferenceBindingError",
    ),
    "WorkspaceRevisionDelta": ("cayu.workspaces.revisions", "WorkspaceRevisionDelta"),
    "WorkspaceRevisionDeltaStatus": ("cayu.workspaces.revisions", "WorkspaceRevisionDeltaStatus"),
    "WorkspaceRevisionMismatchError": ("cayu.workspaces.base", "WorkspaceRevisionMismatchError"),
    "WorkspaceRevisionObservation": ("cayu.workspaces.revisions", "WorkspaceRevisionObservation"),
    "WorkspaceRevisionObservationLimits": (
        "cayu.workspaces.revisions",
        "WorkspaceRevisionObservationLimits",
    ),
    "WorkspaceRevisionObservationStatus": (
        "cayu.workspaces.revisions",
        "WorkspaceRevisionObservationStatus",
    ),
    "WorkspaceWriterIsolationEvidence": (
        "cayu.workspaces.revisions",
        "WorkspaceWriterIsolationEvidence",
    ),
    "WorkspaceWriterIsolationStatus": (
        "cayu.workspaces.revisions",
        "WorkspaceWriterIsolationStatus",
    ),
    "compare_workspace_revisions": ("cayu.workspaces.revisions", "compare_workspace_revisions"),
    "matches_list_pattern": ("cayu.workspaces.base", "matches_list_pattern"),
    "translate_list_pattern": ("cayu.workspaces.base", "translate_list_pattern"),
    "validate_list_pattern": ("cayu.workspaces.base", "validate_list_pattern"),
}

PUBLIC_NAMES = [
    "BoundedTarReader",
    "BoundedTarStreamReader",
    "DEFAULT_E2B_WORKSPACE_LIST_DEPTH",
    "DEFAULT_E2B_WORKSPACE_LIST_LIMIT",
    "DEFAULT_E2B_WORKSPACE_READ_LIMIT_BYTES",
    "DEFAULT_MICROSANDBOX_WORKSPACE_LIST_LIMIT",
    "DEFAULT_MICROSANDBOX_WORKSPACE_READ_LIMIT_BYTES",
    "DEFAULT_RUNNER_WORKSPACE_LIST_LIMIT",
    "DEFAULT_RUNNER_WORKSPACE_READ_LIMIT_BYTES",
    "E2BWorkspace",
    "LocalWorkspace",
    "MicrosandboxWorkspace",
    "RemoteWorkspaceBranchAuthorityProvider",
    "RunnerBoundWorkspace",
    "RunnerWorkspace",
    "SessionWorkspaceBranchStore",
    "TarStreamReadResult",
    "TarStreamWriter",
    "TarWriter",
    "Workspace",
    "WorkspaceBranch",
    "WorkspaceBranchAuthority",
    "WorkspaceBranchBindingAuthority",
    "WorkspaceBranchBindingAuthorityClaim",
    "WorkspaceBranchBindingAuthorityClaimScope",
    "WorkspaceBranchBindingAuthorityProvider",
    "WorkspaceBranchBindingAuthorityRegistry",
    "WorkspaceBranchCapabilities",
    "WorkspaceBranchChange",
    "WorkspaceBranchChangeSet",
    "WorkspaceBranchClosedError",
    "WorkspaceBranchConflict",
    "WorkspaceBranchContentIdentity",
    "WorkspaceBranchCreationResult",
    "WorkspaceBranchDurableState",
    "WorkspaceBranchEvidence",
    "WorkspaceBranchFencedError",
    "WorkspaceBranchLifecycleInspection",
    "WorkspaceBranchLifecycleStatus",
    "WorkspaceBranchLifecycleSummary",
    "WorkspaceBranchLimits",
    "WorkspaceBranchOperationConflict",
    "WorkspaceBranchOutcomeStatus",
    "WorkspaceBranchPublicationError",
    "WorkspaceBranchPublicationRequest",
    "WorkspaceBranchPublicationResult",
    "WorkspaceBranchPublicationStrength",
    "WorkspaceBranchRecoveryRequest",
    "WorkspaceBranchRecoveryResult",
    "WorkspaceBranchRecoveryStrength",
    "WorkspaceBranchRequest",
    "WorkspaceBranchResourceExhaustedError",
    "WorkspaceBranchRetentionStrength",
    "WorkspaceBranchRollbackRequest",
    "WorkspaceBranchRollbackResult",
    "WorkspaceBranchStore",
    "WorkspaceBranchStoreDurability",
    "WorkspaceDirectMutationReconciliation",
    "WorkspaceDirectoryPruner",
    "WorkspaceForkLineage",
    "WorkspaceForkLineageStatus",
    "WorkspaceGitEntry",
    "WorkspaceGitEntryListResult",
    "WorkspaceGitEntryObservationUnsupportedError",
    "WorkspaceGitMode",
    "WorkspaceGitModeMismatchError",
    "WorkspaceGitModeMutator",
    "WorkspaceIdentity",
    "WorkspaceListResult",
    "WorkspaceMoveAmbiguousError",
    "WorkspaceMoveFidelity",
    "WorkspaceMoveResult",
    "WorkspaceMoveUnsupportedError",
    "WorkspaceMutationAttribution",
    "WorkspaceMutationAttributionConfidence",
    "WorkspaceMutationResult",
    "WorkspacePathRevision",
    "WorkspacePathRevisionDelta",
    "WorkspacePreconditionUnsupportedError",
    "WorkspaceReadOffsetError",
    "WorkspaceReadResult",
    "WorkspaceReferenceBinding",
    "WorkspaceReferenceBindingError",
    "WorkspaceRevisionDelta",
    "WorkspaceRevisionDeltaStatus",
    "WorkspaceRevisionMismatchError",
    "WorkspaceRevisionObservation",
    "WorkspaceRevisionObservationLimits",
    "WorkspaceRevisionObservationStatus",
    "WorkspaceWriterIsolationEvidence",
    "WorkspaceWriterIsolationStatus",
    "compare_workspace_revisions",
    "matches_list_pattern",
    "translate_list_pattern",
    "validate_list_pattern",
]
