"""Explicit public exports; implementations load on first access."""

EXPORTS: dict[str, tuple[str, str]] = {
    "TaskGroupInvocationSettlementPending": (
        "cayu.runtime._task_group_invocation",
        "TaskGroupInvocationSettlementPending",
    ),
    "TaskExecutionSettlementPending": (
        "cayu.tasks._execution_settlement",
        "TaskExecutionSettlementPending",
    ),
    "TaskGroupCreate": ("cayu.tasks.groups", "TaskGroupCreate"),
    "TaskGroupQuiescencePolicy": ("cayu.tasks.groups", "TaskGroupQuiescencePolicy"),
    "TaskGroupQuiescenceStatus": ("cayu.tasks.groups", "TaskGroupQuiescenceStatus"),
    "TaskGroupQuiescence": ("cayu.tasks.groups", "TaskGroupQuiescence"),
    "TaskGroupFinalizerStatus": ("cayu.tasks.groups", "TaskGroupFinalizerStatus"),
    "TaskGroupExecutionObligation": ("cayu.tasks.groups", "TaskGroupExecutionObligation"),
    "TaskGroupInvocationObligation": ("cayu.tasks.groups", "TaskGroupInvocationObligation"),
    "TaskGroupQuiescenceResolution": ("cayu.tasks.groups", "TaskGroupQuiescenceResolution"),
    "TaskGroupPolicy": ("cayu.tasks.groups", "TaskGroupPolicy"),
    "TaskGroupCreationReceipt": ("cayu.tasks.groups", "TaskGroupCreationReceipt"),
    "TaskGroupSnapshot": ("cayu.tasks.groups", "TaskGroupSnapshot"),
    "TaskGroupDecision": ("cayu.tasks.groups", "TaskGroupDecision"),
    "TaskGroupStatus": ("cayu.tasks.groups", "TaskGroupStatus"),
    "TaskGroupEvent": ("cayu.tasks.groups", "TaskGroupEvent"),
    "TaskGroupEventType": ("cayu.tasks.groups", "TaskGroupEventType"),
    "TaskGroupConflict": ("cayu.tasks.groups", "TaskGroupConflict"),
    "TaskGroupUnavailable": ("cayu.tasks.groups", "TaskGroupUnavailable"),
    "TaskGraphConflict": ("cayu.tasks.graphs", "TaskGraphConflict"),
    "TaskGraphCreate": ("cayu.tasks.graphs", "TaskGraphCreate"),
    "TaskGraphCreationReceipt": ("cayu.tasks.graphs", "TaskGraphCreationReceipt"),
    "TaskGraphEvent": ("cayu.tasks.graphs", "TaskGraphEvent"),
    "TaskGraphEventType": ("cayu.tasks.graphs", "TaskGraphEventType"),
    "TaskGraphMember": ("cayu.tasks.graphs", "TaskGraphMember"),
    "TaskGraphNode": ("cayu.tasks.graphs", "TaskGraphNode"),
    "TaskGraphSnapshot": ("cayu.tasks.graphs", "TaskGraphSnapshot"),
    "TaskGraphUnavailable": ("cayu.tasks.graphs", "TaskGraphUnavailable"),
    "TaskMisfirePolicy": ("cayu.tasks.scheduling", "TaskMisfirePolicy"),
    "TaskRescheduleRequest": ("cayu.tasks.scheduling", "TaskRescheduleRequest"),
    "TaskScheduleCancelRequest": ("cayu.tasks.scheduling", "TaskScheduleCancelRequest"),
    "TaskScheduleConflict": ("cayu.tasks.scheduling", "TaskScheduleConflict"),
    "TaskScheduleEligibility": ("cayu.tasks.scheduling", "TaskScheduleEligibility"),
    "TaskScheduleEvent": ("cayu.tasks.scheduling", "TaskScheduleEvent"),
    "TaskScheduleEventType": ("cayu.tasks.scheduling", "TaskScheduleEventType"),
    "TaskSchedulePolicy": ("cayu.tasks.scheduling", "TaskSchedulePolicy"),
    "TaskScheduleReceipt": ("cayu.tasks.scheduling", "TaskScheduleReceipt"),
    "TaskScheduleState": ("cayu.tasks.scheduling", "TaskScheduleState"),
    "TaskScheduleWakeup": ("cayu.tasks.scheduling", "TaskScheduleWakeup"),
    "TaskSessionClosureClaim": ("cayu.tasks.base", "TaskSessionClosureClaim"),
    "AdmittedCompletionProposalRequest": (
        "cayu.tasks.admission",
        "AdmittedCompletionProposalRequest",
    ),
    "CompletionConstraintOutcome": ("cayu.tasks.contracts", "CompletionConstraintOutcome"),
    "CompletionContinuationPolicy": ("cayu.tasks.contracts", "CompletionContinuationPolicy"),
    "CompletionCriterionOutcome": ("cayu.tasks.contracts", "CompletionCriterionOutcome"),
    "CompletionDecision": ("cayu.tasks.contracts", "CompletionDecision"),
    "CompletionDecisionApplicationReceipt": (
        "cayu.tasks.base",
        "CompletionDecisionApplicationReceipt",
    ),
    "CompletionDecisionApplicationRequest": (
        "cayu.tasks.contracts",
        "CompletionDecisionApplicationRequest",
    ),
    "CompletionDecisionCreate": ("cayu.tasks.contracts", "CompletionDecisionCreate"),
    "CompletionGap": ("cayu.tasks.contracts", "CompletionGap"),
    "CompletionProposal": ("cayu.tasks.contracts", "CompletionProposal"),
    "CompletionProposalCreate": ("cayu.tasks.contracts", "CompletionProposalCreate"),
    "CompletionRejectionAction": ("cayu.tasks.contracts", "CompletionRejectionAction"),
    "CompletionResultReference": ("cayu.tasks.contracts", "CompletionResultReference"),
    "CompletionResultResolverRef": ("cayu.tasks.contracts", "CompletionResultResolverRef"),
    "CompletionSatisfactionBasis": ("cayu.tasks.contracts", "CompletionSatisfactionBasis"),
    "CompletionVerdict": ("cayu.tasks.contracts", "CompletionVerdict"),
    "CompletionVerificationClaim": ("cayu.tasks.contracts", "CompletionVerificationClaim"),
    "CompletionVerificationClaimLost": ("cayu.tasks.contracts", "CompletionVerificationClaimLost"),
    "CompletionVerificationClaimRequest": (
        "cayu.tasks.contracts",
        "CompletionVerificationClaimRequest",
    ),
    "CompletionVerifierDecision": ("cayu.tasks.contracts", "CompletionVerifierDecision"),
    "CompletionVerifierKind": ("cayu.tasks.contracts", "CompletionVerifierKind"),
    "CompletionVerifierRef": ("cayu.tasks.contracts", "CompletionVerifierRef"),
    "CriterionOutcomeStatus": ("cayu.tasks.contracts", "CriterionOutcomeStatus"),
    "DispatchHandle": ("cayu.tasks.dispatch", "DispatchHandle"),
    "DispatchRequest": ("cayu.tasks.dispatch", "DispatchRequest"),
    "DispatchRuntime": ("cayu.tasks.dispatch", "DispatchRuntime"),
    "DispatchStatus": ("cayu.tasks.dispatch", "DispatchStatus"),
    "Dispatcher": ("cayu.tasks.dispatch", "Dispatcher"),
    "InMemoryTaskStore": ("cayu.tasks.base", "InMemoryTaskStore"),
    "InlineDispatcher": ("cayu.tasks.dispatch", "InlineDispatcher"),
    "InterruptedTaskContinuationClaimPage": (
        "cayu.tasks.base",
        "InterruptedTaskContinuationClaimPage",
    ),
    "Task": ("cayu.tasks.records", "Task"),
    "TaskAggregateFilter": ("cayu.tasks.base", "TaskAggregateFilter"),
    "TaskCancellationReconciliation": ("cayu.tasks.base", "TaskCancellationReconciliation"),
    "TaskCancellationReconciliationConflict": (
        "cayu.tasks.base",
        "TaskCancellationReconciliationConflict",
    ),
    "TaskCancellationReconciliationEvent": (
        "cayu.tasks.base",
        "TaskCancellationReconciliationEvent",
    ),
    "TaskCancellationReconciliationEventType": (
        "cayu.tasks.base",
        "TaskCancellationReconciliationEventType",
    ),
    "TaskCancellationReconciliationEvidence": (
        "cayu.tasks.base",
        "TaskCancellationReconciliationEvidence",
    ),
    "TaskCancellationReconciliationOutcome": (
        "cayu.tasks.base",
        "TaskCancellationReconciliationOutcome",
    ),
    "TaskCancellationReconciliationRejected": (
        "cayu.tasks.base",
        "TaskCancellationReconciliationRejected",
    ),
    "TaskCancellationReconciliationRequest": (
        "cayu.tasks.base",
        "TaskCancellationReconciliationRequest",
    ),
    "TaskCancellationReconciliationResult": (
        "cayu.tasks.base",
        "TaskCancellationReconciliationResult",
    ),
    "TaskClaimLost": ("cayu.tasks.base", "TaskClaimLost"),
    "TaskCompletionDecisionRequired": ("cayu.tasks.contracts", "TaskCompletionDecisionRequired"),
    "TaskCreate": ("cayu.tasks.base", "TaskCreate"),
    "TaskHandlerOutcome": ("cayu.tasks.worker", "TaskHandlerOutcome"),
    "TaskInterruptedHandoffConflict": ("cayu.tasks.base", "TaskInterruptedHandoffConflict"),
    "TaskInterruptedHandoffReceipt": ("cayu.tasks.base", "TaskInterruptedHandoffReceipt"),
    "TaskInterruptedHandoffRequest": ("cayu.tasks.base", "TaskInterruptedHandoffRequest"),
    "TaskInvocationSnapshot": ("cayu.tasks.base", "TaskInvocationSnapshot"),
    "TaskOperationalSnapshot": ("cayu.tasks.base", "TaskOperationalSnapshot"),
    "TaskOrder": ("cayu.tasks.base", "TaskOrder"),
    "TaskQuery": ("cayu.tasks.base", "TaskQuery"),
    "TaskRetryAttemptDisposition": ("cayu.tasks.base", "TaskRetryAttemptDisposition"),
    "TaskRetryAttemptReport": ("cayu.tasks.base", "TaskRetryAttemptReport"),
    "TaskRetryCancellationReconciliation": (
        "cayu.tasks.base",
        "TaskRetryCancellationReconciliation",
    ),
    "TaskRetryCancellationReconciliationConflict": (
        "cayu.tasks.base",
        "TaskRetryCancellationReconciliationConflict",
    ),
    "TaskRetryCancellationReconciliationEvent": (
        "cayu.tasks.base",
        "TaskRetryCancellationReconciliationEvent",
    ),
    "TaskRetryCancellationReconciliationEventType": (
        "cayu.tasks.base",
        "TaskRetryCancellationReconciliationEventType",
    ),
    "TaskRetryCancellationReconciliationEvidence": (
        "cayu.tasks.base",
        "TaskRetryCancellationReconciliationEvidence",
    ),
    "TaskRetryCancellationReconciliationOutcome": (
        "cayu.tasks.base",
        "TaskRetryCancellationReconciliationOutcome",
    ),
    "TaskRetryCancellationReconciliationRejected": (
        "cayu.tasks.base",
        "TaskRetryCancellationReconciliationRejected",
    ),
    "TaskRetryCancellationReconciliationRequest": (
        "cayu.tasks.base",
        "TaskRetryCancellationReconciliationRequest",
    ),
    "TaskRetryEvent": ("cayu.tasks.base", "TaskRetryEvent"),
    "TaskRetryEventType": ("cayu.tasks.base", "TaskRetryEventType"),
    "TaskRetryPolicy": ("cayu.tasks.records", "TaskRetryPolicy"),
    "TaskRetrySeriesDisposition": ("cayu.tasks.records", "TaskRetrySeriesDisposition"),
    "TaskRetrySeriesSnapshot": ("cayu.tasks.records", "TaskRetrySeriesSnapshot"),
    "TaskRetrySettlementRequest": ("cayu.tasks.base", "TaskRetrySettlementRequest"),
    "TaskRetrySettlementResult": ("cayu.tasks.base", "TaskRetrySettlementResult"),
    "TaskStatus": ("cayu.tasks.records", "TaskStatus"),
    "TaskStatusCounts": ("cayu.tasks.base", "TaskStatusCounts"),
    "TaskStore": ("cayu.tasks.base", "TaskStore"),
    "TaskStoreDispatcher": ("cayu.tasks.dispatch", "TaskStoreDispatcher"),
    "TaskTerminalKind": ("cayu.tasks.base", "TaskTerminalKind"),
    "TaskTerminalizationConflict": ("cayu.tasks.base", "TaskTerminalizationConflict"),
    "TaskTerminalizationReceipt": ("cayu.tasks.base", "TaskTerminalizationReceipt"),
    "TaskTerminalizationRequest": ("cayu.tasks.base", "TaskTerminalizationRequest"),
    "TaskTerminalizationRetryPolicy": ("cayu.tasks.base", "TaskTerminalizationRetryPolicy"),
    "TaskTerminalizationRetryResult": ("cayu.tasks.base", "TaskTerminalizationRetryResult"),
    "TaskTerminalizationUncertain": ("cayu.tasks.base", "TaskTerminalizationUncertain"),
    "TaskTopologyChildBranch": ("cayu.tasks.topology", "TaskTopologyChildBranch"),
    "TaskTopologyCycle": ("cayu.tasks.topology", "TaskTopologyCycle"),
    "TaskTopologyInconsistent": ("cayu.tasks.topology", "TaskTopologyInconsistent"),
    "TaskTopologyNode": ("cayu.tasks.topology", "TaskTopologyNode"),
    "TaskTopologyQuery": ("cayu.tasks.topology", "TaskTopologyQuery"),
    "TaskTopologySessionBranch": ("cayu.tasks.topology", "TaskTopologySessionBranch"),
    "TaskTopologyStoreResult": ("cayu.tasks.topology", "TaskTopologyStoreResult"),
    "TaskTopologyTraversalLimitExceeded": (
        "cayu.tasks.topology",
        "TaskTopologyTraversalLimitExceeded",
    ),
    "WorkAttempt": ("cayu.tasks.contracts", "WorkAttempt"),
    "WorkAttemptAdmission": ("cayu.tasks.admission", "WorkAttemptAdmission"),
    "WorkAttemptAdmissionActivate": ("cayu.tasks.admission", "WorkAttemptAdmissionActivate"),
    "WorkAttemptAdmissionConflict": ("cayu.tasks.admission", "WorkAttemptAdmissionConflict"),
    "WorkAttemptAdmissionPrepare": ("cayu.tasks.admission", "WorkAttemptAdmissionPrepare"),
    "WorkAttemptAdmissionState": ("cayu.tasks.admission", "WorkAttemptAdmissionState"),
    "WorkAttemptClaimRenewalRequest": ("cayu.tasks.admission", "WorkAttemptClaimRenewalRequest"),
    "WorkAttemptContinuationContext": ("cayu.tasks.admission", "WorkAttemptContinuationContext"),
    "WorkAttemptCreate": ("cayu.tasks.contracts", "WorkAttemptCreate"),
    "WorkAttemptExecutionClaim": ("cayu.tasks.admission", "WorkAttemptExecutionClaim"),
    "WorkAttemptExecutionClaimLost": ("cayu.tasks.admission", "WorkAttemptExecutionClaimLost"),
    "WorkAttemptExecutionClaimRequest": (
        "cayu.tasks.admission",
        "WorkAttemptExecutionClaimRequest",
    ),
    "WorkAttemptExecutionRequest": ("cayu.tasks.admission", "WorkAttemptExecutionRequest"),
    "WorkAttemptProposalRequest": ("cayu.tasks.admission", "WorkAttemptProposalRequest"),
    "WorkAttemptRecoveryActivate": ("cayu.tasks.admission", "WorkAttemptRecoveryActivate"),
    "WorkAttemptRecoveryRequest": ("cayu.tasks.admission", "WorkAttemptRecoveryRequest"),
    "WorkAttemptRecoveryRequired": ("cayu.tasks.admission", "WorkAttemptRecoveryRequired"),
    "WorkCompletionConflict": ("cayu.tasks.contracts", "WorkCompletionConflict"),
    "WorkConstraint": ("cayu.tasks.contracts", "WorkConstraint"),
    "WorkContract": ("cayu.tasks.contracts", "WorkContract"),
    "WorkContractConflict": ("cayu.tasks.contracts", "WorkContractConflict"),
    "WorkContractDraft": ("cayu.tasks.contracts", "WorkContractDraft"),
    "WorkContractRef": ("cayu.tasks.contracts", "WorkContractRef"),
    "WorkCriterion": ("cayu.tasks.contracts", "WorkCriterion"),
    "WorkEvidenceReference": ("cayu.tasks.contracts", "WorkEvidenceReference"),
    "WorkEvidenceRequirement": ("cayu.tasks.contracts", "WorkEvidenceRequirement"),
    "complete_managed_task": ("cayu.tasks.worker", "complete_managed_task"),
    "completion_gap_fingerprint": ("cayu.tasks.contracts", "completion_gap_fingerprint"),
    "completion_result_sha256": ("cayu.tasks.contracts", "completion_result_sha256"),
    "copy_dispatch_handle": ("cayu.tasks.dispatch", "copy_dispatch_handle"),
    "copy_dispatch_request": ("cayu.tasks.dispatch", "copy_dispatch_request"),
    "fail_managed_task": ("cayu.tasks.worker", "fail_managed_task"),
    "interrupted_task_handoff_request": ("cayu.tasks.base", "interrupted_task_handoff_request"),
    "new_interrupted_task_continuation_handoff_id": (
        "cayu.tasks.base",
        "new_interrupted_task_continuation_handoff_id",
    ),
    "run_task_worker": ("cayu.tasks.worker", "run_task_worker"),
    "settle_task_retry_attempt_with_retry": (
        "cayu.tasks.base",
        "settle_task_retry_attempt_with_retry",
    ),
    "task_create_with_execution_source": ("cayu.tasks.base", "task_create_with_execution_source"),
    "task_invocation_for_create": ("cayu.tasks.base", "task_invocation_for_create"),
    "terminalize_task_with_retry": ("cayu.tasks.base", "terminalize_task_with_retry"),
    "work_contract_fingerprint": ("cayu.tasks.contracts", "work_contract_fingerprint"),
    "work_contract_from_draft": ("cayu.tasks.contracts", "work_contract_from_draft"),
    "CompletionVerifierDecodeStatus": (
        "cayu.tasks.completion_verifier_dispatches",
        "CompletionVerifierDecodeStatus",
    ),
    "CompletionVerifierDispatch": (
        "cayu.tasks.completion_verifier_dispatches",
        "CompletionVerifierDispatch",
    ),
    "CompletionVerifierDispatchBudget": (
        "cayu.tasks.completion_verifier_dispatches",
        "CompletionVerifierDispatchBudget",
    ),
    "CompletionVerifierDispatchBudgetExhausted": (
        "cayu.tasks.completion_verifier_dispatches",
        "CompletionVerifierDispatchBudgetExhausted",
    ),
    "CompletionVerifierDispatchFailure": (
        "cayu.tasks.completion_verifier_dispatches",
        "CompletionVerifierDispatchFailure",
    ),
    "CompletionVerifierDispatchOutcome": (
        "cayu.tasks.completion_verifier_dispatches",
        "CompletionVerifierDispatchOutcome",
    ),
    "CompletionVerifierDispatchRequest": (
        "cayu.tasks.completion_verifier_dispatches",
        "CompletionVerifierDispatchRequest",
    ),
    "CompletionVerifierDispatchSettlement": (
        "cayu.tasks.completion_verifier_dispatches",
        "CompletionVerifierDispatchSettlement",
    ),
    "CompletionVerifierDispatchSettlementRequest": (
        "cayu.tasks.completion_verifier_dispatches",
        "CompletionVerifierDispatchSettlementRequest",
    ),
    "CompletionVerifierUsageStatus": (
        "cayu.tasks.completion_verifier_dispatches",
        "CompletionVerifierUsageStatus",
    ),
    "CompletionEvaluationPolicy": ("cayu.tasks.contracts", "CompletionEvaluationPolicy"),
    "CompletionEvaluatorRef": ("cayu.tasks.contracts", "CompletionEvaluatorRef"),
    "CompletionEvaluationBudgetExhausted": (
        "cayu.tasks.completion_evaluations",
        "CompletionEvaluationBudgetExhausted",
    ),
    "CompletionEvaluationFailure": (
        "cayu.tasks.completion_evaluations",
        "CompletionEvaluationFailure",
    ),
    "CompletionEvaluationOutcome": (
        "cayu.tasks.completion_evaluations",
        "CompletionEvaluationOutcome",
    ),
    "CompletionEvaluationReceipt": (
        "cayu.tasks.completion_evaluations",
        "CompletionEvaluationReceipt",
    ),
    "CompletionEvaluationRun": ("cayu.tasks.completion_evaluations", "CompletionEvaluationRun"),
    "CompletionEvaluationRunRequest": (
        "cayu.tasks.completion_evaluations",
        "CompletionEvaluationRunRequest",
    ),
    "CompletionEvaluationSettlement": (
        "cayu.tasks.completion_evaluations",
        "CompletionEvaluationSettlement",
    ),
    "CompletionEvaluationSettlementRequest": (
        "cayu.tasks.completion_evaluations",
        "CompletionEvaluationSettlementRequest",
    ),
}

PUBLIC_NAMES = [
    "TaskGroupCreate",
    "TaskGroupQuiescencePolicy",
    "TaskGroupQuiescenceStatus",
    "TaskGroupQuiescence",
    "TaskGroupFinalizerStatus",
    "TaskGroupExecutionObligation",
    "TaskGroupInvocationObligation",
    "TaskGroupQuiescenceResolution",
    "TaskGroupPolicy",
    "TaskGroupCreationReceipt",
    "TaskGroupSnapshot",
    "TaskGroupDecision",
    "TaskGroupStatus",
    "TaskGroupEvent",
    "TaskGroupEventType",
    "TaskGroupConflict",
    "TaskExecutionSettlementPending",
    "TaskGroupInvocationSettlementPending",
    "TaskGroupUnavailable",
    "TaskGraphCreate",
    "TaskGraphNode",
    "TaskGraphCreationReceipt",
    "TaskGraphSnapshot",
    "TaskGraphMember",
    "TaskGraphEvent",
    "TaskGraphEventType",
    "TaskGraphConflict",
    "TaskGraphUnavailable",
    "TaskSessionClosureClaim",
    "AdmittedCompletionProposalRequest",
    "CompletionConstraintOutcome",
    "CompletionContinuationPolicy",
    "CompletionCriterionOutcome",
    "CompletionDecision",
    "CompletionDecisionApplicationReceipt",
    "CompletionDecisionApplicationRequest",
    "CompletionDecisionCreate",
    "CompletionGap",
    "CompletionProposal",
    "CompletionProposalCreate",
    "CompletionRejectionAction",
    "CompletionResultReference",
    "CompletionResultResolverRef",
    "CompletionSatisfactionBasis",
    "CompletionVerdict",
    "CompletionVerificationClaim",
    "CompletionVerificationClaimLost",
    "CompletionVerificationClaimRequest",
    "CompletionVerifierDecision",
    "CompletionVerifierKind",
    "CompletionVerifierRef",
    "CriterionOutcomeStatus",
    "DispatchHandle",
    "DispatchRequest",
    "DispatchRuntime",
    "DispatchStatus",
    "Dispatcher",
    "InMemoryTaskStore",
    "InlineDispatcher",
    "InterruptedTaskContinuationClaimPage",
    "Task",
    "TaskAggregateFilter",
    "TaskCancellationReconciliation",
    "TaskCancellationReconciliationConflict",
    "TaskCancellationReconciliationEvent",
    "TaskCancellationReconciliationEventType",
    "TaskCancellationReconciliationEvidence",
    "TaskCancellationReconciliationOutcome",
    "TaskCancellationReconciliationRejected",
    "TaskCancellationReconciliationRequest",
    "TaskCancellationReconciliationResult",
    "TaskClaimLost",
    "TaskCompletionDecisionRequired",
    "TaskCreate",
    "TaskMisfirePolicy",
    "TaskRescheduleRequest",
    "TaskScheduleCancelRequest",
    "TaskScheduleConflict",
    "TaskScheduleEligibility",
    "TaskScheduleEvent",
    "TaskScheduleEventType",
    "TaskSchedulePolicy",
    "TaskScheduleReceipt",
    "TaskScheduleState",
    "TaskScheduleWakeup",
    "TaskHandlerOutcome",
    "TaskInterruptedHandoffConflict",
    "TaskInterruptedHandoffReceipt",
    "TaskInterruptedHandoffRequest",
    "TaskInvocationSnapshot",
    "TaskOperationalSnapshot",
    "TaskOrder",
    "TaskQuery",
    "TaskRetryAttemptDisposition",
    "TaskRetryAttemptReport",
    "TaskRetryCancellationReconciliation",
    "TaskRetryCancellationReconciliationConflict",
    "TaskRetryCancellationReconciliationEvent",
    "TaskRetryCancellationReconciliationEventType",
    "TaskRetryCancellationReconciliationEvidence",
    "TaskRetryCancellationReconciliationOutcome",
    "TaskRetryCancellationReconciliationRejected",
    "TaskRetryCancellationReconciliationRequest",
    "TaskRetryEvent",
    "TaskRetryEventType",
    "TaskRetryPolicy",
    "TaskRetrySeriesDisposition",
    "TaskRetrySeriesSnapshot",
    "TaskRetrySettlementRequest",
    "TaskRetrySettlementResult",
    "TaskStatus",
    "TaskStatusCounts",
    "TaskStore",
    "TaskStoreDispatcher",
    "TaskTerminalKind",
    "TaskTerminalizationConflict",
    "TaskTerminalizationReceipt",
    "TaskTerminalizationRequest",
    "TaskTerminalizationRetryPolicy",
    "TaskTerminalizationRetryResult",
    "TaskTerminalizationUncertain",
    "TaskTopologyChildBranch",
    "TaskTopologyCycle",
    "TaskTopologyInconsistent",
    "TaskTopologyNode",
    "TaskTopologyQuery",
    "TaskTopologySessionBranch",
    "TaskTopologyStoreResult",
    "TaskTopologyTraversalLimitExceeded",
    "WorkAttempt",
    "WorkAttemptAdmission",
    "WorkAttemptAdmissionActivate",
    "WorkAttemptAdmissionConflict",
    "WorkAttemptAdmissionPrepare",
    "WorkAttemptAdmissionState",
    "WorkAttemptClaimRenewalRequest",
    "WorkAttemptContinuationContext",
    "WorkAttemptCreate",
    "WorkAttemptExecutionClaim",
    "WorkAttemptExecutionClaimLost",
    "WorkAttemptExecutionClaimRequest",
    "WorkAttemptExecutionRequest",
    "WorkAttemptProposalRequest",
    "WorkAttemptRecoveryActivate",
    "WorkAttemptRecoveryRequest",
    "WorkAttemptRecoveryRequired",
    "WorkCompletionConflict",
    "WorkConstraint",
    "WorkContract",
    "WorkContractConflict",
    "WorkContractDraft",
    "WorkContractRef",
    "WorkCriterion",
    "WorkEvidenceReference",
    "WorkEvidenceRequirement",
    "complete_managed_task",
    "completion_gap_fingerprint",
    "completion_result_sha256",
    "copy_dispatch_handle",
    "copy_dispatch_request",
    "fail_managed_task",
    "interrupted_task_handoff_request",
    "new_interrupted_task_continuation_handoff_id",
    "run_task_worker",
    "settle_task_retry_attempt_with_retry",
    "task_create_with_execution_source",
    "task_invocation_for_create",
    "terminalize_task_with_retry",
    "work_contract_fingerprint",
    "work_contract_from_draft",
    "CompletionVerifierDecodeStatus",
    "CompletionVerifierDispatch",
    "CompletionVerifierDispatchBudget",
    "CompletionVerifierDispatchBudgetExhausted",
    "CompletionVerifierDispatchFailure",
    "CompletionVerifierDispatchOutcome",
    "CompletionVerifierDispatchRequest",
    "CompletionVerifierDispatchSettlement",
    "CompletionVerifierDispatchSettlementRequest",
    "CompletionVerifierUsageStatus",
    "CompletionEvaluationPolicy",
    "CompletionEvaluatorRef",
    "CompletionEvaluationBudgetExhausted",
    "CompletionEvaluationFailure",
    "CompletionEvaluationOutcome",
    "CompletionEvaluationReceipt",
    "CompletionEvaluationRun",
    "CompletionEvaluationRunRequest",
    "CompletionEvaluationSettlement",
    "CompletionEvaluationSettlementRequest",
]
