"""Explicit public exports; implementations load on first access."""

EXPORTS: dict[str, tuple[str, str]] = {
    "AdmittedCompletionProposalRequest": (
        "cayu.tasks.admission",
        "AdmittedCompletionProposalRequest",
    ),
    "CompletionConstraintOutcome": ("cayu.tasks.contracts", "CompletionConstraintOutcome"),
    "CompletionContinuationPolicy": ("cayu.tasks.contracts", "CompletionContinuationPolicy"),
    "CompletionCriterionOutcome": ("cayu.tasks.contracts", "CompletionCriterionOutcome"),
    "CompletionDecision": ("cayu.tasks.contracts", "CompletionDecision"),
    "CompletionDecisionApplicationReceipt": (
        "cayu.tasks.base",
        "CompletionDecisionApplicationReceipt",
    ),
    "CompletionDecisionApplicationRequest": (
        "cayu.tasks.contracts",
        "CompletionDecisionApplicationRequest",
    ),
    "CompletionDecisionCreate": ("cayu.tasks.contracts", "CompletionDecisionCreate"),
    "CompletionGap": ("cayu.tasks.contracts", "CompletionGap"),
    "CompletionProposal": ("cayu.tasks.contracts", "CompletionProposal"),
    "CompletionProposalCreate": ("cayu.tasks.contracts", "CompletionProposalCreate"),
    "CompletionRejectionAction": ("cayu.tasks.contracts", "CompletionRejectionAction"),
    "CompletionResultReference": ("cayu.tasks.contracts", "CompletionResultReference"),
    "CompletionResultResolverRef": ("cayu.tasks.contracts", "CompletionResultResolverRef"),
    "CompletionSatisfactionBasis": ("cayu.tasks.contracts", "CompletionSatisfactionBasis"),
    "CompletionVerdict": ("cayu.tasks.contracts", "CompletionVerdict"),
    "CompletionVerificationClaim": ("cayu.tasks.contracts", "CompletionVerificationClaim"),
    "CompletionVerificationClaimLost": ("cayu.tasks.contracts", "CompletionVerificationClaimLost"),
    "CompletionVerificationClaimRequest": (
        "cayu.tasks.contracts",
        "CompletionVerificationClaimRequest",
    ),
    "CompletionVerifierDecision": ("cayu.tasks.contracts", "CompletionVerifierDecision"),
    "CompletionVerifierKind": ("cayu.tasks.contracts", "CompletionVerifierKind"),
    "CompletionVerifierRef": ("cayu.tasks.contracts", "CompletionVerifierRef"),
    "CriterionOutcomeStatus": ("cayu.tasks.contracts", "CriterionOutcomeStatus"),
    "DispatchHandle": ("cayu.tasks.dispatch", "DispatchHandle"),
    "DispatchRequest": ("cayu.tasks.dispatch", "DispatchRequest"),
    "DispatchRuntime": ("cayu.tasks.dispatch", "DispatchRuntime"),
    "DispatchStatus": ("cayu.tasks.dispatch", "DispatchStatus"),
    "Dispatcher": ("cayu.tasks.dispatch", "Dispatcher"),
    "InMemoryTaskStore": ("cayu.tasks.base", "InMemoryTaskStore"),
    "InlineDispatcher": ("cayu.tasks.dispatch", "InlineDispatcher"),
    "InterruptedTaskContinuationClaimPage": (
        "cayu.tasks.base",
        "InterruptedTaskContinuationClaimPage",
    ),
    "Task": ("cayu.tasks.base", "Task"),
    "TaskAggregateFilter": ("cayu.tasks.base", "TaskAggregateFilter"),
    "TaskCancellationReconciliation": ("cayu.tasks.base", "TaskCancellationReconciliation"),
    "TaskCancellationReconciliationConflict": (
        "cayu.tasks.base",
        "TaskCancellationReconciliationConflict",
    ),
    "TaskCancellationReconciliationEvent": (
        "cayu.tasks.base",
        "TaskCancellationReconciliationEvent",
    ),
    "TaskCancellationReconciliationEventType": (
        "cayu.tasks.base",
        "TaskCancellationReconciliationEventType",
    ),
    "TaskCancellationReconciliationEvidence": (
        "cayu.tasks.base",
        "TaskCancellationReconciliationEvidence",
    ),
    "TaskCancellationReconciliationOutcome": (
        "cayu.tasks.base",
        "TaskCancellationReconciliationOutcome",
    ),
    "TaskCancellationReconciliationRejected": (
        "cayu.tasks.base",
        "TaskCancellationReconciliationRejected",
    ),
    "TaskCancellationReconciliationRequest": (
        "cayu.tasks.base",
        "TaskCancellationReconciliationRequest",
    ),
    "TaskCancellationReconciliationResult": (
        "cayu.tasks.base",
        "TaskCancellationReconciliationResult",
    ),
    "TaskClaimLost": ("cayu.tasks.base", "TaskClaimLost"),
    "TaskCompletionDecisionRequired": ("cayu.tasks.contracts", "TaskCompletionDecisionRequired"),
    "TaskCreate": ("cayu.tasks.base", "TaskCreate"),
    "TaskHandlerOutcome": ("cayu.tasks.worker", "TaskHandlerOutcome"),
    "TaskInterruptedHandoffConflict": ("cayu.tasks.base", "TaskInterruptedHandoffConflict"),
    "TaskInterruptedHandoffReceipt": ("cayu.tasks.base", "TaskInterruptedHandoffReceipt"),
    "TaskInterruptedHandoffRequest": ("cayu.tasks.base", "TaskInterruptedHandoffRequest"),
    "TaskInvocationSnapshot": ("cayu.tasks.base", "TaskInvocationSnapshot"),
    "TaskOperationalSnapshot": ("cayu.tasks.base", "TaskOperationalSnapshot"),
    "TaskOrder": ("cayu.tasks.base", "TaskOrder"),
    "TaskQuery": ("cayu.tasks.base", "TaskQuery"),
    "TaskRetryAttemptDisposition": ("cayu.tasks.base", "TaskRetryAttemptDisposition"),
    "TaskRetryAttemptReport": ("cayu.tasks.base", "TaskRetryAttemptReport"),
    "TaskRetryCancellationReconciliation": (
        "cayu.tasks.base",
        "TaskRetryCancellationReconciliation",
    ),
    "TaskRetryCancellationReconciliationConflict": (
        "cayu.tasks.base",
        "TaskRetryCancellationReconciliationConflict",
    ),
    "TaskRetryCancellationReconciliationEvent": (
        "cayu.tasks.base",
        "TaskRetryCancellationReconciliationEvent",
    ),
    "TaskRetryCancellationReconciliationEventType": (
        "cayu.tasks.base",
        "TaskRetryCancellationReconciliationEventType",
    ),
    "TaskRetryCancellationReconciliationEvidence": (
        "cayu.tasks.base",
        "TaskRetryCancellationReconciliationEvidence",
    ),
    "TaskRetryCancellationReconciliationOutcome": (
        "cayu.tasks.base",
        "TaskRetryCancellationReconciliationOutcome",
    ),
    "TaskRetryCancellationReconciliationRejected": (
        "cayu.tasks.base",
        "TaskRetryCancellationReconciliationRejected",
    ),
    "TaskRetryCancellationReconciliationRequest": (
        "cayu.tasks.base",
        "TaskRetryCancellationReconciliationRequest",
    ),
    "TaskRetryEvent": ("cayu.tasks.base", "TaskRetryEvent"),
    "TaskRetryEventType": ("cayu.tasks.base", "TaskRetryEventType"),
    "TaskRetryPolicy": ("cayu.tasks.base", "TaskRetryPolicy"),
    "TaskRetrySeriesDisposition": ("cayu.tasks.base", "TaskRetrySeriesDisposition"),
    "TaskRetrySeriesSnapshot": ("cayu.tasks.base", "TaskRetrySeriesSnapshot"),
    "TaskRetrySettlementRequest": ("cayu.tasks.base", "TaskRetrySettlementRequest"),
    "TaskRetrySettlementResult": ("cayu.tasks.base", "TaskRetrySettlementResult"),
    "TaskStatus": ("cayu.tasks.base", "TaskStatus"),
    "TaskStatusCounts": ("cayu.tasks.base", "TaskStatusCounts"),
    "TaskStore": ("cayu.tasks.base", "TaskStore"),
    "TaskStoreDispatcher": ("cayu.tasks.dispatch", "TaskStoreDispatcher"),
    "TaskTerminalKind": ("cayu.tasks.base", "TaskTerminalKind"),
    "TaskTerminalizationConflict": ("cayu.tasks.base", "TaskTerminalizationConflict"),
    "TaskTerminalizationReceipt": ("cayu.tasks.base", "TaskTerminalizationReceipt"),
    "TaskTerminalizationRequest": ("cayu.tasks.base", "TaskTerminalizationRequest"),
    "TaskTerminalizationRetryPolicy": ("cayu.tasks.base", "TaskTerminalizationRetryPolicy"),
    "TaskTerminalizationRetryResult": ("cayu.tasks.base", "TaskTerminalizationRetryResult"),
    "TaskTerminalizationUncertain": ("cayu.tasks.base", "TaskTerminalizationUncertain"),
    "TaskTopologyChildBranch": ("cayu.tasks.base", "TaskTopologyChildBranch"),
    "TaskTopologyCycle": ("cayu.tasks.base", "TaskTopologyCycle"),
    "TaskTopologyInconsistent": ("cayu.tasks.base", "TaskTopologyInconsistent"),
    "TaskTopologyNode": ("cayu.tasks.base", "TaskTopologyNode"),
    "TaskTopologyQuery": ("cayu.tasks.base", "TaskTopologyQuery"),
    "TaskTopologySessionBranch": ("cayu.tasks.base", "TaskTopologySessionBranch"),
    "TaskTopologyStoreResult": ("cayu.tasks.base", "TaskTopologyStoreResult"),
    "TaskTopologyTraversalLimitExceeded": ("cayu.tasks.base", "TaskTopologyTraversalLimitExceeded"),
    "WorkAttempt": ("cayu.tasks.contracts", "WorkAttempt"),
    "WorkAttemptAdmission": ("cayu.tasks.admission", "WorkAttemptAdmission"),
    "WorkAttemptAdmissionActivate": ("cayu.tasks.admission", "WorkAttemptAdmissionActivate"),
    "WorkAttemptAdmissionConflict": ("cayu.tasks.admission", "WorkAttemptAdmissionConflict"),
    "WorkAttemptAdmissionPrepare": ("cayu.tasks.admission", "WorkAttemptAdmissionPrepare"),
    "WorkAttemptAdmissionState": ("cayu.tasks.admission", "WorkAttemptAdmissionState"),
    "WorkAttemptClaimRenewalRequest": ("cayu.tasks.admission", "WorkAttemptClaimRenewalRequest"),
    "WorkAttemptContinuationContext": ("cayu.tasks.admission", "WorkAttemptContinuationContext"),
    "WorkAttemptCreate": ("cayu.tasks.contracts", "WorkAttemptCreate"),
    "WorkAttemptExecutionClaim": ("cayu.tasks.admission", "WorkAttemptExecutionClaim"),
    "WorkAttemptExecutionClaimLost": ("cayu.tasks.admission", "WorkAttemptExecutionClaimLost"),
    "WorkAttemptExecutionClaimRequest": (
        "cayu.tasks.admission",
        "WorkAttemptExecutionClaimRequest",
    ),
    "WorkAttemptExecutionRequest": ("cayu.tasks.admission", "WorkAttemptExecutionRequest"),
    "WorkAttemptProposalRequest": ("cayu.tasks.admission", "WorkAttemptProposalRequest"),
    "WorkAttemptRecoveryActivate": ("cayu.tasks.admission", "WorkAttemptRecoveryActivate"),
    "WorkAttemptRecoveryRequest": ("cayu.tasks.admission", "WorkAttemptRecoveryRequest"),
    "WorkAttemptRecoveryRequired": ("cayu.tasks.admission", "WorkAttemptRecoveryRequired"),
    "WorkCompletionConflict": ("cayu.tasks.contracts", "WorkCompletionConflict"),
    "WorkConstraint": ("cayu.tasks.contracts", "WorkConstraint"),
    "WorkContract": ("cayu.tasks.contracts", "WorkContract"),
    "WorkContractConflict": ("cayu.tasks.contracts", "WorkContractConflict"),
    "WorkContractDraft": ("cayu.tasks.contracts", "WorkContractDraft"),
    "WorkContractRef": ("cayu.tasks.contracts", "WorkContractRef"),
    "WorkCriterion": ("cayu.tasks.contracts", "WorkCriterion"),
    "WorkEvidenceReference": ("cayu.tasks.contracts", "WorkEvidenceReference"),
    "WorkEvidenceRequirement": ("cayu.tasks.contracts", "WorkEvidenceRequirement"),
    "complete_managed_task": ("cayu.tasks.worker", "complete_managed_task"),
    "completion_gap_fingerprint": ("cayu.tasks.contracts", "completion_gap_fingerprint"),
    "completion_result_sha256": ("cayu.tasks.contracts", "completion_result_sha256"),
    "copy_dispatch_handle": ("cayu.tasks.dispatch", "copy_dispatch_handle"),
    "copy_dispatch_request": ("cayu.tasks.dispatch", "copy_dispatch_request"),
    "fail_managed_task": ("cayu.tasks.worker", "fail_managed_task"),
    "interrupted_task_handoff_request": ("cayu.tasks.base", "interrupted_task_handoff_request"),
    "new_interrupted_task_continuation_handoff_id": (
        "cayu.tasks.base",
        "new_interrupted_task_continuation_handoff_id",
    ),
    "run_task_worker": ("cayu.tasks.worker", "run_task_worker"),
    "settle_task_retry_attempt_with_retry": (
        "cayu.tasks.base",
        "settle_task_retry_attempt_with_retry",
    ),
    "task_create_with_execution_source": ("cayu.tasks.base", "task_create_with_execution_source"),
    "task_invocation_for_create": ("cayu.tasks.base", "task_invocation_for_create"),
    "terminalize_task_with_retry": ("cayu.tasks.base", "terminalize_task_with_retry"),
    "work_contract_fingerprint": ("cayu.tasks.contracts", "work_contract_fingerprint"),
    "work_contract_from_draft": ("cayu.tasks.contracts", "work_contract_from_draft"),
}

PUBLIC_NAMES = [
    "AdmittedCompletionProposalRequest",
    "CompletionConstraintOutcome",
    "CompletionContinuationPolicy",
    "CompletionCriterionOutcome",
    "CompletionDecision",
    "CompletionDecisionApplicationReceipt",
    "CompletionDecisionApplicationRequest",
    "CompletionDecisionCreate",
    "CompletionGap",
    "CompletionProposal",
    "CompletionProposalCreate",
    "CompletionRejectionAction",
    "CompletionResultReference",
    "CompletionResultResolverRef",
    "CompletionSatisfactionBasis",
    "CompletionVerdict",
    "CompletionVerificationClaim",
    "CompletionVerificationClaimLost",
    "CompletionVerificationClaimRequest",
    "CompletionVerifierDecision",
    "CompletionVerifierKind",
    "CompletionVerifierRef",
    "CriterionOutcomeStatus",
    "DispatchHandle",
    "DispatchRequest",
    "DispatchRuntime",
    "DispatchStatus",
    "Dispatcher",
    "InMemoryTaskStore",
    "InlineDispatcher",
    "InterruptedTaskContinuationClaimPage",
    "Task",
    "TaskAggregateFilter",
    "TaskCancellationReconciliation",
    "TaskCancellationReconciliationConflict",
    "TaskCancellationReconciliationEvent",
    "TaskCancellationReconciliationEventType",
    "TaskCancellationReconciliationEvidence",
    "TaskCancellationReconciliationOutcome",
    "TaskCancellationReconciliationRejected",
    "TaskCancellationReconciliationRequest",
    "TaskCancellationReconciliationResult",
    "TaskClaimLost",
    "TaskCompletionDecisionRequired",
    "TaskCreate",
    "TaskHandlerOutcome",
    "TaskInterruptedHandoffConflict",
    "TaskInterruptedHandoffReceipt",
    "TaskInterruptedHandoffRequest",
    "TaskInvocationSnapshot",
    "TaskOperationalSnapshot",
    "TaskOrder",
    "TaskQuery",
    "TaskRetryAttemptDisposition",
    "TaskRetryAttemptReport",
    "TaskRetryCancellationReconciliation",
    "TaskRetryCancellationReconciliationConflict",
    "TaskRetryCancellationReconciliationEvent",
    "TaskRetryCancellationReconciliationEventType",
    "TaskRetryCancellationReconciliationEvidence",
    "TaskRetryCancellationReconciliationOutcome",
    "TaskRetryCancellationReconciliationRejected",
    "TaskRetryCancellationReconciliationRequest",
    "TaskRetryEvent",
    "TaskRetryEventType",
    "TaskRetryPolicy",
    "TaskRetrySeriesDisposition",
    "TaskRetrySeriesSnapshot",
    "TaskRetrySettlementRequest",
    "TaskRetrySettlementResult",
    "TaskStatus",
    "TaskStatusCounts",
    "TaskStore",
    "TaskStoreDispatcher",
    "TaskTerminalKind",
    "TaskTerminalizationConflict",
    "TaskTerminalizationReceipt",
    "TaskTerminalizationRequest",
    "TaskTerminalizationRetryPolicy",
    "TaskTerminalizationRetryResult",
    "TaskTerminalizationUncertain",
    "TaskTopologyChildBranch",
    "TaskTopologyCycle",
    "TaskTopologyInconsistent",
    "TaskTopologyNode",
    "TaskTopologyQuery",
    "TaskTopologySessionBranch",
    "TaskTopologyStoreResult",
    "TaskTopologyTraversalLimitExceeded",
    "WorkAttempt",
    "WorkAttemptAdmission",
    "WorkAttemptAdmissionActivate",
    "WorkAttemptAdmissionConflict",
    "WorkAttemptAdmissionPrepare",
    "WorkAttemptAdmissionState",
    "WorkAttemptClaimRenewalRequest",
    "WorkAttemptContinuationContext",
    "WorkAttemptCreate",
    "WorkAttemptExecutionClaim",
    "WorkAttemptExecutionClaimLost",
    "WorkAttemptExecutionClaimRequest",
    "WorkAttemptExecutionRequest",
    "WorkAttemptProposalRequest",
    "WorkAttemptRecoveryActivate",
    "WorkAttemptRecoveryRequest",
    "WorkAttemptRecoveryRequired",
    "WorkCompletionConflict",
    "WorkConstraint",
    "WorkContract",
    "WorkContractConflict",
    "WorkContractDraft",
    "WorkContractRef",
    "WorkCriterion",
    "WorkEvidenceReference",
    "WorkEvidenceRequirement",
    "complete_managed_task",
    "completion_gap_fingerprint",
    "completion_result_sha256",
    "copy_dispatch_handle",
    "copy_dispatch_request",
    "fail_managed_task",
    "interrupted_task_handoff_request",
    "new_interrupted_task_continuation_handoff_id",
    "run_task_worker",
    "settle_task_retry_attempt_with_retry",
    "task_create_with_execution_source",
    "task_invocation_for_create",
    "terminalize_task_with_retry",
    "work_contract_fingerprint",
    "work_contract_from_draft",
]
