"""Explicit public exports; implementations load on first access."""

EXPORTS: dict[str, tuple[str, str]] = {
    "Any": ("cayu.testing.base", "Any"),
    "BaseModel": ("cayu.testing.base", "BaseModel"),
    "Callable": ("cayu.testing.base", "Callable"),
    "CayuApp": ("cayu.testing.base", "CayuApp"),
    "ConfigDict": ("cayu.testing.base", "ConfigDict"),
    "ExecCommand": ("cayu.testing.base", "ExecCommand"),
    "Iterable": ("cayu.testing.base", "Iterable"),
    "Literal": ("cayu.testing.base", "Literal"),
    "LocalRunner": ("cayu.testing.base", "LocalRunner"),
    "LocalWorkspace": ("cayu.testing.base", "LocalWorkspace"),
    "Mapping": ("cayu.testing.base", "Mapping"),
    "ProcessIsolatedTool": ("cayu.testing.base", "ProcessIsolatedTool"),
    "ProviderCredentialIsolationVerification": (
        "cayu.testing.base",
        "ProviderCredentialIsolationVerification",
    ),
    "ProviderCredentialIsolationViolation": (
        "cayu.testing.base",
        "ProviderCredentialIsolationViolation",
    ),
    "Runner": ("cayu.testing.base", "Runner"),
    "StrEnum": ("cayu.testing.base", "StrEnum"),
    "StrictBool": ("cayu.testing.base", "StrictBool"),
    "ToolContext": ("cayu.testing.base", "ToolContext"),
    "ToolEffect": ("cayu.testing.base", "ToolEffect"),
    "ToolEffectVerification": ("cayu.testing.base", "ToolEffectVerification"),
    "ToolEffectVerificationStatus": ("cayu.testing.base", "ToolEffectVerificationStatus"),
    "ToolResult": ("cayu.testing.base", "ToolResult"),
    "asyncio": ("cayu.testing.base", "asyncio"),
    "copy_durable_json_object": ("cayu.testing.base", "copy_durable_json_object"),
    "copy_json_value": ("cayu.testing.base", "copy_json_value"),
    "dataclass": ("cayu.testing.base", "dataclass"),
    "field_validator": ("cayu.testing.base", "field_validator"),
    "hashlib": ("cayu.testing.base", "hashlib"),
    "isfinite": ("cayu.testing.base", "isfinite"),
    "json": ("cayu.testing.base", "json"),
    "model_validator": ("cayu.testing.base", "model_validator"),
    "os": ("cayu.testing.base", "os"),
    "re": ("cayu.testing.base", "re"),
    "require_clean_nonblank": ("cayu.testing.base", "require_clean_nonblank"),
    "require_durable_clean_nonblank": ("cayu.testing.base", "require_durable_clean_nonblank"),
    "require_durable_nonblank": ("cayu.testing.base", "require_durable_nonblank"),
    "require_durable_text": ("cayu.testing.base", "require_durable_text"),
    "require_nonblank": ("cayu.testing.base", "require_nonblank"),
    "tempfile": ("cayu.testing.base", "tempfile"),
    "verify_provider_credential_isolation": (
        "cayu.testing.base",
        "verify_provider_credential_isolation",
    ),
    "verify_tool_effect": ("cayu.testing.base", "verify_tool_effect"),
}

PUBLIC_NAMES = [
    "Any",
    "BaseModel",
    "Callable",
    "CayuApp",
    "ConfigDict",
    "ExecCommand",
    "Iterable",
    "Literal",
    "LocalRunner",
    "LocalWorkspace",
    "Mapping",
    "ProcessIsolatedTool",
    "ProviderCredentialIsolationVerification",
    "ProviderCredentialIsolationViolation",
    "Runner",
    "StrEnum",
    "StrictBool",
    "ToolContext",
    "ToolEffect",
    "ToolEffectVerification",
    "ToolEffectVerificationStatus",
    "ToolResult",
    "asyncio",
    "copy_durable_json_object",
    "copy_json_value",
    "dataclass",
    "field_validator",
    "hashlib",
    "isfinite",
    "json",
    "model_validator",
    "os",
    "re",
    "require_clean_nonblank",
    "require_durable_clean_nonblank",
    "require_durable_nonblank",
    "require_durable_text",
    "require_nonblank",
    "tempfile",
    "verify_provider_credential_isolation",
    "verify_tool_effect",
]
